### ISSUE TITLE
The default data doesn't show when remember attribute is set

### ISSUE THREAD

**Issue by AshishDhamalaAD** [protonemedia/laravel-splade#10]
When I do it like this, it works perfectly fine. The word 'Laratips' is shown in the input file like so:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/65481305/180636242-287152e8-f486-43fd-9534-8dc95fc5ad38.png">
<img width="380" alt="image" src="https://user-images.githubusercontent.com/65481305/180636279-2f689815-1d03-41ec-88f1-262d95bbe05b.png">

But, as soon as I write remember attribute, it does not show the default value. The input file becomes empty as shown here:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/65481305/180636302-c2c5ab71-a96a-4956-8488-b65618729bc1.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/65481305/180636306-72d8c904-ec6d-40a2-8f24-0cf81027443f.png">

**Comment by pascalbaljet** [comment]
Fixed in v0.1.2. Be sure to update both with composer and npm.
