### ISSUE TITLE
Request to alter modal positions

### ISSUE THREAD

**Issue by MotionPhix** [protonemedia/laravel-splade#101]
I wanted to ask if it would be possible to have the modal position movable vertically. Right now, the **container to center the modal panel** uses **`flex min-h-full items-center justify-center`** classes. From that, I wanted to be able to pass say an attribute (maybe like the one we pass to the modal itself for **max-width**) but now for **position** and its value could be **`top, default or bottom`**. These values will translate to (say if you put *position: 'top'*) **items-start**, **items-center** for *position: 'default'* and *items-end* for *position: 'bottom'*

**Comment by MotionPhix** [comment]
OK, I found a way to do it. I just passed a prop to the SpladeModal and use that to change classes accordingly.

**Comment by pascalbaljet** [comment]
Will be fixed in #158

**Comment by pascalbaljet** [comment]
@MotionPhix I've added the `position` attribute in v1.1.1. You can set it to either `top`, `center`, or `bottom`. It defaults to `center` :)

```blade
<x-splade-modal position="top">
    ...
</x-splade-modal>
```

**Comment by MotionPhix** [comment]
Wow! Thanks. This is great news! Oh, let me get to it already.
