### ISSUE TITLE
Redirect with method 'DELETE' after destroy-request

### ISSUE THREAD

**Issue by J87NL** [protonemedia/laravel-splade#102]
Possibly related to https://github.com/protonemedia/laravel-splade/issues/69#issuecomment-1304840600

In my blade I have the following:
```
                        <x-splade-form
                            action="{{ route('posts.destroy', ['post' => $post]) }}"
                            method="delete"
                            confirm
                        >
                            <x-splade-submit>{{ __('Delete') }}</x-splade-submit>
                        </x-splade-form>
```
which posts to:
```
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('posts.index');
    }
```

The delete is successful but the redirect results in:

```
Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
The DELETE method is not supported for this route. Supported methods: GET, HEAD, POST. 
```

Where Laravel applications 
![Schermafdruk van 2022-11-06 19-08-52](https://user-images.githubusercontent.com/16107428/200187920-4a3c93b0-6ed7-43e4-b3a9-1c49a97f6dba.png)
usually do a POST-request with a `_method: DELETE` and CSRF-token in the body:

I see in Splade a DELETE-request (which results in a DELETE-request for the redirect):
![Schermafdruk van 2022-11-06 19-13-30](https://user-images.githubusercontent.com/16107428/200187951-c49c90e8-fae7-46ff-aa2b-afe148580af7.png)

Workaround for now is to show `return $this->index();` instead of `return redirect()->route('posts.index');` after the delete.

**Comment by MotionPhix** [comment]
I think there was a bug in versions prior to v0.65. If you can upgrade to that version or any other above v0.65, you will get that to work, unless otherwise.

**Comment by J87NL** [comment]
Sorry, forgot to mention that I tested in both v0.6.13 and v0.7.1 of Splade.

**Comment by MotionPhix** [comment]
Oh. And how do your web routes look like? Prior to my response, there was a similar issue addressed on [twitter](https://twitter.com/_motionplus/status/1581758572676886530). It turned out that an update was required. And I have never had any issues after that.

**Comment by J87NL** [comment]
I'm using just a normal Route::resource() for this.

**Comment by pascalbaljet** [comment]
Thanks for sharing, I'll take a look at it!

Splade uses Laravel's [Method Spoofing](https://laravel.com/docs/9.x/routing#form-method-spoofing), so it shouldn't make a `DELETE` request.
https://github.com/protonemedia/laravel-splade/blob/127d161a49b6ecd751ea78f16bc5cf820749f2ca/lib/Components/Form.vue#L288-L291

**Comment by J87NL** [comment]
My apologies, apparently my package.json was running behind having "@protonemedia/laravel-splade": "^0.5.0" instead of "0.6.0". I did update with composer but not the npm-packages.

I installed a fresh Laravel application with the latest protonemedia/laravel-splade-breeze, placed my models, views and controllers in it and now it's working like a charm.

This fixes https://github.com/protonemedia/laravel-splade/issues/69 as well.

**Comment by MotionPhix** [comment]
I knew something was wrong with the packages, as pointed out that it was
fixed in a tweet through upgrade. Glad you figured it out finally

**Comment by pascalbaljet** [comment]
Glad you've found the issue, and good to hear you're enjoying it!

**Comment by brunoalfred** [comment]
https://user-images.githubusercontent.com/55545250/202216660-b9459679-f58b-478d-b971-d0924afc0901.mov

```html
<x-splade-form :default="$role" :action="route('roles.update', $role)" method="put"> ... </x-splade-form>
```
