### ISSUE TITLE
Open modals without binding to routes

### ISSUE THREAD

**Issue by MotionPhix** [protonemedia/laravel-splade#104]
Is it possible to open modals without binding them to a route? I have a modal for a mobile menu (it's only available on small screens) that I am struggling to get to work perfectly.

_Originally posted by @MotionPhix in https://github.com/protonemedia/laravel-splade/issues/86#issuecomment-1304878424_

![01](https://user-images.githubusercontent.com/59722054/200212453-782fc390-346f-4b10-8f08-de1f4d9b7f94.png)

The photo above shows how my app looks like on mobile phones. When I click on the hamburger menu, I get the following picture:

![02](https://user-images.githubusercontent.com/59722054/200212598-bfec8e85-4550-4172-b028-0485321fed23.png)

As you can see, It is working. I am able to load the menu in a modal but there is a problem. Since for now we load modals attached to a certain route, look at my web routes snippet below.

![04](https://user-images.githubusercontent.com/59722054/200213028-94685f88-07c1-432f-9798-4e44e85598d3.png)

From the picture above you can see how I have attached the modal to **/menu** route. The problem with this is that I am unable to tell which route to change as active in the mobile modal menu. If you take a look at the picture, I echoed out **request()->url()** in the modal and it shows **http::/tracker.test/menu** instead of the route I am at now which is **http://tracker.test**, which is the Dashboard.

![05](https://user-images.githubusercontent.com/59722054/200213508-99f58db4-9dac-4e26-8e09-e70c2054e029.png)

The following picture shows how the routes contradict each other

![06](https://user-images.githubusercontent.com/59722054/200213967-95f3287a-8fee-48c8-8608-f05de43cbd6d.png)

This is because we are loading modals in routes and at times (like this time) we may just need to load a modal not to attach it to a route. Is that a possibility we could look forward to or we find alternative solutions?

**Comment by pascalbaljet** [comment]
You can only use the built-in Modal feature by using a dedicated route. The Modal is a dedicated component (not bound to Splade's SPA capabilities), so I'll look into how to reuse it for menus.

**Comment by pascalbaljet** [comment]
```blade
{{-- Page... --}}

<Link href="#menu-modal">Preloaded modal</Link>
<Link href="#menu-slideover">Preloaded slideover</Link>

<x-splade-modal modal name="menu-modal">
    <h1>Check out my modal!</h1>
</x-splade-modal>

<x-splade-modal slideover name="menu-slideover">
    <h1>Check out my slideover!</h1>
</x-splade-modal>
```

I've got it working by putting a `name` attribute to the `x-splade-modal` element and using a `#` anchor in the `Link` component. The other thing that's different from loading a route is you have to predefine the type (`modal` or `slideover`) on the `x-splade-modal` element instead of the `Link` component.

**Comment by MotionPhix** [comment]
That's great! Let me take a look into that. On the other hand, where do I place the **x-splade-modal** in this case? In a separate file or on the same page as the **Link**?

**Comment by pascalbaljet** [comment]
Can be anywhere in the template, but when it's a menu, I think it makes sense to put it somewhere in the layout template.

**Comment by MotionPhix** [comment]
Tried it but it's giving me a couple of errors. First error is that x-splade-modal complains about modal and name properties being passed but not being inherited automatically since x-splade-modal is rendered to nodes. Second error is that if I remove the modal property on the Link, the menu modal doesn't work. It doesn't open. It kind of tries to just reload the page. So if I put it back on the Link, it works but at times it opens multiple menu modals.

**Comment by pascalbaljet** [comment]
Ohh it's not released yet! 😅 #105

**Comment by pascalbaljet** [comment]
Fixed in v0.7.2 🔥

Docs: https://splade.dev/docs/x-modal

**Comment by MotionPhix** [comment]
> Fixed in v0.7.2 🔥
> 
> Docs: https://splade.dev/docs/x-modal

I think the documentation on this is not thorough. There should be information about where to place the **x-splade-modal** component in this scenario, because I just tried it, putting the modal in a different location and it didn't work. How does splade know where to find the document to load it in the modal? If it's scanning all the folders, wouldn't that be placing a performance issue if I have so many files? On another note, the whole modal is just broken right now. It looks like it's working but if you open the developer tools in the browser, you'll a lot of errors there about x-splade-modal has been passed a name attribute which can't be inherited because it renders nodes. If you are not looking at the developer tools console, it appears to work, but I don't want to be seeing those errors there

**Comment by MotionPhix** [comment]
https://user-images.githubusercontent.com/59722054/201908685-f62e3cb6-244c-445a-b6ed-b00729c3ad34.mp4

Look at the above video. I implemented the modal like before the preloaded modals were introduced. Below is the code producing the above condition

![Capture1](https://user-images.githubusercontent.com/59722054/201909236-4b833bfe-19fa-4e49-a9ef-aa4f81d4a441.PNG)

![Capture](https://user-images.githubusercontent.com/59722054/201909267-66e25546-b9a8-4ed3-8a8f-5ef5ee5fde8f.PNG)

While it seems like it's working, but I don't want to be seeing those errors in the console. And that's version 0.7.3 and splade-breeze 1.3.0 and laravel 9.19

**Comment by pascalbaljet** [comment]
The pre-loaded Modal auto-registers if it's on the same page. Check out the docs, you need to use a `name` attribute on the Modal component *and* an href value with a `#` prefix on the Link component.

**Comment by MotionPhix** [comment]
> The pre-loaded Modal auto-registers if it's on the same page. Check out the docs, you need to use a `name` attribute on the Modal component _and_ an href value with a `#` prefix on the Link component.

I checked out the docs. In the docs it doesn't state where to place the pre-loaded Modal. Should the name attribute be the name of the file in the **_components_** folder? Or the name attribute has nothing to do with file locations? Let's say the file I want to load in the pre-loaded modal is in the layouts folder, will that just work by putting any name on the **_Link_** and **x-splade-modal** in the **_layouts_** folder?

On a separate note from these pre-loaded modals, the normal modal is also broken in the latest release. Like I showed you in the [video attached above](https://user-images.githubusercontent.com/59722054/201908685-f62e3cb6-244c-445a-b6ed-b00729c3ad34.mp4), v0.7.3 was doing that and now v0.7.4 is still not working. Just throws errors and doesn't load the modal. The errors are as follows in the console:

![errors_1](https://user-images.githubusercontent.com/59722054/202107750-f562a87c-6f79-4ec2-9790-c64a15d38aa3.PNG)

If you get it working without errors, probably I am doing something wrong, but in a fresh laravel project, installing splade defaults to 0.6.13.

**Comment by bdsumon4u** [comment]
Have you followed the [Upgrading](https://splade.dev/docs/upgrading) guideline properly?
```php
composer update protonemedia/laravel-splade
npm upgrade @protonemedia/laravel-splade
php artisan view:clear
```
Have you run all of the above commands?

**Comment by MotionPhix** [comment]
I did more than that. I deleted the node_modules folder and the vendor folder. I also deleted the composer lock file and the package.jason lockfile . Then I run the upgrade command. Have you tried version 0.7.4 yourself? Is everything working properly?

**Comment by sahnb** [comment]
what you want to achieved , modal perfectly work. 
![image](https://user-images.githubusercontent.com/8742640/202253526-2c836098-00ce-45c1-83dc-dff4f3ebfb8f.png)
![image](https://user-images.githubusercontent.com/8742640/202253780-8577d729-d139-40b1-baa7-cbaa63c49011.png)
![image](https://user-images.githubusercontent.com/8742640/202255607-84a5b76f-e65d-476d-9e4d-50fca567c09c.png)
![image](https://user-images.githubusercontent.com/8742640/202255931-e0346e9e-19aa-45ac-8191-a0d2dfc0a9c6.png)
![image](https://user-images.githubusercontent.com/8742640/202256021-43d9f140-f1cc-43dc-a321-e092e2c2e399.png)

**Comment by MotionPhix** [comment]
Wow! Sorry, team. My bad. As I was looking into the docs about upgrading, I saw a section that says _**@protonemedia/laravel-splade**_ version should match _**protonemedia/laravel-splade**_. Mine were not matching even after I run `npm upgrade @protonemedia/laravel-splade`. So I manually upgraded by writing matching versions for both. And now it's working fine. 

Thanks, team. Sorry for the trouble, especially to you @pascalbaljet
