### ISSUE TITLE
[Feature Request] Confirm password when submitting form or a useForm helper for vue.

### ISSUE THREAD

**Issue by bdsumon4u** [protonemedia/laravel-splade#108]
**Similar to Splade's [Confirmation](https://splade.dev/docs/x-form#:~:text=Confirmation,form%20is%20submitted%3A) feature.**

I was dealing with a _**critical**_ form that should require password confirmation. Unfortunately, I couldn't implement that with Splade. I was trying to use a [custom vue component](https://splade.dev/docs/custom-vue-components). But it was very difficult because Splade doesn't provide [Inertia's useForm like helper](https://inertiajs.com/forms#:~:text=for%20more%20information.-,Form%20helper,-Since%20working%20with) to work with the features like __wasSuccessful, recentlySuccessful, errors__ easily on custom vue component.

**What I am requesting is:**
If I use `confirm-password="route-for-confirming-password"` instead of `confirm` attribute on x-splade-form component then the confirmation modal will ask for my password. It will validate the password using the given route. If the password is correct then the form will be submitted. Otherwise, validation errors will be shown.
**Example:** In Jetstream's [Two Factor Authentication](https://jetstream.laravel.com/2.x/features/two-factor-authentication.html), if I click on **Enable** button then a modal opens for password.

The default route will be `password.confirm`.
If I use Laravel Fortify or Jetstream then I've got a `password.confirm` route provided by Fortify.
Or if I don't use Laravel Fortify, then my custom controller will be a clone of Fortify's `Laravel\Fortify\Http\Controllers\ConfirmablePasswordController`.

**_Alternatively_** I can just add an extra `password` field on my form and add the validation logic to password validation rules. But this feature is very much repetitive in my project. So, instead of repeating these, I'm highly interested to have this feature using a single attribute on the form component.

### Note:
_This is a less important feature. You can just ignore it. But `useForm` like helper will be a good feature for working with custom forms. So I'm requesting you to extract some logic from Splade's [Form.vue](https://github.com/protonemedia/laravel-splade/blob/main/lib/Components/Form.vue) component and provide a form helper._

**Comment by bdsumon4u** [comment]
Following [The Last Example](https://github.com/protonemedia/laravel-splade/issues/99#issuecomment-1320271722:~:text=And%20then%20in%20the%20Blade%20template%3A) here, I can pass `form` object to custom vue components. So, I can work without `useForm` helper.

**Comment by pascalbaljet** [comment]
As of v1.2.2, this is built-in:

`<x-splade-form confirm require-password>`

Check out the docs for more information: https://splade.dev/docs/x-form
