### ISSUE TITLE
form.processing never shows

### ISSUE THREAD

**Issue by AshishDhamalaAD** [protonemedia/laravel-splade#11]
I am using `x-splade-form` component.

When I submit the form, form.processing is never true I guess. The text inside the `p` tag with the `v-if="form.processing"` check is never rendered.

Here is the code I used:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/65481305/180638358-f8651363-80ed-431f-b0c5-02dbe01cf5bd.png">

When clicked on submit it only shows this but not the pending state:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/65481305/180638375-adc47e4f-73d2-46f0-96c2-020c2d70704e.png">

I even tried by making slow 3g on the network tab on chrome.

**Comment by pascalbaljet** [comment]
Fixed in v0.1.2. Be sure to update both with composer and npm.
