### ISSUE TITLE
[Feature Request] Option for default order on defaultSort of SpladeTable

### ISSUE THREAD

**Issue by sdiama** [protonemedia/laravel-splade#111]
It will be nice to have a second option at the `defaultSort()` method of SpladeTable to select the default order (ascending/descending). E.x.

`$table->defaultSort('id', 'DESC')`

**Comment by bdsumon4u** [comment]
> $table->defaultSort('`-id`')

**Comment by pascalbaljet** [comment]
I'll add the second argument to the `defaultSort` methods, and a new `defaultSortDesc` method. I'll update the docs as well.
