### ISSUE TITLE
Big performance issue with selectFilter() and withGlobalSearch() methods of SpladeTable

### ISSUE THREAD

**Issue by sdiama** [protonemedia/laravel-splade#112]
The `selectFilter()` and `withGlobalSearch()` methods of SpladeTable internally are using the LOWER function of DB. In MySql and PgSql when a function is used in the query, **does not use a key for the query** if the field contains a string and that has a huge impact on performance, especially on large tables.
A workaround for a user is to create a functional key, but this is supported only from PgSql and for MySql v8.0.13 or greater.

**Comment by pascalbaljet** [comment]
I'll change the behavior for `selectFilter`, but I'll look into a better default solution for the search inputs. I've copied this implementation from the [Laravel Cross Eloquent Search](https://github.com/protonemedia/laravel-cross-eloquent-search) package, but maybe it's not required here.

**Comment by pascalbaljet** [comment]
Fixed in v0.7.4.
