### ISSUE TITLE
Filepond image preview isn't working 

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#119]
Composer updated

![image](https://user-images.githubusercontent.com/8742640/202287164-8586a80a-a7ed-441b-8b5a-c1720edfd03b.png)

Define Middleware In Route

![image](https://user-images.githubusercontent.com/8742640/202287103-29dd0bb7-731a-4e6a-a336-25116cda5a79.png)

Request form validation

![image](https://user-images.githubusercontent.com/8742640/202288446-c20f81f4-d546-46e7-9dc9-d53d78a1a8ad.png)

Controller Method:-

![image](https://user-images.githubusercontent.com/8742640/202288642-f14cf71a-27ea-4079-a564-b178c72fa257.png)

View:-

![image](https://user-images.githubusercontent.com/8742640/202288746-4d29f878-0cc3-4a6d-9fe2-c63f8adea67b.png)

Output:-

![image](https://user-images.githubusercontent.com/8742640/202287465-19090e0d-47c0-4f28-8c14-63ecdc49227c.png)

**Comment by pascalbaljet** [comment]
JS package updated? 😏

**Comment by pascalbaljet** [comment]
Your screenshot looks like the default file input component. Filepond looks like this (fresh Laravel project with Splade v0.7.6):

<img width="837" alt="Schermafbeelding 2022-11-16 om 21 45 19" src="https://user-images.githubusercontent.com/8403149/202290353-80fdf0b7-fc89-4c85-a3d3-7d14e606b5f4.png">

**Comment by sahnb** [comment]
![image](https://user-images.githubusercontent.com/8742640/202290692-461746b3-446f-466e-86fc-23010d476dec.png)

yes update even cache clear;

**Comment by sahnb** [comment]
Manually update the version in package.json 
![image](https://user-images.githubusercontent.com/8742640/202295371-64ff8d38-6c51-4b73-b1a1-4214eedf325c.png)

and perfectly work. 
![image](https://user-images.githubusercontent.com/8742640/202296047-ed89f9aa-86c7-4cd5-b7eb-e1f325e5ea46.png)

thank you and love @pascalbaljet
