### ISSUE TITLE
Link component is not able to perform POST request.

### ISSUE THREAD

**Issue by bdsumon4u** [protonemedia/laravel-splade#120]
In Inertia's [Link](https://inertiajs.com/links) component, we were able to set [`method`](https://inertiajs.com/links#:~:text=%3Cbutton%3E.-,Method,-You%20can%20specify) attribute to perform `POST, PUT, PATCH, and DELETE` requests.
![Screenshot from 2022-11-18 10-04-03](https://user-images.githubusercontent.com/75123992/202614258-bb92e565-380b-46a4-a2b7-b20ee6f1c245.png)
We were also able to set [`data`](https://inertiajs.com/links#:~:text=%3C/Link%3E-,Data,-You%20can%20add) and [`headers`](Headers) attributes to set some hardcoded data & headers.

**In this way, we could implement something like nested form**
![Screenshot from 2022-11-18 10-09-34](https://user-images.githubusercontent.com/75123992/202614908-a9d2c443-99d3-4f76-be8a-1e969091f22b.png)

**I've made a copy of Link.vue & customized it.**
```vue

const props = defineProps({
    href: {
        type: String,
        required: false,
        default: "#"
    },
    method: {
        type: String,
        required: false,
        default: 'GET',
    },
    data: {
        type: Object,
        required: false,
        default: {},
    },
    headers: {
        type: Object,
        required: false,
        default: {},
    },
    replace: {
        type: Boolean,
        required: false,
        default: false,
    },
    ...
});
```

```vue
function perform() {
    if (props.away) {
        return window.location = props.href;
    }
    ...
    Splade.request(props.href, props.method, props.data, props.headers, props.replace);
}
```

**Comment by pascalbaljet** [comment]
Added in v0.7.7. I'll add it to the docs soon.

**Comment by pascalbaljet** [comment]
Docs updated: https://splade.dev/docs/x-link

**Comment by bdsumon4u** [comment]
That's great.
Can you please add a `stay` attribute also?
Just like the `Form` component.
