### ISSUE TITLE
[Question]  How to pass prefix value in table to a relation key

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#125]
I want to pass a currency symbol as a prefix to row.
Table :- Invoices
![image](https://user-images.githubusercontent.com/8742640/203216470-f06c36c8-5f72-41f0-8056-7efc4b70953e.png)
View:-
![image](https://user-images.githubusercontent.com/8742640/203216553-b4644fee-a425-4b8f-bdbd-2555f5f87ac7.png)

**Comment by pascalbaljet** [comment]
Fixed in v0.7.8:

```blade
<x-splade-cell invoiceItem.plan.charges>
    ${{ $invoice->charges }}
</x-splade-cell>
```
