### ISSUE TITLE
[Feature Request] image url pass into input on click parse to filepond preview then upload.

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#127]
@pascalbaljet is it possible or in future consideration? 
Image URL paste or pass into input then preview in filepond, like if we have a file on AWS server or at third party remote source. we want to upload it on our server. Something like this:-
https://github.com/pqina/filepond/issues/192

**Comment by pascalbaljet** [comment]
Yes, that would be great! Not sure about pasting URLs, but definitely showing existing uploads.

**Comment by sahnb** [comment]
> ### [Nov 24, 2022](#issuecomment-1325542534)

Thank you @pascalbaljet Magician

**Comment by pascalbaljet** [comment]
Added in v1.1.0:

```blade
<x-splade-form>
    <x-splade-file filepond server name="avatar" />
 
    <x-splade-input name="remote_url" label="Remote URL" />
 
    <button @click.prevent="form.$addFile('avatar', form.remote_url)">
        Add from Remote URL
    </button>
</x-splade-form>
```

It now also supports showing existing files. Docs: https://splade.dev/docs/form-file
