### ISSUE TITLE
[Question] How can we pass object of array to select option from vue 

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#128]
I am trying to match tags if exist, if not exist in the database then temporarily fill all the tags that pass from Vue to Blade select component.

![image](https://user-images.githubusercontent.com/8742640/203657579-946e0efa-acef-410e-a160-fe00d7200e38.png)

like from Vue component render less passing following tags.
![image](https://user-images.githubusercontent.com/8742640/203658083-627599e8-070c-47de-8b18-b41767d93427.png)
and already exist in the database:-

![image](https://user-images.githubusercontent.com/8742640/203658362-8d5e409f-98d0-49fa-93ab-c26fddb9b18d.png)

I try to achieved final dropdown as:-
![image](https://user-images.githubusercontent.com/8742640/203658839-2aacba5b-f179-4eba-bf3b-eba4cbc2af77.png)

**Comment by pascalbaljet** [comment]
I think you forget the `[]` brackets in the `name` attribute.

```blade
<x-splade-form :default="['tags' => [1, 2, 3]]">
    <x-splade-select name="tags[]" multiple choices :options="[1 => 'Basic', 2 => 'General', 3 => 'Advance']" />
</x-splade-form>
```

**Comment by sahnb** [comment]
actually, i am passing :options from vue . i guess options key is serialized globally ,so that not populated in splade-select.

**Comment by pascalbaljet** [comment]
Can you provide a code example of how you're passing the options from Vue? (and why?)
