### ISSUE TITLE
How to add custom blade component in datatable?

### ISSUE THREAD

**Issue by takielias** [protonemedia/laravel-splade#129]
@pascalbaljet This is a great package for spa. Thanks for your contribution. 
Table integration is easy & simple But how could I use an external blade template / raw HTML here?

_N.B: I need to show profile image in the first column of datatables._

**Comment by pascalbaljet** [comment]
Check out the 'Custom column cells' section: 
https://splade.dev/docs/table-query-builder

```blade
<x-splade-table :for="$users">
    <x-splade-cell avatar>
        <img src="{{ $item->profile_photo_url }}" />
    </x-splade-cell>
</x-splade-table>
```
