### ISSUE TITLE
Uncaught (in promise) TypeError: s.response is undefined

### ISSUE THREAD

**Issue by takielias** [protonemedia/laravel-splade#132]
Several times I got the error below. But after page reload it's usually gone.
![image](https://user-images.githubusercontent.com/38932580/204116414-35a23321-7ea6-4d51-8459-14759089cc46.png)

**Comment by pascalbaljet** [comment]
This usually indicates that the route is missing the [Splade Middleware](https://splade.dev/docs/manual-installation). I've refined the error message in v1.0.3.
