### ISSUE TITLE
In Validation HTML isn't Rendering in Error Message

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#134]
![image](https://user-images.githubusercontent.com/8742640/204165119-2e8e598d-8cc8-45dc-88e6-5c8d30aa8520.png)

Output;-
![image](https://user-images.githubusercontent.com/8742640/204165165-aa3639c2-582d-413a-b7f6-fefc25befd7a.png)

**Comment by pascalbaljet** [comment]
Fixed in v1.0.4. I've added a configuration setting to disable the escaping:

https://github.com/protonemedia/laravel-splade/blob/e5852cd04066e2fc07912a0d5827b7ccbc1ee5fe/config/splade.php#L51

It's now also in the docs: https://splade.dev/docs/form-overview
