### ISSUE TITLE
Close-button attribute for x-splade-modal 

### ISSUE THREAD

**Issue by basst85** [protonemedia/laravel-splade#14]
It would be nice if you can set an attribute for x-splade-modal to show a default close-button (X) in the right upper corner.
This button can $emit('close') on click.

**Comment by richardkeep** [comment]
Nice. I think it shouldn't be an opt-in feature but an inbuilt feature for the modal component. 99.999% modals have a close button at the top right corner.

**Comment by pascalbaljet** [comment]
I agree it should be present by default.

**Comment by basst85** [comment]
And maybe also an header-title attribute?

Example:
![image](https://user-images.githubusercontent.com/6396615/181633144-717403ad-a36e-4126-90f1-a56c3c470cbc.png)

**Comment by richardkeep** [comment]
Good idea. I think we can have a header section (for optionally setting the title) and footer section (for action button)

**Comment by pascalbaljet** [comment]
I didn't include this initially because I didn't want it to be too opinionated. But honestly, I would use this most of the time as well. I think it's perfectly doable to keep it clean by using slots. Will look into it!

**Comment by pascalbaljet** [comment]
[v0.2.1](https://github.com/protonemedia/laravel-splade/releases/tag/0.2.1) now includes the close button.

**Comment by richardkeep** [comment]
I guess this issue should be closed now.
