### ISSUE TITLE
Keep modal with SpladeTable opened when filtering/ordering

### ISSUE THREAD

**Issue by J87NL** [protonemedia/laravel-splade#141]
Hi Pascal,

I found out that when you have a SpladeTable at a modal, this modal will be closed when you apply a filter on the table of change a sort direction. Is there anything I can do to prevent this and keep the modal open?

Kind regards,
Johan

**Comment by pascalbaljet** [comment]
It needs to be updated in the Splade core. It resets the modal count when a new page comes in:

https://github.com/protonemedia/laravel-splade/blob/2ec80eae1e71c12e912664729b43839e5ed5b001/lib/Splade.js#L191-L192

So in the Table component, when a new page is requested, we need to check whether the table lives in a modal:

https://github.com/protonemedia/laravel-splade/blob/2ec80eae1e71c12e912664729b43839e5ed5b001/lib/Components/Table.vue#L385-L386

I'll try to come up with a solution!

**Comment by pascalbaljet** [comment]
Fix coming in #158

**Comment by pascalbaljet** [comment]
Fixed in v1.1.1.
