### ISSUE TITLE
[QUESTION]: Extracting Vue Components to use in Breeze or Jetstream

### ISSUE THREAD

**Issue by secondmanveran** [protonemedia/laravel-splade#142]
@pascalbaljet 

Is it possible to extract the javascript in the `lib` directory and implement it as is in either Breeze or Jetstream?

I already discovered and installed the [Inertia Tables](https://github.com/protonemedia/inertiajs-tables-laravel-query-builder) package in my Jetstream app and I love it! But I'm not in a place where I can abandon Jetstream and Vue and start over using Splade.

Any pointers you can provide to help me convert this over?

Your work is amazing by the way -- I'm very excited for the Jetstream starter to be finished so I can build my new apps with Splade.

**Comment by pascalbaljet** [comment]
You can install the library with `npm install @protonemedia/laravel-splade`, but I'm not sure if that's what you want. What part of Splade do you want to use in your existing Vue app?
