### ISSUE TITLE
When I try to refresh the page, it blinks

### ISSUE THREAD

**Issue by fhsdmhacc** [protonemedia/laravel-splade#146]
https://user-images.githubusercontent.com/103301588/207630790-db8629d0-83f6-4722-8fd9-4545ac837e3a.mp4

After install laravel fresh project and follow the automatic installation, when I try to refresh the page, it blinks.
even if it's in Mozilla Firefox or Google Chrome
thanks

**Comment by pascalbaljet** [comment]
That's normal behavior when running a Vite dev server and happens on non-Splade projects as well. If you run `npm run build` to compile the production assets, it won't blink.

**Comment by chibuzora** [comment]
> Laravel.Mozilla.Firefox.2022-12-14.21-56-30.mp4 
> After install laravel fresh project and follow the automatic installation, when I try to refresh the page, it blinks. even if it's in Mozilla Firefox or Google Chrome thanks


Use this in your 'root.blade.php' file

`
@if(App::environment('local'))
    @vite(['resources/css/app.css', 'resources/js/app.js'])
@else
    @vite('resources/js/app.js')
@endif
`
