### ISSUE TITLE
file_exists(): open_basedir restriction in effect.

### ISSUE THREAD

**Issue by DasdWaller** [protonemedia/laravel-splade#147]
Hello every,
First time I install the Splade and had this error [file_exists(): open_basedir restriction in effect. File(C:\WinNMP\WWW\project\lang/en/Are you sure you want to continue?.php) is not within the allowed path(s): (c:/winnmp)](https://flareapp.io/share/qm1N9ODP#F82). Laravel working perfectly and this error is for the first time. Any help?

**Comment by pascalbaljet** [comment]
It seems like a permissions problem, but I need a little more info to help. What kind of development environment do you use?
