### ISSUE TITLE
Need to add some vue code, but how ?

### ISSUE THREAD

**Issue by prdpspkt** [protonemedia/laravel-splade#149]
I have just started using laravel-splade. I need to use heroicons. I just wanted to use icon like 
```
<template>
  <div>
    <BeakerIcon class="h-6 w-6 text-blue-500"/>
    <p>...</p>
  </div>
</template>

<script>
import { BeakerIcon } from '@heroicons/vue/24/solid'

export default {
  components: { BeakerIcon }
}
</script>
```
But it shows error. 
`Uncaught SyntaxError: Cannot use import statement outside a module`

**Comment by pascalbaljet** [comment]
Do you use Heroicons v1 or v2?

**Comment by soixt** [comment]
Why don't you just copy the svg code per icon? Works for me

**Comment by prdpspkt** [comment]
Latest version

**Comment by pascalbaljet** [comment]
I tried it with both the Vue Composition API and Options API, and Heroicons v2 works fine. So I doubt Heroicon is causing the error.
