### ISSUE TITLE
Is is neccessary to use Tailwind ?

### ISSUE THREAD

**Issue by macgadger** [protonemedia/laravel-splade#15]
Hi 

Thanks for the efforts for making such a amazing tool; but i am amazed and see in manual installation you have mentioned we need to setup Tailwind ? is it neccesary to use it i mean what if i want to use Bootstrap or any other framework ?

Please update

Thanks.

**Comment by basst85** [comment]
Tailwind classes are used in the Blade-templates, so I think it's neccessary to install Tailwind 🙂

**Comment by pascalbaljet** [comment]
It's not necessary, but I built the Blade templates with Tailwind. You can [publish the files](https://splade.dev/docs/customization) and swap the Tailwind classes with Bootstrap styling. Note that only a handful of components have CSS classes. Most of them (data, defer, event, form, toggle, etc.) are unstyled.
