### ISSUE TITLE
Toasts firing multiple times on Octane

### ISSUE THREAD

**Issue by JapSeyz** [protonemedia/laravel-splade#151]
Hey,

It seems there's some kind of disconnect with [Laravel Octane](https://laravel.com/docs/9.x/octane).

Hitting a route with the following code:

```php
\Log::info('House ProfileImagesRequest');
Toast::title(__('Images updated successfully.'));

return redirect()->back();
```

Upon being redirected back, 2 identical toasts show up, and upon a page-reload 6 identical toasts show up.

It seems they are continuously being read from [SpladeCore::$toasts](https://github.com/protonemedia/laravel-splade/blob/main/src/SpladeCore.php#L39) and added to the session, but SpladeCore::$toasts is not being reset, so more and more toasts are just being added.

Adding a [terminable middleware](https://laravel.com/docs/9.x/middleware#terminable-middleware) seems to fix the issue (and any memory leaks)

```php
public function terminate($request, $response)
{
    $this->splade->reset();
}
```

I'll create a PR for this

**Comment by pascalbaljet** [comment]
Thanks for helping out! It's merged in v1.1.3. Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).
