### ISSUE TITLE
Tiny MCE (or any WYSIWYG editor intergration into x-splade-textarea

### ISSUE THREAD

**Issue by uqjohart** [protonemedia/laravel-splade#161]
Just wondering if there is any clear doco on how or if we can integrate a WYSIWYG editor into the x-splade-textarea.
I've tried adding it in as I do for both  a normal Laravel and a livewire build, but I think the Vue rendering is killing it. 

Any suggestions or plans to intergrate it going forward? Would be a massive boost to the platform. Something like a little flag
<x-splade-textarea name="notes" label="Notes" autosize editor/>

Love the framework, it's making my life easier!
(not sure if this should be an issue, if not feel free to delete)

**Comment by pascalbaljet** [comment]
I think it's a good idea, but I'm not sure which library to support yet. There's an open issue (#38) for TipTap. Let's continue the discussion over there :)
