### ISSUE TITLE
[Feature Request] Preserve Scroll

### ISSUE THREAD

**Issue by MotionPhix** [protonemedia/laravel-splade#165]
I think so far Splade is offering more features and becoming more usable by day. While working with lots of forms in applications, I wanted to ask for a feature for preserving the scroll position of the page. right now, if i am on a form that is slightly at the bottom (or anywhere other than the top of the page, the behaviour is that after clicking update, save, delete or any of the actions available to a form, the page scrolls back to the top instead of just remaining where I am looking at. It's a feature that is also available in inertiajs. Can we have that feature in Splade?

**Comment by pascalbaljet** [comment]
Yes, that would be nice! Also: https://twitter.com/tompiraino/status/1605405453193732096

**Comment by pascalbaljet** [comment]
```blade
<x-splade-form preserve-scroll>
```

```blade
