### ISSUE TITLE
[Broken Functionality??] Vue & Splade Malfunction

### ISSUE THREAD

**Issue by MotionPhix** [protonemedia/laravel-splade#166]
Hello,

So I created a Vue component that looks like below:
![should_show](https://user-images.githubusercontent.com/59722054/209401581-3d84f5a5-d4dc-4707-9ae3-3d2bfb513a6e.png)

It's a simple component that I am using in the main app layout to show elements based on how far someone has scrolled down.
![layout](https://user-images.githubusercontent.com/59722054/209401743-46c2e1f4-a6a9-4162-b22a-b8b4817ff9b3.png)

The problem I am facing now is that the **v-if** directive is not working at all. Take a look at the following video:
https://user-images.githubusercontent.com/59722054/209401874-1774632a-fc65-4002-8674-da2a5c8c9c2d.mp4

I don't know if it's vue or splade or the way I am laying the code out but how do I make this to function as intended?

**Comment by pascalbaljet** [comment]
`y` value is a `Ref`, so you should pass the value to the slot:

```js
return this.$slots.default({
    y: y.value
});
````
