### ISSUE TITLE
@if condition around <x-splade-form> raises a Blade syntax error

### ISSUE THREAD

**Issue by juienpro** [protonemedia/laravel-splade#167]
Setting a Blade condition around <x-splade-form> produces the following error:

**syntax error, unexpected end of file, expecting "elseif" or "else" or "endif"**

To reproduce: 

```
@if(true)
   <x-splade-form type="POST" action="/toto">
@else
  <x-splade-form type="POST" action="/toto">
@endif
</x-splade-form>
```

A condition around `<x-splade-input>` works.

**Comment by guiofranca** [comment]
I think that's a Blade behavior. Similar thing happen if you try to do:
```
@if(true)
@foreach([1,2,3] as $value)
@else
@foreach([4,5,6] as $value)
@endif
<p>{{$value}}</p>
@endforeach
```
wich yields an error. Instead you do:
```
@if(true)
@foreach([1,2,3] as $value)
<p>{{$value}}</p>
@endforeach
@else
@foreach([4,5,6] as $value)
<p>{{$value}}</p>
@endforeach
@endif
```
Better off if you bring whatever variable you want from the controller instead of IF-ELSEing on Blade. If that's really necessary, do the following:
```
@if(true)
   <x-splade-form type="POST" action="/toto">
   </x-splade-form>
@else
  <x-splade-form type="POST" action="/toto">
   </x-splade-form>
@endif
```

**Comment by juienpro** [comment]
Yes, I just saw your post and I came to the same conclusion. 

I tested another Blade component, and it's the same. Conditioning an opening tag of a Blade component is nonsense I guess.

Thank you for the proposed alternatives however.

This issue can be closed, sorry for the post.
