### ISSUE TITLE
[FEATURE REQUEST] Include a real and solid UI framework

### ISSUE THREAD

**Issue by juienpro** [protonemedia/laravel-splade#173]
I will never understand why boilerplates or frameworks like Jetstream or Laravel Splade do not include a viable UI framework. They have "some" components. Input fields are designed, but not links... People cannot understand this.

UI components are where we lose all of our time. 

I am at the point where for Jetstream and for Splade, my first reflex is to do a `npm install primevue@^3 --save`, otherwise I will scratch my head over simple things.

Nowadays, a good boilerplate/framework can only be delivered with UI components. Quasar Framework bet on it, and it's delightful: I know that almost everything is included when I develop.

**Comment by pascalbaljet** [comment]
Splade is not a UI framework. It was even originally meant to be totally renderless and without any markup. However, some components, like a Modal or Table, benefit from having a default UI as it requires a lot of time to implement. Implementing a button or some styling to a Link is easy. By [publishing the Blade templates](https://splade.dev/docs/customization), everything is still customizable, and you could even replace Tailwind with another or no CSS framework.

I'm constantly considering whether a component should be renderless or not. In the future, I might split Splade into a `splade-core` that handles the navigation/routing stuff, a `splade-base-components` that contains the renderless stuff, and then dedicated packages like `splade-form-components`, `splade-table`, etc. But for now, it's much easier to bundle everything together. Less setup for everyone and easier to maintain.
