### ISSUE TITLE
Page expired when logging out after session is expired

### ISSUE THREAD

**Issue by LordMcAwesome** [protonemedia/laravel-splade#174]
Using:
- Laravel 9.19
- Splade 1.1
- Laravel Breeze for auth setup

Steps to reproduce:
- Login / Generate a session for the user
- Wait for the session to expire or delete the session file under storage/framework/sessions
- Try to execute any POST request, such as the logout

Effect:
You will get a 419 Page expired.

Possible solution:
With Inertia and Vue I had adapted the app/Exceptions/Handler.php's render method as follows:
```
public function register()
{
    $this->renderable(function (Exception $e) {
        // Redirects to login when session is invalid
        if (
            $e->getPrevious() instanceof TokenMismatchException ||
            $e instanceof AuthenticationException
        ) {
            return redirect()
                ->to(route("login"));
        }
    });
}
```

As Splade intercepts this register method, it would be possible to add that code snippet into the SpladeCore.php's exceptionHandler method as follows:
```
public static function exceptionHandler(Handler $exceptionHandler): Closure
    {
        return Closure::bind(function (Throwable $e, $request) {
            if ($request->header(SpladeCore::HEADER_SPLADE) && !$e instanceof ValidationException) {
                /** @var Handler $this */
                return $this->prepareResponse($request, $e);
            }
            if (
                $e->getPrevious() instanceof TokenMismatchException ||
                $e instanceof AuthenticationException
            ) {
                return redirect()
                    ->to(route("login"));
            }
        }, $exceptionHandler, get_class($exceptionHandler));
    }
```

Are there other ways to accomplish redirecting to the login page if the session has expired?

**Comment by hipoagencia** [comment]
I'm facing the same issue. Looking for an solution!

**Comment by pascalbaljet** [comment]
Thanks for reporting, I'll look into it!

**Comment by pascalbaljet** [comment]
By the way, this also occurs on regular Laravel apps, right? I think this is the default behavior as there's a package to prevent it: https://github.com/GeneaLabs/laravel-caffeine

I never used it, so I have no idea if this fixes it with Splade.

**Comment by LordMcAwesome** [comment]
Yes, this also occurs on regular Laravel apps, and I guess it is fine to handle the solution as per every app you build. Some app want to redirect to the login page, other maybe perform a different action.

As I would (with other Laravel apps) adapt the app/Exceptions/Handler.php as shown above, I was just wondering, what the appropriate place was when using Splade.

**Comment by pascalbaljet** [comment]
Ahh, I see! Maybe I could add an additional argument so you can add a custom handler:

```php
$this->renderable(
    SpladeCore::exceptionHandler($this, function (Throwable $e) {
        // Handle invalid session...
    })
);
```

**Comment by LordMcAwesome** [comment]
That would be great! Thank you

**Comment by ajimatahari** [comment]
```
public function render($request, Throwable $exception)
    {

        if($exception instanceof AuthenticationException){
            return Splade::redirectAway(route('login'));
        }

        return parent::render($request, $exception);
    }
```

i add snippets above to the `Exceptions\Handler.php` , it fix 419 Token Mismatch and Expired Session on my side. hope it helps.

**Comment by pascalbaljet** [comment]
Added in v1.1.3. Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).

Docs: https://splade.dev/docs/exception-handling

**Comment by LordMcAwesome** [comment]
It works like a charm @pascalbaljet, thanks so much for this! :)
