### ISSUE TITLE
relation datatable column for searchable not working

### ISSUE THREAD

**Issue by JunedSetiawan** [protonemedia/laravel-splade#178]
column datatable relation for searchable is not working because inside the column key is changed to toLower and it doesn't have dot, i can fix it, can i do PR in this repo?

**Comment by pascalbaljet** [comment]
I don't understand your problem. Please provide a code example so I can reproduce the error. Thanks!

**Comment by JunedSetiawan** [comment]
Error : Requested filters `kategoryforumname` are not allowed. Allowed filter(s) are `title, body, kategoryForum.name`

there's my code 

$forums = QueryBuilder::for($data)
            ->allowedIncludes('kategoryForum')
            ->allowedSorts('title')
            ->allowedFilters(['title', 'body', 'kategoryForum.name', $globalSearch])
            ->paginate()
            ->withQueryString();

        return view('panel.index', [
            'forums' => SpladeTable::for($forums)
                ->withGlobalSearch()
                ->column('title', searchable: true, sortable: true)
                ->column("kategoryForum.name", 'kategoryForum', searchable: true)
                ->column('action')
                ->selectFilter('kategoryForum.name', $kategory),
        ]);

the problem is in ->column(key:...)

**Comment by uqjohart** [comment]
Super simplified example to replicate: 

**Model Experiment:**
- Use PowerJoins
- Protected fields: 'company'
- hasMany(Result::class)

 **Model Results:**
- use PowerJoins
- Protected fields: 'testimonial', 'experiment_id'
- belongsTo(Experiment::class, 'experiment_id')

**Results Controller Function:**
`
$results = QueryBuilder::for(Result::class)
    ->allowedFilters([
        'testimonial',
        // This throws errors
        'experiments.company',
        GlobalSearchController::globalSearch([
            'testimonial',
            //This works
            'experiments.company',
        ])
    ])
    ->joinRelationship('experiments')
    ->paginate(50)
    ->withQueryString();
return view('results.index', [
    'results' =>  Splade::onLazy(
        fn () => SpladeTable::for($results)
            ->withGlobalSearch()
            ->defaultSort('experiments.company', 'desc')
            ->column(
                'experiments.company',
                label: 'Company',
                sortable: true,
                searchable: true,
                hidden: false,
                canBeHidden: false,
            )
            ->column('testimonial', sortable: true, searchable: true, hidden: true)
            ->perPageOptions([50, 100, 200, 10000])
    ),
]);

`
**Error thrown:**
Error produced when using the individual filter field (not global search)
`Spatie \ QueryBuilder \ Exceptions \ InvalidFilterQuery
PHP 8.1.6
9.43.0
Requested filter(s) `experimentscompany` are not allowed. Allowed filter(s) are `testimonial, experiments.company, global`.`
Note the missing period. Hope this helps?

**Comment by pascalbaljet** [comment]
Thanks for sharing, I'll look into it!

**Comment by JunedSetiawan** [comment]
Thanks
