### ISSUE TITLE
Vite not bundling assets on Splade project.

### ISSUE THREAD

**Issue by kylemabaso** [protonemedia/laravel-splade#181]
I built an app using Laravel and Splade. When I create views, the CSS is there but certain elements like images and charts disappear. When I comment out this line:

`@vite(['resources/js/app.js'])`

Everything looks fine but Splade is no longer active. This suggests that there's something wrong with my Vite configuration but I can't figure it out. I have tried this with multiple templates and different assets so the issue isn't the template.

The error I get from the console is runtime-core.esm-bundler.js:40 [Vue warn]: Template compilation error: Tags with side effect (<script> and <style>) are ignored in client component templates.

https://github.com/kylemabaso/splade

<img width="1440" alt="Screenshot 2023-01-03 at 03 33 48" src="https://user-images.githubusercontent.com/4367951/210290141-9b8ac249-18a8-4e90-9a2a-5f4f47988963.png">

**Comment by pascalbaljet** [comment]
As of v1.2.0, there's a new Script Component: https://splade.dev/docs/x-script

Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).
