### ISSUE TITLE
How to submit form with GET

### ISSUE THREAD

**Issue by quillenstrange** [protonemedia/laravel-splade#188]
I'm trying to create a tag search for posts, but when I submit the form, the page refreshes but doesn't pass any GET parameters to the controller or the URL. 

<x-splade-form method="GET">
	<x-splade-select name="type[]" choices multiple>
		<option value="image">Image</option>
		<option value="video">Video</option>
                <option value="book">Book</option>
	</x-splade-select>
	<div class="flex flex-col items-center">
		<x-splade-submit label="Search" :spinner="true" />
	</div>
</x-splade-form>

**Comment by HUGE-D1CK-10-INCHES** [comment]
Can you post that section of the code?

**Comment by fikri-kompanion** [comment]
yup. having same problem

**Comment by pascalbaljet** [comment]
Please provide a code example. Did you set the `method` attribute?

```blade
<x-splade-form method="get">
    ...
</x-splade-form>
```

**Comment by quillenstrange** [comment]
Here's the code...I'm trying to use it with a select, but a text input didn't work either:

`<x-splade-form method="get">`
`	<x-splade-select name="type[]" choices multiple>`
`		<option value="image">Image</option>`
`		<option value="video">Video</option>`
`		<option value="book">Book</option>`
`	</x-splade-select>`
`	<div class="flex flex-col items-center">`
`		<x-splade-submit label="Search" :spinner="true" />`
`	</div>`
`</x-splade-form>`

**Comment by HUGE-D1CK-10-INCHES** [comment]
Not sure if this is required but where is your action on form?

**Comment by quillenstrange** [comment]
I have tried with action, but still didn't work. It should default to the current page if you don't specify action anyway.

**Comment by fikri-kompanion** [comment]
I have to create a global mixin for this problem.

```js
export default {
    methods: {
        formSearch($event) {
            const formData = new FormData($event.target)
            let data = [...formData.entries()]
            const queryString = data
                .map(x => `${encodeURIComponent(x[0])}=${encodeURIComponent(x[1])}`)
                .join('&')

            this.$splade.visit(`${$event.target.action}?${queryString}`)
        }
    }
}
```
Then using it like this

```blade
<x-splade-form role="form" @submit.prevent="$root.formSearch($event)" method="get" action="{{ route('customers:index') }}" :default="[
    'query' => request()->get('query'),
    'externalId' => request()->get('externalId'),
]">
    <div v-blur="form.processing">
        <x-splade-input name="query" label="Search term (can use regex)" placeholder="Search something..."></x-splade-input>

        <x-splade-input name="externalId" label="External ID" placeholder="Search for exact external id"></x-splade-input>

        <div class="flex flex-row gap-5">
            <Link class="btn btn-secondary flex-0 mt-4" href="{{ route('customers:index') }}" :class="{ 'btn-disabled': form.processing }">Clear</Link>
            <x-splade-submit class="btn btn-primary mt-4 flex-1" label="Search" :spinner="true" />
        </div>
    </div>
</x-splade-form>
```

It does work, however, when i submit the form, it does a request **TWO** times. 1st request is running the `formSearch()` and 2nd request is like it is loading back the page.

![image](https://user-images.githubusercontent.com/101977604/211174686-4a0c2551-6756-4eeb-b765-2db157cdeb51.png)

**Comment by fikri-kompanion** [comment]
For the double requests, i've tested this:

1. Create a button and call `this.$splade.visit()` in js with query string- No double requests
2. Refresh the page with query string - No double requests
3. Submit form and using custom submit using `@submit.prevent=` - It will make double requests

**Comment by pascalbaljet** [comment]
I’ll work on a fix in the Form component. Axios doesn’t handle it by default.

**Comment by pascalbaljet** [comment]
Fixed in v1.1.3. Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).

**Comment by fikri-kompanion** [comment]
thank you. it is now working as expected

**Comment by quillenstrange** [comment]
Thanks!
