### ISSUE TITLE
SpladeTable name(), causing perPageOptions() not working

### ISSUE THREAD

**Issue by ajimatahari** [protonemedia/laravel-splade#189]
I was playing along with this awesome package, i might say. then i found some bug (i think). I generate a Splade Table class, with all the basic function 

this is the configure function that i make :
```
/**
     * Configure the given SpladeTable.
     *
     * @param \ProtoneMedia\Splade\SpladeTable $table
     * @return void
     */
    public function configure(SpladeTable $table)
    {
        $table
        ->name('user') // this function causing perPageOptions doesn't work as expected
        ->withGlobalSearch('Search through the data...', columns: ['email'])
        ->perPageOptions([5, 10, 25])
        ->paginate(10)
        ->column(key: 'name', searchable: true, sortable: true, canBeHidden: false)
        ->column(key: 'email', searchable: true, sortable: true, canBeHidden: false)
        ->column(label: 'Actions')
        ->searchInput(
            key: 'name',
            label: 'Find by name',
        )
        ->bulkAction(
            label: 'Touch timestamp',
            each: fn (User $user) => $user->touch(),
            before: fn () => info('Touching the selected projects'),
            after: fn () => Toast::info('Timestamps updated!')
        )
        ->export();

    }
```

when i chain the `name()` function with the $table variable, the `perPageOption()` doesn't work. it just keep at the 10 per page no matter what options i select (5/10/25) it will shows in 10 row that i set in `paginate(10)` function. but when i remove the `name()` function. it works again as expected. 

PS : i keep the package as minimum as it can, i'm just trying to use the package (which i'm pretty impressed, and i might use it for my next project). so every code i used in this env,  i take it from the documentation, i just trying the options. Thank you for your awesome package

**Comment by pascalbaljet** [comment]
The `name()` method is not documented because it's meant for a feature that didn't make the v1.0 release. Therefore, I'd suggest not using it as it has no effect.

**Comment by ajimatahari** [comment]
> The `name()` method is not documented because it's meant for a feature that didn't make the v1.0 release. Therefore, I'd suggest not using it as it has no effect.

ohh I see, sorry for the inconveniences, just trying things on the source code
