### ISSUE TITLE
There are no focusable elements inside the <FocusTrap />

### ISSUE THREAD

**Issue by HUGE-DECK-10-INCHES** [protonemedia/laravel-splade#190]
@pascalbaljet  This happens when I try to stack two modals:

```
<x-splade-modal :name="modal-1">
<--- some form --->
  <x-splade-modal :name="confirm-modal">
    // Password confirmation form
  </x-splade-modal>
</x-splade-modal>
```
I can't figure out how to focus to input existing inside form in inner modal...
https://github.com/tailwindlabs/headlessui/issues/493
https://github.com/tailwindlabs/headlessui/issues/265

**Comment by soixt** [comment]
@pascalbaljet anything  on this, having the same issue?

**Comment by HUGE-DECK-10-INCHES** [comment]
Seems like this works from latest updates. So I am closing it
