### ISSUE TITLE
Production build resulted with an empty page

### ISSUE THREAD

**Issue by placiu** [protonemedia/laravel-splade#191]
I was developing in local env with `npm run dev`

Then I deployed the app to the server and build frontend with `npm run build` 
When I enter my app, the content showed up for a second, and in the next second it went to blank screen

Console log:

<img width="620" alt="screen1" src="https://user-images.githubusercontent.com/29714618/211200773-8d90ed58-3218-431f-a638-4ee1130c0350.png">

Any guess why?

**Comment by HUGE-D1CK-10-INCHES** [comment]
Did you even check what is the error at console logged line? Like this no one can know, and I do npm run build locally as well and it works

**Comment by placiu** [comment]
It's hard to read anything from a file with over 100k cols. Anyway, this SyntaxError refers to my mistake in blade template file. I was merging two class attributes under one tag. Dev server didn't throw an error. Production one did. It blows though that it can't render an actual error, like for example Livewire do. But still, at this point great package.

**Comment by pascalbaljet** [comment]
For feature readers:

In development, Vue lets you know in the console, but in production, it throws an error and stops rendering.

As of v1.4.13, I've added an option to suppress the error. In your main `app.js` file, you can use the `suppress_compile_errors` option:

```js
createApp({
    render: renderSpladeApp({ el })
})
    .use(SpladePlugin, {
        "suppress_compile_errors": true
    })
    .mount(el);
```

Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).
