### ISSUE TITLE
select input is not passing default value

### ISSUE THREAD

**Issue by quillenstrange** [protonemedia/laravel-splade#197]
I use the "selected" attribute on an option to make it the default option. If you don't make any changes and leave it as default, the form passes the value as blank.

```
    <x-splade-form method="get">
        <x-splade-select name="country_code" choices>
            <option value="be">Belgium</option>
            <option value="nl" selected>The Netherlands</option>
        </x-splade-select>
        <div class="flex flex-col items-center">
            <x-splade-submit label="Submit" :spinner="true" />
        </div>
    </x-splade-form>
```
In this code, when you press submit, it should pass the value of "nl" since that is the default selected option, but it passes nothing. You have to click another option then click back to the default for it to pass.

**Comment by HUGE-D1CK-10-INCHES** [comment]
For some reason with coices is not working, if you remove choices it will work. If you want choices, you will need to pass :options="" to work. For sum reason with slots doesn't work.

**Comment by quillenstrange** [comment]
If I take off "choices" it doesn't default to the "selected" option at all. 

I tried passing values through "options" like this and the selected doesn't work:

```
    <x-splade-form method="get">
        <x-splade-select name="country_code" choices :options="
            [
                ['value' => 'Option 1', 'label' => 'Option 1', 'selected' => true],
                ['value' => 'Option 2','label' => 'Option 2'],
            ]
        "/>
        <div class="flex flex-col items-center">
            <x-splade-submit label="Search" :spinner="true" />
        </div>
    </x-splade-form>
```

**Comment by pascalbaljet** [comment]
You need to pass default values to the `x-splade-form` element:

```blade
<x-splade-form :default="['country_code' => 'nl']" method="get">
    <x-splade-select name="country_code" choices>
        <option value="be">Belgium</option>
        <option value="nl">The Netherlands</option>
    </x-splade-select>
</x-splade-form>
```

Check out the [default data](https://splade.dev/docs/x-form) section of the form documentation.
