### ISSUE TITLE
Passing v-model value to splade defer component

### ISSUE THREAD

**Issue by hipoagencia** [protonemedia/laravel-splade#204]
Hi there!

I'm trying to use defer component to get some data trough api.
But, i need to get the value of a input field. If i try using Vue {{ value }} it throws an error.

Somebody have a solution for this?

For example:

```
 <x-splade-defer url="https://viacep.com.br/ws/{{zipcode}}/json/">
<x-splade-input id="zipcode" name="zipcode" v-model="zipcode" label="CEP" class="col-span-1"/>
</x-splade-defer>
```

**Comment by hipoagencia** [comment]
By the way, it will be great if we create a Facebook community to discuss simple stuffs like that and help each other!

**Comment by pascalbaljet** [comment]
As of v1.2.4, the `url` attribute support *Template literals*:

```blade
<x-splade-form>
    <input v-model="form.zipcode" />

    <x-splade-defer
        url="`/defer/input/${form.zipcode}`"
        watch-value="form.zipcode"
        watch-debounce="100"
        manual
    >
        <p v-if="response" v-text="response" />
    </x-splade-defer>
</x-splade-form>
```

The `watch-debounce` value defaults to `0`, but I recommend setting it higher as people will type into the input field :)

Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).

**Comment by hipoagencia** [comment]
Making my question more clear.
- If i use defer, the response will be like this: response.field.
- Using v-model, i cant use response.field and form.field to send to Laravel.
