### ISSUE TITLE
Doesn't work for my existing platform, Please help

### ISSUE THREAD

**Issue by coding-sunshine** [protonemedia/laravel-splade#21]
Hi @pascalbaljet 
I am trying to install on the app which is already using alpine and I want to add Splade to it. but doesn't work and the blank page loads :(

**Comment by pascalbaljet** [comment]
Are there any console errors you can share? And is it only Alpine.js you’re using, or Livewire as well?

**Comment by sidiqaldi** [comment]
in my case, blank page because i'm using automatic installation on windows OS. 
check `App\Http\Kernel` & `App\Exceptions\Handler` make sure it's installed correctly

**Comment by coding-sunshine** [comment]
@pascalbaljet yes I am using livewire. And as a matter of fact when I run 
```
npm run dev
```
things kind of work fine but the issue is when I run build.

Please find attached screenshot. Its kinda unreadable 

but if you need I can provide you access to the repo. 
Its pretty much Boilerplate repo with Laravel Jetstream/Livewire, Alpine, and a few spatie packages

<img width="630" alt="Screen Shot 2022-07-30 at 1 02 10 AM" src="https://user-images.githubusercontent.com/3206025/181788525-0b88d4d6-3fc1-44ae-b6be-dc82994acd45.png">

<img width="1229" alt="Screen Shot 2022-07-30 at 1 05 53 AM" src="https://user-images.githubusercontent.com/3206025/181788921-d301a0f2-c621-41a1-b98c-db1fd0577d7d.png">

**Comment by coding-sunshine** [comment]
@sidiqaldi I am on mac and everything is good on ```App\Http\Kernel``` & ```App\Exceptions\Handler```

**Comment by pascalbaljet** [comment]
@coding-sunshine It would be if you could share the repo! Thanks in advance :)

**Comment by coding-sunshine** [comment]
@pascalbaljet I have added you to the repo, you can checkout code in ```splade``` branch
https://github.com/coding-sunshine/laravel-saas-boilerplate/

**Comment by coding-sunshine** [comment]
@pascalbaljet I even tried manual installation with a simple laravel breeze application but still facing issues. Am I missing anything here ? :(

**Comment by imariusalin** [comment]
Hi, I have a similar error. any fix?

app.68daceb1.js:29 Uncaught SyntaxError: 24 (at app.68daceb1.js:29:101608)
    at tt (app.68daceb1.js:29:101608)
    at He (app.68daceb1.js:30:6571)
    at aL (app.68daceb1.js:30:1836)
    at Fp (app.68daceb1.js:29:108706)
    at aL (app.68daceb1.js:30:1589)
    at Fp (app.68daceb1.js:29:108706)
    at sL (app.68daceb1.js:29:107949)
    at pN (app.68daceb1.js:35:21062)
    at FN (app.68daceb1.js:35:25309)
    at LN (app.68daceb1.js:35:25818)
