### ISSUE TITLE
[Question] how access data on custom dataTable

### ISSUE THREAD

**Issue by dfikeda** [protonemedia/laravel-splade#213]
### Description:

I'm trying to implement the table with the built-in features of splade using the Custom head and body according to the documentation:

```
<x-splade-table :for="$users">
    <x-slot name="head">
        <thead>
            ...
        </thead>
    </x-slot>

    <x-slot name="body">
        <tbody>
            ...
        </tbody>
    </x-slot>
</x-splade-table>
```

But, inside the slots, how do I access the data, like for example $user->name?

I believe I can even increase this part of the documentation =D
Thanks Pascal

**Comment by guiofranca** [comment]
`$users->columns()->first()->label` for instance. I don't think you got row properties access (like first row user->email), since you'll be getting them server-side after table creation.

For body customization, I would rather publish the blade components from the package and customize it there globally. If you don't need that level of customization, use [Custom Columns Cells](https://splade.dev/docs/table-query-builder) instead.

**Comment by dfikeda** [comment]
> `$users->columns()->first()->label` for instance. I don't think you got row properties access (like first row user->email), since you'll be getting them server-side after table creation.
> 
> For body customization, I would rather publish the blade components from the package and customize it there globally. If you don't need that level of customization, use [Custom Columns Cells](https://splade.dev/docs/table-query-builder) instead.

Vou escrever em br que pra mim fica mais fácil...
Então eu quero na realidade em uma tabela ter duas linhas (uma vai togglear a outra). Não cheguei a testar a sua solução de publicar, e tem que ver também se conseguirei limitar a apenas 1 tabela que necessita desse trato fino... 

I'll write it in br because it's easier for me...
So I actually want a table to have two rows (one will toggle the other). I didn't get to test your publishing solution, and I also have to see if I can limit it to just 1 table that needs this fine treatment...

**Comment by guiofranca** [comment]
> Vou escrever em br que pra mim fica mais fácil... Então eu quero na realidade em uma tabela ter duas linhas (uma vai togglear a outra). Não cheguei a testar a sua solução de publicar, e tem que ver também se conseguirei limitar a apenas 1 tabela que necessita desse trato fino...

Se são só duas linhas, precisa ser uma tabela? Pode ser mais simples um componente específico.

Investiguei como fazer em tabela mesmo assim e cheguei nisso, veja se atende:

```
<x-splade-table :for="$users" >
    <x-slot name="head">
        <thead>
            <tr>
                @foreach($users->columns() as $column)
                    <th>{{$column->label}}</th>
                @endforeach
            </tr>
        </thead>
    </x-slot>
    <x-slot name="body">
        <tbody>
            @foreach($users->resource as $user)
                <tr>
                    @foreach($users->columns() as $column)
                        <td>{{$user[$column->key]}}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </x-slot>
</x-splade-table>
```

**Comment by pascalbaljet** [comment]
I've extended the docs: https://splade.dev/docs/table-overview
