### ISSUE TITLE
[Feature Request] Hydrate form model after submit

### ISSUE THREAD

**Issue by teuunn** [protonemedia/laravel-splade#220]
- Laravel Version: 9.46.0
- PHP Version: 8.1.12
- Splade JS Version (npm): 1.1.5
- Splade PHP Version (composer): 1.1.5

### Description:

In the demo's the controller method returns to the index page for specified resource. It would be very nice to re-hydrate form model data after submitting the form. That way you're able to "inline edit" the form. If I add **stay** to the form the old model data is presented. If I redirect to the  full resource again it feels like overkill. Maybe I'm missing the correct way of doing the return in the controller, but for me it felt 'something is missing'.

Just an idea, we currently have those two:
```
<x-splade-form stay reset-on-success> 
<x-splade-form stay restore-on-success>
```

Maybe we can add something like:
```
<x-splade-form stay rehydrate-on-success>
```

### Steps To Reproduce Issue:

1. Create a simple edit form as mentioned in the docs/video with **stay** and **default**
2. Update the model in the controller as mentioned in the docs/video
3. Model default shows old values instead of the new updated ones

If it's something to go on and if I can help, please let me know where to start.

**Comment by pascalbaljet** [comment]
Thanks for sharing! I actually think it's a bug. The `restore-on-success` currently defaults to `true`:

https://github.com/protonemedia/laravel-splade/blob/3ab09c74d768b593bcd1beaad7384fd1fb395c42/lib/Components/Form.vue#L79-L83

I'll look into it :)

**Comment by teuunn** [comment]
Added in #238
