### ISSUE TITLE
Existing file: error during load

### ISSUE THREAD

**Issue by HUGE-D1CK-10-INCHES** [protonemedia/laravel-splade#223]
Not sure if this has been asked, but when I try to preview the uploaded image:

```
protected function image (): Attribute {
       return Attribute::make(
        //    get: fn ($value) => route('index') .'/storage' . $value,
            get: fn ($value) => ExistingFile::fromDisk('public')->get($value),
       );
}
```
When I use commented way I get the image preview but re-upload is not working when the image is not changed, it reuploads the same image again. 
When I return ExistingFile:
```
+filename: "files/1/blog-posts/55/v7f80bOhp0bXWrkHMYiRTq5IHF9jw4doqSrtZFDA.jpg"
  +metadata: array:2 [▶]
  +name: "v7f80bOhp0bXWrkHMYiRTq5IHF9jw4doqSrtZFDA.jpg"
  +previewUrl: "https://example.com/storage/files/1/blog-posts/55/v7f80bOhp0bXWrkHMYiRTq5IHF9jw4doqSrtZFDA.jpg"
  +mimeType: "image/jpeg"
  +sizeInBytes: 101388
  -identifier: "4x8flMaDlVu84v3W"
```
But for some reason I get "error during load" with "filename" path, like it is not even using "previewUrl" path.. Am I missing something?

**Comment by hipoagencia** [comment]
how did you solved it? I cant make the file preview work on edit.

I'm trying this code:

`
    public function getImageAttribute($value)
    {
        return \Vite::asset($value);
    }
`

![image](https://user-images.githubusercontent.com/79876130/218532941-93658e6c-bcfb-401f-a934-3be248203111.png)

**Comment by HUGE-D1CK-10-INCHES** [comment]
Not sure, what does the error says in console for you?
