### ISSUE TITLE
Existing file: error during load

### ISSUE THREAD

**Issue by HUGE-DECK-10-INCHES** [protonemedia/laravel-splade#225]
Filepond preview returns cors problem with sub.sub.domain.com. 

Not sure how to fix it with laravel because allowing all cors does not work. 

Anyway. I could fix it if file component could use a custom url as prefix to previewUrl..

Is there a way to do it because it passes my sub.domain.com insteaad of sub.sub.domain.com

**Comment by HUGE-D1CK-10-INCHES** [comment]
Currently, I found a workaround since I can't get cors to work at all:
```
if (tenant()) {
    Config::set('filesystems.disks.public.url', route('tenant.index') . '/storage');
}
```
So it uses sub-domain as main URL

**Comment by pascalbaljet** [comment]
@HUGE-D1CK-10-INCHES Can we close this issue? This seems not Splade-specific.

**Comment by HUGE-D1CK-10-INCHES** [comment]
@pascalbaljet  Would be nice if it could be passed as custom config value instead of using it straight from the config, but yeah you can close it
