### ISSUE TITLE
[Question] How to pass data to Modal?

### ISSUE THREAD

**Issue by errand** [protonemedia/laravel-splade#227]
- Laravel Version: 9
- PHP Version: 8.1
- Composer (PHP) package version: 1.1.5
- NPM (JS) package version: 1.1.2

### Description:

It's common situation when user clicks on Delete button and confirmation Modal pops up. But i'm stuck passing id to Modal

```
<x-splade-state>

      <x-splade-table :for="$tags" class="w-2/3">
          <x-splade-cell actions>
              <Link href="#confirm-delete" @click="state.shared.tag = {{ $item->id }}"> {{__('Delete')}} </Link>
          </x-splade-cell>
      </x-splade-table>

    <x-splade-modal :close-button="false" name="confirm-delete">
        <h1>{{ __('Are you sure') }}?</h1>
        <button type="button" @click="modal.close">{{ __('Cancel') }}</button>
        <Link :href=`/dashboard/tag/${state.shared.tag}/delete`> {{__('Delete')}} </Link>
    </x-splade-modal>

</x-splade-state>
```

Tried both Data and State. And in both cases there is no data in modal

**Comment by ajimatahari** [comment]
The data can be passed like any other route, this is what i did 
`<x-splade-link
                                class="items-center block px-4 py-2 text-left text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out" 
                                href="{{route('user.delete',$item->id)}}"
                                confirm="Enter the danger zone..."
                                confirm-text="Are you sure?"
                                confirm-button="Yes, take me there!"
                                cancel-button="No, keep me save!"
                                method="POST"
                                :data="['_method'=>'DELETE']"
                                >Delete</x-splade-link>`

**Comment by errand** [comment]
Awesome. Thank you @ajimatahari 
I guess i should be more attentive to the [documentation](https://splade.dev/docs/x-link).
