### ISSUE TITLE
[Question] PWA and offline first support

### ISSUE THREAD

**Issue by vladninja** [protonemedia/laravel-splade#228]
### Description:
Is there any documentation or possibility to create an offline and PWA applications?

**Comment by bdsumon4u** [comment]
Sadly, there is no documentation.
I was trying to mak a PWA a few days ago, but unfortunately I've failed to add offline capabilities.

I've the same question.
Is it possible to make a PWA with offline capabilities?

**Comment by bdsumon4u** [comment]
Splade's **Link** component uses **Axios**, that's why **fetch** event doesn't work.

![Screenshot from 2023-01-23 18-27-02](https://user-images.githubusercontent.com/75123992/214039433-193cad23-a63f-4d59-abab-170affd6971d.png)

**Comment by pascalbaljet** [comment]
I'm not familiar with progressive web apps, but what is the use-case? Displaying a 'no internet/network' warning?
