### ISSUE TITLE
[Question] make custom component but keep include some of splade features

### ISSUE THREAD

**Issue by zulfikar-ditya** [protonemedia/laravel-splade#232]
- Laravel Version: 9.47
- PHP Version: 8.0.12
- Splade JS Version (npm): 1.1.5
- Splade PHP Version (composer): 1.1.5
 
### Description:
I want make some component but it keep include some of splade feature.

example i want make a input component with custom styling, 
- Str::headline for label and include some asterisk in label (red is required, blue is nullable)
- auto placeholder if the placeholder is null (get from label)
- floating label styling
- and more

but i want to keep some of splade features. 

i [readed](https://splade.dev/docs/custom-vue-components) it's not contains how to customize existing splade component.

Thanks

**Comment by rusdyahmad** [comment]
You may publish the Blade templates using 

`php artisan vendor:publish --provider="ProtoneMedia\Splade\ServiceProvider" --tag="views"`

Now the templates are available in the `/resources/views/vendor/splade` folder.

You can modify as needed for each form you want.

**Comment by zulfikar-ditya** [comment]
@rusdyahmad Thanks
