### ISSUE TITLE
[Feature] Slideover position to slide from left to right

### ISSUE THREAD

**Issue by raftalks** [protonemedia/laravel-splade#249]
As of now the slideover only works opens from right side of the screen, I think giving the option to open either from right or left will be a useful and simple feature to add.

**Comment by pascalbaljet** [comment]
Good idea!

**Comment by pascalbaljet** [comment]
As of v1.2.4, you may set the `position` attribute to `left`:

```blade
<x-splade-modal position="left">
    ...
</x-splade-modal>
```

Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).
