### ISSUE TITLE
Show loader instead of pre-rendered content

### ISSUE THREAD

**Issue by pascalbaljet** [protonemedia/laravel-splade#25]
It would be nice if there was some kind of loading spinner/screen that fades away when the Vue app is mounted. 

This might be a Vite ‘issue’, as it happens with a vanilla Jetstream installation as well. Let’s see if we can fix the flickering before the app is mounted.

**Comment by tekleberhan** [comment]
yes the same issue

**Comment by pascalbaljet** [comment]
I found out this is a non-issue as it only happens when developing. On production builds, the CSS gets loaded first.
