### ISSUE TITLE
Accessing events/hooks on flatpickr

### ISSUE THREAD

**Issue by JapSeyz** [protonemedia/laravel-splade#250]
- Laravel Version: 9.47.0
- PHP Version: 8.1.14
- Splade JS Version (npm): 1.1.7
- Splade PHP Version (composer): 1.1.7

You may use the [built-in Artisan Command](https://splade.dev/docs/upgrading) to show the installed versions of the packages:

```bash
php artisan splade:show-versions
```

### Description:

How does one go about accessing events/hooks from flatpickr?

I've got a splade-form in a blade view, however writing a javascript function in a heredoc and passing it to either the `date` or `JsFlatpickrOptions` prop, seems to not work.

https://flatpickr.js.org/events/

**Comment by JapSeyz** [comment]
Update, having tried `@js` without luck:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/2234034/213922588-5ac82959-5f6c-4ae2-aa98-73343a07d828.png">


<img width="429" alt="image" src="https://user-images.githubusercontent.com/2234034/213922629-5ef374aa-6fd2-4742-ae6a-52aa37d30c31.png">


<img width="618" alt="image" src="https://user-images.githubusercontent.com/2234034/213922615-e3c1d46b-abbb-46d7-9f96-e7888e32ccb9.png">

**Comment by pascalbaljet** [comment]
The right syntax would be:

```blade
<x-splade-input name="date_of_birth" date="{ onOpen: () => alert('x') }" />
```

Except this throws an error as it can't find the `alert` function (or `console`, `window`, etc.). I'll look into it. Probably have to bind the function to the context.

```js
jsFlatpickrOptions.onOpen = jsFlatpickrOptions.onOpen.bind(this);
```

What is the use case?

**Comment by iMusicJJ** [comment]
A calendar of vacation-days - where I'd add a small mark under the days with plans. This however requires the onDayCreate event.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/57725397/214574817-7df38766-f329-4a78-8491-4fbfaff7a830.png">


<img width="393" alt="image" src="https://user-images.githubusercontent.com/57725397/214574727-436583f1-c026-44cf-a649-ff500ea32262.png">

https://flatpickr.js.org/events#ondaycreate

**Comment by pascalbaljet** [comment]
This works, but I'll try to refactor it to get rid of the `$splade` object.

```blade
<x-splade-script>
    $splade.setVacationDays = function(dObj, dStr, fp, dayElm) {
        console.log(dObj, dStr, fp, dayElm);
    };
</x-splade-script>

<x-splade-input name="date_of_birth" date="{ onDayCreate: $splade.setVacationDays }" />
```

**Comment by JapSeyz** [comment]
Great, thanks!

**Comment by JapSeyz** [comment]
I am gonna make this even more difficult. `date` is already taken up by a PHP variable w/ dates:

```blade
@php
    $dates = [
        'minDate' => 'today',
        'enable' => $model->availableDates(),
    ];

    // TODO: OnDayCreate here: https://flatpickr.js.org/events#ondaycreate
@endphp
```

```blade
<x-splade-input class="border-gray-300" name="dates" :date="$dates" range jsFlatpickrOptions="{ onDayCreate: $splade.setVacationDays }"/>
```

And then it again seems that jsFlatpickrOptions doesn't do a whole lot for me in the scenario. It doesn't emit an error in the console, but neither does it log anything to the console, even though there's dates created.

Got any ideas?

**Comment by pascalbaljet** [comment]
```blade
<x-splade-script>
    @php
        $phpOptions = [
            'minDate' => 'today',
        ];
    @endphp

    $splade.datesOptions = {
        onDayCreate: function(dObj, dStr, fp, dayElm) {
            console.log(dObj, dStr, fp, dayElm);
        },
        ...@json($phpOptions)
    };
</x-splade-script>

<x-splade-form>
    <x-splade-input name="dates" date="$splade.datesOptions" />
    <x-splade-submit />
</x-splade-form>
```

**Comment by JapSeyz** [comment]
I see, so there's a json and js helper. Sweet.

It works like a charm.
