### ISSUE TITLE
Textarea isnt working

### ISSUE THREAD

**Issue by hipoagencia** [protonemedia/laravel-splade#254]
- Laravel Version: 9.19
- PHP Version: 8.1
- Splade JS Version (npm): 2.1 with breeze
- Splade PHP Version (composer): 1.2.1

You may use the [built-in Artisan Command](https://splade.dev/docs/upgrading) to show the installed versions of the packages:

```bash
php artisan splade:show-versions
```

### Description:

https://user-images.githubusercontent.com/79876130/214030340-fd04afce-1669-4dd4-bb31-55105a53ad48.mp4

### Steps To Reproduce Issue:

- In the video, i'm not sure why the record didnt showed PHPStorm, but anyway, i just uncommented the textarea.
- When i use splade textarea, everything on the page goes away.
```bash
<x-splade-textarea name="biography" autosize />
```

**Comment by JapSeyz** [comment]
Try to upgrade both Splade PHP and JS versions, and show us the rest of the code.

There's nothing wrong with the textarea, so it must be something surrounding it, or interacting with it.

**Comment by hipoagencia** [comment]
> Try to upgrade both Splade PHP and JS versions, and show us the rest of the code.
> 
> There's nothing wrong with the textarea, so it must be something surrounding it, or interacting with it.

Already did it. Im looking for another solution.

**Comment by JapSeyz** [comment]
> Already did it. Im looking for another solution.

Alright, can you show me the code for the entire form?

**Comment by hipoagencia** [comment]
```
<x-splade-form method="patch" :action="route('profile.update')" :default="$user" class="mt-6 space-y-6">
        <div class="grid grid-cols-1 lg:grid-cols-4 gap-4">

            <h2 class="text-lg font-medium text-white col-span-4 mt-3">Avatar</h2>

            <p class="col-span-4  lg:col-span-1">
                <img src="{{$user->avatar}}" alt="Avatar" class="rounded-full mb-5">
                <x-splade-file name="avatarUpload" filepond preview accept="image/png, image/jpeg, image/jpg, image/gif" max-size="1MB" :min-resolution="300 * 300"/>
            </p>

            <h2 class="text-lg font-medium text-white col-span-4 mt-3">Geral</h2>

            <x-splade-input id="name" name="name" type="text" :label="__('Name')" required autofocus autocomplete="name"  class="col-span-4  lg:col-span-1"/>
            <x-splade-input id="email" name="email" type="email" :label="__('Email')" required autocomplete="email" class="col-span-4  lg:col-span-1"/>

            <x-splade-input id="whatsapp" name="whatsapp" type="text" :label="__('WhatsApp')" required autocomplete="whatsapp" class="col-span-4  lg:col-span-1"/>
            <x-splade-input id="date_birth" name="date_birth" type="data" :label="__('Data de Nascimento')" required autocomplete="date_birth" date class="col-span-4  lg:col-span-1"/>

            <h2 class="text-lg font-medium text-white col-span-4 mt-3">Biografia</h2>

            <x-splade-textarea  class="col-span-4" id="biography" name="biography" type="text" :label="__('Biografia')"  autocomplete="facebook" autosize />

            <h2 class="text-lg font-medium text-white col-span-4 mt-3">Social</h2>

            <x-splade-input id="facebook" name="facebook" type="text" :label="__('Facebook')"  autocomplete="facebook" class="col-span-4  lg:col-span-1"/>
            <x-splade-input id="instagram" name="instagram" type="text" :label="__('Instagram')"  autocomplete="instagram" class="col-span-4  lg:col-span-1"/>
            <x-splade-input id="linkedin" name="linkedin" type="text" :label="__('Linkedin')"  autocomplete="biography" class="col-span-4  lg:col-span-1"/>

        </div>

        @if ($user instanceof \Illuminate\Contracts\Auth\MustVerifyEmail && ! $user->hasVerifiedEmail())
            <div>
                <p class="text-sm mt-2 text-gray-300">
                    {{ __('Your email address is unverified.') }}

                    <Link method="post" href="{{ route('verification.send') }}" class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        {{ __('Click here to re-send the verification email.') }}
                    </Link>
                </p>

                @if (session('status') === 'verification-link-sent')
                    <p class="mt-2 font-medium text-sm text-green-600">
                        {{ __('A new verification link has been sent to your email address.') }}
                    </p>
                @endif
            </div>
        @endif

        <div class="flex items-center gap-4">
            <x-splade-submit label="Salvar" class="button-bg"/>

            @if (session('status') === 'profile-updated')
                <p class="text-sm text-gray-600">
                    Atualizado com sucesso
                </p>
            @endif
        </div>
    </x-splade-form>
```

**Comment by iMusicJJ** [comment]
Thanks, and lastly, do you have the network payload/response for the weird behaving request?

**Comment by hipoagencia** [comment]
> Thanks, and lastly, do you have the network payload/response for the weird behaving request?

![image](https://user-images.githubusercontent.com/79876130/214461021-08c47d6c-1463-4076-bfce-f7044f97c287.png)

**Comment by hipoagencia** [comment]
I've found one way to reproduce the bug. If i refresh the page, i get this error. If i come from another page, the textarea works fines.

**Comment by iMusicJJ** [comment]
For the request/response. I need to see the payload of the specific request that triggers the error. (Headers etc too, if possible).

Is there an error in the console when recreating it? It looks like it on your photo.

**Comment by hipoagencia** [comment]
Sorry for the late response.
The error in the console is another think.. Its about OWL Carousel

![image](https://user-images.githubusercontent.com/79876130/214565235-2b4b64d5-c2fe-48d6-9f20-cab36b3837e9.png)

I've noticed that the payload preview it's empty like the url

![image](https://user-images.githubusercontent.com/79876130/214565331-f494e886-d6e6-4efb-b58b-a4a83310daa8.png)

**Comment by hipoagencia** [comment]
And it's strange because when i load for the first time, loads correctly. When i refresh the page, thats the result.

If i remove textarea, everything workings fine on refresh.

**Comment by iMusicJJ** [comment]
I am not entirely sure what the problem is - I thought it was related to submitting the form. However this seems to be on load.

Is the issue that the form is entirely black?

**Comment by hipoagencia** [comment]
Exactly! But only when i refresh the page. I've found the error while i was editting de form and VITE refreshed the page. But, if i came from another page, everything works fine.

**Comment by iMusicJJ** [comment]
Hmm, it'd like to check it out - do you have a reproduction link, or can invite me to the repo?

If you need to invite me, invite @JapSeyz please, and I'll have a look after work.

**Comment by hipoagencia** [comment]
The link is: [](https://decola.io)

And if you still need access to the repo, there's no problem. Just let me know.
I will record the path that you need to do.

Thanks for your help and time.

**Comment by iMusicJJ** [comment]
Okay, it seems like the OwlCarousel is breaking the loading of further JS.

Can you try to either fix the OwlCarousel bug, or temporarily disable it / load it async. Right now it's throwing an exception that blocks the rest of the JS from successfully running.

**Comment by iMusicJJ** [comment]
You also still have the `dynamicProps` issue from here:

https://github.com/protonemedia/laravel-splade/issues/185

**Comment by hipoagencia** [comment]
> 

oh ok! I will fix now..  Few days ago, Pascal released an option to use javascript in splade

**Comment by hipoagencia** [comment]
I've tryed to use <x-splade-script>but the plugins just died. But no problem, now the JS is commented and the error persists.

You can check, its live.

**Comment by iMusicJJ** [comment]
I am still getting the exception from OwlCarousel, as mentioned here: https://github.com/protonemedia/laravel-splade/issues/254#issuecomment-1403567459

<img width="641" alt="image" src="https://user-images.githubusercontent.com/57725397/214571822-d3cf3776-8ec7-4949-80a2-ca4bc9ece1b4.png">

Can you try to disable it entirely?

**Comment by hipoagencia** [comment]
> I am still getting the exception from OwlCarousel, as mentioned here: [#254 (comment)](https://github.com/protonemedia/laravel-splade/issues/254#issuecomment-1403567459)
> 
> <img alt="image" width="641" src="https://user-images.githubusercontent.com/57725397/214571822-d3cf3776-8ec7-4949-80a2-ca4bc9ece1b4.png">
> 
> Can you try to disable it entirely?

Awesome! I think that everything is working fine now.
Really apreciate your help. As soon as i start to earn, i will contribute for sure.

**Comment by hipoagencia** [comment]
I'm looking for a package to do the same thing as Owl, do you recomend one?

**Comment by hipoagencia** [comment]
I've found another error.. when i use the command:

```
sail artisan splade:show-versions
Composer (PHP) package version: 1.2.4
NPM (JS) package not found

```

Maybe this is the problem that DEFER and REQUIRE PASSWORD isnt working right?
