### ISSUE TITLE
How to pass x-xsrf-token on Link with custom method

### ISSUE THREAD

**Issue by HUGE-D1CK-10-INCHES** [protonemedia/laravel-splade#256]
Trying to delete something via link:

`<Link method="DELETE" href="{{ route('social.unlink', [$social->id]) }}" >Unlink</Link>`

Which returns 419, csrf is not passed within request..

Passing custom headers doesn't work:
 `:headers="['x-xsrf-token' => csrf_token()]"`

**Comment by JapSeyz** [comment]
Is your endpoint within the Splade middleware? and do you have `<meta name="csrf-token" content="{{ csrf_token() }}">` in your `root.blade.php`?

I believe `Link` used `axios` under the hood, which should detect the csrf token automatically

**Comment by HUGE-D1CK-10-INCHES** [comment]
Yeah, I thinks its not working when sending between subdomains even tho I set session domain  for subdomains as well..

**Comment by pascalbaljet** [comment]
The Form and Link components use the same logic under the hood to send requests. Axios sends the `XSRF-TOKEN` cookie along with the request, which should handle Laravel's CSRF Protection. You should update the cookie settings accordingly if you're sending requests to (other) subdomains. Check out the `session.domain` configuration key. On top of my head, it should be `.domain.com` to allow subdomains.
