### ISSUE TITLE
[Feature Request] Splade Table with pagination links to preserve scroll

### ISSUE THREAD

**Issue by raftalks** [protonemedia/laravel-splade#261]
If the Splade table is placed down at a scrolled position of a lengthy page with pagination links when clicked, needs an option to let those links preserve-scroll for a better user experience. 

```
<x-splade-table pagination-preserve-scroll ... />
```

**Comment by pascalbaljet** [comment]
Instead of scrolling to the top of the page, wouldn't you prefer to scroll to the top of the table (considering the table is not at the top of the page)?

**Comment by raftalks** [comment]
> Instead of scrolling to the top of the page, wouldn't you prefer to scroll to the top of the table (considering the table is not at the top of the page)?

Yes, that is a valid user experience to scroll to the top of the table when paginating instead to the top of the page.

**Comment by pascalbaljet** [comment]
Cool! I'll look into it.

**Comment by pascalbaljet** [comment]
As of v1.4.15, there's a `pagination-scroll` attribute to control the behavior. You may set it to `top` (default), `head`, or `preserve`.

Docs: https://splade.dev/docs/table-overview

Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).
