### ISSUE TITLE
x-splade-defer and input

### ISSUE THREAD

**Issue by hipoagencia** [protonemedia/laravel-splade#262]
- Laravel Version: 9.48
- PHP Version: 8.0
- Splade PHP Version (composer): Splade Breeze 2.2

### Description:
I'm using <x-splade-defer> to get data from an API:

```
<x-splade-defer
                                url="`https://viacep.com.br/ws/${form.zipcode}/json/`"
                                watch-value="form.zipcode"
                                watch-debounce="700"
                                manual>
```

At this point, everything working just fine! I can set the value of the textbox with the response using v-model:

```
<x-splade-input id="city" name="city" label="Cidade"
                                                class="col-span-2 lg:col-span-1"  v-model="response.localidade"/>
```

But, Laravel doesnt recognize the value of a v-model. I've trying a few combinations to make it working, but without success.

Thanks!

**Comment by JunedSetiawan** [comment]
Same issue

**Comment by pascalbaljet** [comment]
As of v1.2.5, you can use the response data in the `@success` event:

```blade
<x-splade-form>
    <x-splade-input name="zipcode" label="Zipcode"/>
    <x-splade-input name="city" label="Cidade"/>

    <x-splade-defer
        url="`https://viacep.com.br/ws/${form.zipcode}/json/`"
        watch-value="form.zipcode"
        watch-debounce="100"
        manual
        @success="(response) => form.city = response.localidade"
    />
</x-splade-form>
```

Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).
