### ISSUE TITLE
Adding preserve-scroll to Splade Link not working.

### ISSUE THREAD

**Issue by twoarmtom** [protonemedia/laravel-splade#264]
- Laravel Version: 9.48.0
- PHP Version: 8.1.7 
- Splade JS Version (npm): 1.1.2
- Splade PHP Version (composer): 1.2.4

### Description:

Using preserve-scroll with x-splade-link in a table does not preserve scroll.

### Steps To Reproduce Issue:

In my Splade Table I add preserve-scroll to the splade-link
```
<x-splade-cell action>
                    
  <x-splade-link confirm="Delete competency?" href="{{ route('submitted-competencies.destroy', $item->id) }}" method="delete" 
   class="button-danger text-xs p-2" preserve-scroll>
      <x-heroicon-o-trash />
  </x-splade-link>

</x-splade-cell>
```

In my Controller
```
public function destroy(SubmittedCompetency $submittedCompetency)
    {
        $this->authorize('delete', $submittedCompetency);
        // delete the submitted competency
        $submittedCompetency->delete();
        // create the toast message
        Toast::title('Competency Deleted!')->warning()->autoDismiss(3);

        return redirect()->back();
    }
```
Always scrolls back to the top of the page (on page one of the table as well).

**Comment by pascalbaljet** [comment]
You need to update the npm package, it was added in [v1.1.3](https://github.com/protonemedia/laravel-splade/releases/tag/1.1.3) :)

**Comment by twoarmtom** [comment]
Thank you!  Didn't realize that!  Updated and works.
