### ISSUE TITLE
How to pass an event or data to the backend controller with Splade?

### ISSUE THREAD

**Issue by zamarproject** [protonemedia/laravel-splade#265]
- Laravel Version: #.#.#
- PHP Version: 8.0.2
- Splade JS Version (npm): 1.2.2
- Splade PHP Version (composer): 1.2.2

You may use the [built-in Artisan Command](https://splade.dev/docs/upgrading) to show the installed versions of the packages:

```bash
php artisan splade:show-versions
```

### Description:

I have reading the whole documentation, and still I´m striving to get the right information to send values to the backend through some event, not precisely using Forms, like a button, using some JS function, sending with Axios.

But seems to be that something is not working well, or the Splade Middleware is affecting the process, I would like to know, 
how could I send a post request to the controller
Thank you.

**Comment by twoarmtom** [comment]
Can you provide your code as an example to help understand exactly what you are attempting to do?

**Comment by zamarproject** [comment]
Sure! Thank you.

Route: 
`Route::post('/submitdata', ActionButtonController::class, 'submitData');`
 Blade: 
   Option 1)
` <button onclick="boxstatus( {{ $box->id }} )">Box Status</button>`
 
   Option 2)
`<button @click="$splade.emit('boxstatus', { boxid: {{ $box->id }}  })">Box Status</button>`  
  
Using Axios in my main.js file: 

`window.boxstatus = function (boxId){

    const data = { 
        boxid: boxId,
        name: 'John Doe', 
        email: 'johndoe@example.com', 
        age: 30 }; 

        axios.post('/api/submit-data', data) 
        .then(response => { 
            console.log(response); 
        })
        .catch(error => { 
            console.error(error); 
        });

}`

Also using Axios but using x-splade-script:

`<x-splade-script>
    $splade.on('boxstatus', function(boxID)){

    const data = { 
        boxid: boxId,
        name: 'John Doe', 
        email: 'johndoe@example.com', 
        age: 30 }; 

        axios.post('/api/submit-data', data) 
        .then(response => { 
            console.log(response); 
        })
        .catch(error => { 
            console.error(error); 
        });
    }

</x-splade-script>`

Controller: 
`public function submitData(Request $request){

        $data = $request->all(); 
        
        return response()->json([
            'message' => 'Success: POST request received',
            'data' => 'Post Request Arrived!'
        ], 200);

    }
`

*   The route is located in the Api Folder.


Thank you in advance for any advise.

**Comment by twoarmtom** [comment]
Why not just use a Splade Link?

```
<x-splade-link href="/api/submit-data" method="POST" 
data="{ 
    boxid: boxId,
    name: 'John Doe', 
    email: 'johndoe@example.com', 
    age: 30 
}" preserve-scroll>
```
Then use the integrated Toast messages in the controller to return messages to the front end if required.
```
use ProtoneMedia\Splade\Facades\Toast;

// not sure what you're doing with this $data, but do what you need to.

$data = $request->all(); 

// create a success message, could be conditional if you want.

Toast::success('Success: POST request received');

// returning back when using preserve-scroll in the front end will maintain 
// page scroll position, just as though you have done an axios request

return redirect()->back();
```

**Comment by zamarproject** [comment]
Woow! 
I didn´t know that I could use the splade-link lilke a form !! Amazing! 
I will give a try, and I will let you know, how did work ! 
Thanks a lot! 
:)

**Comment by zamarproject** [comment]
By the way, I wrote $data = $request->all without a specific purpose, just to get the $request in a variable  to send it back.
:)

**Comment by zamarproject** [comment]
One more question, I have the route in the API folder, but I had a response in the console:
"The response is not a Splade response. Did you use the Splade Middleware on this route?"
So, 1) I have to place this route in the web folder inside the Splade Middleware?
2) in the Api folder, I have to place this route creating a Splade Middleware ?
Thank you so much.

**Comment by twoarmtom** [comment]
The routes needs to be wrapped with the [Splade middleware](https://splade.dev/docs/navigation-routing).

I have not tested this in the api.php file.  But for the SPA magic, the routes need to be within a Splade Middleware.

**Comment by zamarproject** [comment]
Ohh ok! 
I tried in the web folder with the Splade Middleware, but when I´m clicking it, is sending me to the route as a view, and do not return.
and no response.

<x-splade-link href="/api/submitdata" method="POST" preserve-scroll data="{ 
                        id : {{ $box->id }},   
                        name : 'John Doe', 
                        email : 'johndoe@example.com', 
                        age : 30
                    }" class="btn btn-secondary btn-sm">
                        SENDING 
</x-splade-link>

in the API folder:
Route::middleware('splade')->group (
    function () {
        Route::post('/submitdata', ActionButtonController::class, 'submitData');
});

In the controller:
    public function submitData(Request $request){

        Toast::success('Success: POST request received');
        
        return redirect()->back();
    }

Response in the Console:
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (submitdata, line 0)

Response in the Browser:
"Session store not set on request."



Now:
Having the route in the Web Folder, also inside the Splade Middleware:

in the x-splade-link I´m removing in the url : "/api", just "/submitdata"

the route in the web folder in side the Splade Middleware
 Route::post('/submitdata', ActionButtonController::class, 'submitData');
 
 
 Response in the Console:    Nothing.
 Response in the Browser: Blank but the url shows the route:     http://127.0.0.1:8000/submitdata

**Comment by twoarmtom** [comment]
I don't know what version of Laravel you are using, but the Route you are showing should likely be written with the Class and function in an array.

```
use App\Http\Controllers\ActionButtonController; // assuming this is where your controller is

Route::post('/submitdata', [ActionButtonController::class, 'submitData'])
```

As I mentioned, I'm not using any api's in my project, but this should work in your web.php file assuming you've imported the Class.

**Comment by zamarproject** [comment]
Hi Twoarmtom

Truly I appreciattd your following to this issue that I´m facing, about the Laravel version I´m LARAVEL v9.48.0, VITE 3.2.5 
and SPLADE this last version 1.2.4

I´ve just upgraded Splade from version 1.2.2., I cleared views, I placed the route in WEB, not in API, as Post, the rest of the code is the same:

Blade:
                    <x-splade-link href="/submitdata" method="POST" preserve-scroll :data="[
                        'id' => $box->id,   
                        'name' => 'John Doe', 
                        'email' => 'johndoe@example.com', 
                        'age' => 30
                        ]" 
                        class="btn btn-secondary btn-sm">
                        SENDING 
                    </x-splade-link>
CONTROLLER:
class ActionButtonController extends Controller{

    public function submitData(Request $request){
          $box = Box::find($request->id);
          $box->update([
            'box_status' => 18,
        ]);
        Splade::toast('Finally!: ');   
        return redirect()->back();
    }          
}

Seems that all is working great! 
Thank you so much for helping me. 
Greetings!

**Comment by twoarmtom** [comment]
Glad it's working, maybe you can close this issue now?

**Comment by zamarproject** [comment]
Oh yes, sorry. Thank you so much again. Greetings.
