### ISSUE TITLE
Add to docs about SpladePreserveScroll

### ISSUE THREAD

**Issue by HUGE-D1CK-10-INCHES** [protonemedia/laravel-splade#269]
If you want you could add to docs this if someone want to preserve scroll on vue component:

`v-SpladePreserveScroll:sidebar:[string]`

Maybe I missed something, but I needed to add it like this: `v-SpladePreserveScroll:sidebar` - to work

**Comment by pascalbaljet** [comment]
It's in the [Navigation and routing](https://splade.dev/docs/navigation-routing) section (*Preserve scroll position*).

**Comment by HUGE-D1CK-10-INCHES** [comment]
@pascalbaljet yea for blade, not for vue

**Comment by pascalbaljet** [comment]
I'll add that, thanks!

**Comment by HUGE-D1CK-10-INCHES** [comment]
No problem

**Comment by pascalbaljet** [comment]
Added in https://github.com/protonemedia/laravel-splade-docs/commit/4edb47a0d9e4fa9dee74af19a7932122ca979cef
