### ISSUE TITLE
Undefined constant Maatwebsite\Excel\Excel::XLSX

### ISSUE THREAD

**Issue by propanto** [protonemedia/laravel-splade#270]
- Laravel Version: 9 latest
- PHP Version: 8.1.14
- Splade JS Version (npm): 1.2.1
- Splade PHP Version (composer):  1.2.4

### Description:

Add `export(label: 'Posts Excel')` on Post table and this error `Undefined constant Maatwebsite\Excel\Excel::XLSX` appear.

example here: https://github.com/propanto/laravel-splade-crud

**Comment by pascalbaljet** [comment]
You need the `maatwerk/laravel-excel` package: https://splade.dev/docs/table-exports
