### ISSUE TITLE
Register user show error 403 when implements MustVerifyEmail

### ISSUE THREAD

**Issue by helio-cg** [protonemedia/laravel-splade#274]
- Laravel Version: 9.48.0
- PHP Version: 8.2.1

### Description:

When implementing the verify email function after registration, it displays a 403 permission error. I can only see the page with the instructions to verify email at (route: 'verify-email') after reloading the page.

**Comment by HUGE-D1CK-10-INCHES** [comment]
Well isn't  that the point, not sure if this is splade issue.
