### ISSUE TITLE
SELECT component and Spatie Permissions

### ISSUE THREAD

**Issue by hipoagencia** [protonemedia/laravel-splade#275]
Hello again! I'm really focused to use Splade :D
- Laravel Version: 9.48
- PHP Version: 8
- Splade PHP Version (composer): 1.2.4

### Description:

I'm using the SELECT component with users permissions like this:

`<x-splade-select name="permissions" label="Permissões" class="col-span-3" option-label="name" option-value="name" :options="$permissions" placeholder="Selecione as permissões..." choices multiple relation></x-splade-select>`

So for so good.. i can edit and assign all the roles. But, when i try to update a user, there's no selected permissions.
On de controller, i already loaded the relation:

```
     public function edit(User $user)
    {
        $permissions = Permission::select('name')->orderBy('name')->get();

        $user->load('permissions');

        return view('admin.user.edit', compact('user', 'permissions'));
    }
```

Anyone knows what i'm missing?
Thanks!

**Comment by pascalbaljet** [comment]
Try `name="permissions[]"` with the brackets. Can you share the complete `<x-splade-form>` section of your template?

**Comment by hipoagencia** [comment]
Already tryed "permissions[]"

`

                    <x-splade-form default="{{$user}}" action="{{route('users.update', $user)}}" method="PUT" >

                        <div class="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-4">
                            <x-splade-input name="name" label="Nome"></x-splade-input>
                            <x-splade-input name="email" label="E-mail"></x-splade-input>

{{--                            @dd($user->permissions)--}}

                            <x-splade-select name="permissions" label="Permissões" class="col-span-3" option-label="name" option-value="name" :options="$permissions" placeholder="Selecione as permissões..." choices multiple relation></x-splade-select>
                        </div>

                        <x-splade-submit>Atualizar</x-splade-submit>

                    </x-splade-form>`

The complete form section!

Thanks

**Comment by HUGE-D1CK-10-INCHES** [comment]
Not sure if this would help you but I use it this way:

```
<x-splade-form action="/update-user" method="PATCH" :default="(array) $user" class="space-y-4">
<x-splade-select name="roles" multiple choices :options="$roles" option-label="title" option-value="id" :label="__('Choose Roles')" :placeholder="__('Select roles')" />
```

Now, I need to convert $user to array, thats why I added (array) $user, I think it wont work otherwise since it cannot look into loaded relation collection.

**Comment by hipoagencia** [comment]
> Not sure if this would help you but I use it this way:
> 
> ```
> <x-splade-form action="/update-user" method="PATCH" :default="(array) $user" class="space-y-4">
> <x-splade-select name="roles" multiple choices :options="$roles" option-label="title" option-value="id" :label="__('Choose Roles')" :placeholder="__('Select roles')" />
> ```
> 
> Now, I need to convert $user to array, thats why I added (array) $user, I think it wont work otherwise since it cannot look into loaded relation collection.

if i use (array), all the inputs gets blank on update.

**Comment by HUGE-D1CK-10-INCHES** [comment]
Can you send the whole form code?

**Comment by hipoagencia** [comment]
``> Can you send the whole form code?

Sure..

 <x-splade-form default="{{$user}}" action="{{route('users.update', $user)}}" method="PUT" >

                        <div class="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-4">
                            <x-splade-input name="name" label="Nome"></x-splade-input>
                            <x-splade-input name="email" label="E-mail"></x-splade-input>



                            <x-splade-select name="permissions" label="Permissões" class="col-span-3" option-label="name" option-value="name" :options="$permissions" placeholder="Selecione as permissões..." choices multiple relation></x-splade-select>
                        </div>

                        <x-splade-submit>Atualizar</x-splade-submit>

                    </x-splade-form>`

`
  public function edit(User $user)
    {
        $permissions = Permission::select('name')->orderBy('name')->get();

        $user->load('permissions');

        return view('admin.user.edit', compact('user', 'permissions'));
    }
`

**Comment by HUGE-D1CK-10-INCHES** [comment]
What is `relation` on  select, and show me the opening form tag

**Comment by hipoagencia** [comment]
Ops, sorry. Forgot the opening tag. In the documentation, it says to use relation when the data come from a relation
`
 <x-splade-form default="{{$user}}" action="{{route('users.update', $user)}}" method="PUT" >
`

**Comment by HUGE-D1CK-10-INCHES** [comment]
Pass it as array as I did and remove that relation part, it should work

**Comment by hipoagencia** [comment]
> Pass it as array as I did and remove that relation part, it should work

Okay.. i will try again. Thanks

**Comment by hipoagencia** [comment]
> Pass it as array as I did and remove that relation part, it should work

If i pass as array, every input goes empty!

**Comment by HUGE-D1CK-10-INCHES** [comment]
As I posted it above and my `User $user`, automatically gets roles because I added it to protected `$with = ['roles'];`

So I have just route model binding User $user passed

**Comment by HUGE-D1CK-10-INCHES** [comment]
can you dd() $user to check what is getting there?
`<x-splade-input type="text" name="name" :label="__('Name')" required/>`
This is how my other inputs look like. Try with one input, maybe something else is problem check the console, sometimes if something else  is problem nothing in form would fill up.

**Comment by hipoagencia** [comment]
![image](https://user-images.githubusercontent.com/79876130/216327567-de352928-9276-4678-bf02-c9722f5092e1.png)

**Comment by stuartcusackie** [comment]
Just chipping in here a year later. Here's how I did it:

```
<x-splade-select
  id="role_names"
  name="role_names[]" 
  label="Roles"
  option-label="name" 
  option-value="name" 
   :options="$roleOptions"
  choices 
  multiple 
/>
```

Then in my user model:

```
    protected $appends = [
        'role_names'
    ];

    protected function roleNames(): Attribute
    {
        return new Attribute(
            get: fn () => $this->getRoleNames()
        );
    }
```

Maybe it can be done using the 'relation' tag on the select but I couldn't figure out how to mark the current roles as selected that way.

By the way, this example doesn't show you how to assign the roles after update.
