### ISSUE TITLE
How to translate x-splade-cell actions to other language

### ISSUE THREAD

**Issue by tommy66374** [protonemedia/laravel-splade#284]
- Laravel Version: 9.50.0
- PHP Version: 8.1.2
- Splade JS Version (npm): #.#.#
- Splade PHP Version (composer): 1.2.6

### Description:

How to translate x-splade-cell `actions` to other language

### Steps To Reproduce Issue:

```
->column(label: 'Actions', canBeHidden: false)
```

```
<x-splade-table :for="$users">
    <x-splade-cell actions>
        <Link href="/users/{{ $item->id }}/edit"> Edit </Link>
    </x-splade-cell>
</x-splade-table>
```

tired this didn't work

```
    <x-splade-cell :actions="__('Actions')">
```

**Comment by pascalbaljet** [comment]
You may use the `key` argument:

```php
->column(key: 'actions', label: __('Actions'), canBeHidden: false)
```

Then you can keep using the `actions` attribute in the Blade component, independent from the translation:

```blade
<x-splade-cell actions>
```
