### ISSUE TITLE
Problem when running build

### ISSUE THREAD

**Issue by imariusalin** [protonemedia/laravel-splade#285]
- Laravel Version: 9.50.2
- PHP Version: 8.1.10
- Splade JS Version (npm): 1.2.9
- Splade PHP Version (composer): 1.2.9

You may use the [built-in Artisan Command](https://splade.dev/docs/upgrading) to show the installed versions of the packages:

```bash
php artisan splade:show-versions
```

### Description:

app.7f3afa27.js:29 SyntaxError: 24 (at app.7f3afa27.js:29:102088)
    at et (app.7f3afa27.js:29:102088)
    at je (app.7f3afa27.js:30:6571)
    at _F (app.7f3afa27.js:30:1836)
    at Bp (app.7f3afa27.js:29:109191)
    at _F (app.7f3afa27.js:30:1589)
    at Bp (app.7f3afa27.js:29:109191)
    at gF (app.7f3afa27.js:29:108434)
    at EN (app.7f3afa27.js:35:21086)
    at HN (app.7f3afa27.js:35:25333)
    at jN (app.7f3afa27.js:35:25842)

### Steps To Reproduce Issue:

This issue appears only when the command npm run build is executed. In dev is working.
I made a short screen record of the issue. 

https://youtu.be/cqOwTUggZ-s

Thanks in advance!

**Comment by pascalbaljet** [comment]
Maybe it's a syntax error in your Blade template, can you share it? And what version of Node/NPM are you running?

**Comment by imariusalin** [comment]
Hi , https://github.com/imariusalin/erfcV4-2023  , i have added you to collaborators , thanks a lot

**Comment by imariusalin** [comment]
You ware right, i had issues inside my blade template. Thanks for the help!

**Comment by romain-lgr** [comment]
I have a similar issue. May I ask how you manage to debug?
