### ISSUE TITLE
Can we use route naming in <Link>? 

### ISSUE THREAD

**Issue by takielias** [protonemedia/laravel-splade#290]
- Laravel Version: 9.50
- PHP Version: 8.2.1
- Splade JS Version (npm): 1.2.11
- Splade PHP Version (composer): 1.2.11

### Description:

We generally use 

`<Link modal href="/users/create">Create new user</Link>`

Can we use route naming? Like below

`<Link modal :href="route('users.create')">Create new user</Link>`

**Comment by ShiferawAbel** [comment]
has this been answered?
