### ISSUE TITLE
x-splade-select choices showing &amp;

### ISSUE THREAD

**Issue by jamesj2** [protonemedia/laravel-splade#292]
- Laravel Version: 9.50.2
- PHP Version: 8.1.14
- Splade JS Version (npm): 1.2.11
- Splade PHP Version (composer): 1.2.11.1

### Description:

Select labels are displaying html entities when using the choices option of x-splade-select.  It works fine without the choices option.

### Steps To Reproduce Issue:

The following:
```
<x-splade-select name="status" placeholder="Status" label="Status" :options="['1'=>'&Active','0'=>'Inactive']" choices/>
```

Will display to the user:
```
&amp;Active
```

**Comment by pascalbaljet** [comment]
The Choices.js integration doesn't allow HTML in the elements (to prevent XSS attacks), but you may override it:

```blade
<x-splade-select name="status" placeholder="Status" label="Status" :options="['1'=>'&Active','0'=>'Inactive']" choices="{allowHTML: true}" />
```
