### ISSUE TITLE
Splade toast line feeds not shown

### ISSUE THREAD

**Issue by jamesj2** [protonemedia/laravel-splade#294]
- Laravel Version: 9.50.2
- PHP Version: 8.1.14
- Splade JS Version (npm): 1.2.11
- Splade PHP Version (composer): 1.2.11.1

### Description:

Not able to use line feeds in toasts.  I did a little digging and the line feeds are present on the payload from the server but when displayed they are not.  I suspect the JS component is removing them.   I also tried `<br/>` but HTML gets escaped.  Is it possible to preserve the line feeds and/or HTML? 

### Steps To Reproduce Issue:

In the example app add `Splade::toast("line1\nline2")->info();` to the home controller.  The toast displays as `line1 line2` without the linefeed.

**Comment by pascalbaljet** [comment]
Fixed in v1.2.12, make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).
