### ISSUE TITLE
(bug) Form clear button changed the checkboxes to non-array

### ISSUE THREAD

**Issue by tommy66374** [protonemedia/laravel-splade#295]
- Laravel Version: 9.50.0
- PHP Version: 8.1.2
- Splade JS Version (npm): #.#.#
- Splade PHP Version (composer): 1.2.6

Click the link below to watch the Youtube video for more details.

[![Watch the Youtube video](https://img.youtube.com/vi/5994nx9IXFU/0.jpg)](https://www.youtube.com/watch?v=5994nx9IXFU)

**Comment by HUGE-D1CK-10-INCHES** [comment]
You can talk so video doesn't go up to 5 minutes, no one has time to watch it. Anyway, the reset function resets the whole form to empty object, and restore uses default data structure. I posted a similar issue. Maybe its supposed to work like that.

**Comment by tommy66374** [comment]
> You can talk so video doesn't go up to 5 minutes, no one has time to watch it. Anyway, the reset function resets the whole form to empty object, and restore uses default data structure. I posted a similar issue. Maybe its supposed to work like that.

I don't have mic and English not my first language, sorry about that.
