### ISSUE TITLE
[Feature Request] Defer Request-Headers

### ISSUE THREAD

**Issue by REIZFLUT** [protonemedia/laravel-splade#298]
- Laravel Version: 9.51.0
- PHP Version: 8.2.2
- Splade JS Version (npm): 1.2.11
- Splade PHP Version (composer): 1.2.11.1

### Description:

It would be cool, if I could set a headers-object for defer components.

### Steps To Reproduce Issue:
```
<x-splade-defer method="POST" url="/post/increase" request="{ post_id: 1 }"
 headers="{ 
    Authorisation: sessionStorage.getItem('auth.post.increase'),
    Accept: 'application/json'
}">
```

May be done by adding headers property to Defer.vue and setting it as config.headers inside the performRequest method.
(lib/Components/Defer.vue line 108)

```
performRequest() {

...

this.headers.Accept = this.headers.Accept || this.acceptHeader;
            
const config = {
    url: this.url,
    method: this.method,
    headers: this.headers
}

...

}
```

**Comment by pascalbaljet** [comment]
Added in v1.2.12, make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).

Docs: https://splade.dev/docs/x-defer

**Comment by REIZFLUT** [comment]
Thank you for your good work 👍
