### ISSUE TITLE
Prerender content when initially requesting a page

### ISSUE THREAD

**Issue by Wulfheart** [protonemedia/laravel-splade#3]
As the rendering process on the server side happens with Blade it would be really nice to already have the content shown when the page is loaded. This would have the benefit that no SSR process on the server side would be needed.

What do you think about it?

**Comment by pascalbaljet** [comment]
Yeah, I thought about it too. We can do two things: include the content as you said, or run a dedicated SSR process as Inertia.js does. The benefit of the last approach is that it will render Vue components as well. I can imagine building apps with Splade and still needing some Vue components here and there.

**Comment by pascalbaljet** [comment]
I came up with a solution that includes both. You can run a dedicated SSR process to get the fully rendered content, and there's a *Blade fallback* option, which echoes out the rendered Blade view (which will be replaced by Vue whenever it mounts).

https://github.com/protonemedia/laravel-splade/blob/b9e924d75d32da531ba2d51368859a1d9029fb15/config/splade.php#L12-L20

**Comment by Wulfheart** [comment]
OMG!!!

**Comment by pascalbaljet** [comment]
This is now available in [v0.2](https://github.com/protonemedia/laravel-splade/releases/tag/0.2.0) ([docs](https://splade.dev/docs/ssr)).
