### ISSUE TITLE
Splate fail tfaild to add middleware and exceptionHandler at right place while installing in laravel version ^9.19

### ISSUE THREAD

**Issue by sayyadkhan5774900** [protonemedia/laravel-splade#304]
- Laravel Version: ^9.19
- PHP Version: ^8.0.2
- Splade JS Version (npm): 1.2.12
- Splade PHP Version (composer): 1.2.12

Splade failed to add its middleware in routeMiddleware intead it add at karnal top and it did same for exceptionHandler while installing in laravel version ^9.19

**Comment by pascalbaljet** [comment]
Are you using Windows?

**Comment by sayyadkhan5774900** [comment]
Yes, I am using the window OS.
