### ISSUE TITLE
How to use x-splade-script component?

### ISSUE THREAD

**Issue by p4rad0xus** [protonemedia/laravel-splade#312]
- Laravel Version: 9.51.0
- PHP Version: 8.2.1
- Splade JS Version (npm): 1.1.6
- Splade PHP Version (composer): 1.2.13
- Dev environment (OS, Sail/Valet/etc): Sail

### Description:

How can I use the x-splade-script component to use custom javascript to manipulate the DOM?

In the [documentation](https://splade.dev/docs/x-script) the `x-splade-script` component is described but if I use the component the following error is prompt:

```
[Vue warn]: Failed to resolve component: SpladeScript
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

If I follow the warning and set the compilerOptions the warning is still coming.

```
export default defineConfig({
  plugins: [
    vue({
      template: {
        compilerOptions: {
          isCustomElement: (tag) => ['x-splade-script'].includes(tag),
        }
      }
    })
  ]
})
```

**Comment by pascalbaljet** [comment]
Please keep and use the issue template with the Laravel/PHP/Splade versions, otherwise I can't help.

**Comment by p4rad0xus** [comment]
Thanks for the fast comment. I update my description.

**Comment by pascalbaljet** [comment]
The Script component was added in v1.2, so you need to update the NPM package :)
