### ISSUE TITLE
dynamic input

### ISSUE THREAD

**Issue by skuzalabs** [protonemedia/laravel-splade#313]
- Laravel Version: 9.51.0
- PHP Version: 8.1.15
- Splade JS Version (npm): 1.2.12
- Splade PHP Version (composer): 1.2.13
- Dev environment (OS, Sail/Valet/etc): OS

### Description:

hello, I followed the instructions in the document, but I have a problem with dynamic input. when i change the value of the first input the other input also changes the value following the value of the first input

```blade
<x-splade-form>
    <Calculator :form="form">
        @foreach($item as $key => $items)
            <x-splade-input label="Qty" name="qty" />
        @endforeach
    </Calculator>
</x-splade-form>
```

[the doc](https://splade.dev/docs/custom-form-components)

**Comment by romain-lgr** [comment]
May I ask how you solve this issue? I have a similar case. Thanks!
