### ISSUE TITLE
Bulk action doesn't work when pagination enabled

### ISSUE THREAD

**Issue by tapan288** [protonemedia/laravel-splade#321]
- Laravel Version: 10.0.3
- PHP Version: 8.2.1
- Splade JS Version (npm): 1.2.15
- Splade PHP Version (composer): 1.2.15
- Dev environment:  Valet

### Steps To Reproduce Issue:
I tried to use bulk actions and noticed that it doesn't work when pagination is enabled.
For demonstration, I'm uploading a Video:

https://user-images.githubusercontent.com/46927593/219845180-d9a23509-f8dd-44a9-b6a5-079655a0c53d.mp4

**Comment by pascalbaljet** [comment]
You should call the `paginate` method on the `SpladeTable` instance, not in the `for` method. Check out the 'example table' section: https://splade.dev/docs/table-query-builder
