### ISSUE TITLE
[Feature] Customize the progress indicator.

### ISSUE THREAD

**Issue by prpanto** [protonemedia/laravel-splade#322]
- Laravel Version: latest
- PHP Version: 8.1
- Splade JS Version (npm): latest
- Splade PHP Version (composer): latest
- Dev environment (OS, Sail/Valet/etc): Ubuntu Valet

I want to customize the progress indicator, Is there any way to achieve this?

**Comment by pascalbaljet** [comment]
What do you want to customize? You may already change the color and delay: https://splade.dev/docs/progress-bar

**Comment by pascalbaljet** [comment]
Then you need to set the `css` config to `false` and add your own CSS for NProgress: https://github.com/protonemedia/laravel-splade/blob/aeba92cba5878e76b6180ab3485b6729b28ddc47/lib/SpladeProgress.js#L9-L66
