### ISSUE TITLE
[Feature Request] Expose a response property inside the <x-splade-form /> component.

### ISSUE THREAD

**Issue by mccarlosen** [protonemedia/laravel-splade#323]
- Laravel Version: 9.19
- PHP Version: 8.1.12
- Splade JS Version (npm): 1.2.4
- Splade PHP Version (composer): 1.2.4
- Dev environment (OS, Sail/Valet/etc): Homestead

### Description:

Expose a property that allows you to manipulate the response inside the `<x-splade-form />` component when we use the `stay` property. This would be useful in forms that work with steps or parts. Having a response property would help to modify values or respond to a certain logic.

#### For example:

```php
// ...

class FormController extends Controller
{
    // ....
    public function save(Request $request)
    {
        $step = $request->input('step');
        if ($step == 'verification') {
            $data = $request-->validate(/* ... */);
            // ...
            return response()->json(['step' => 'verified']);
        }
        if ($step == 'finish') {
            $data = $request-->validate(/* ... */);

            // ...

            Model::create([/* ... */]);

            return response()->json(['step' => 'complete']);
        }
    }
}
```

Using a response property: This way is limited because I can't update the form's properties.

```blade
<x-splade-form stay default="{step: 'verification'}">
    <div v-show="form.step == 'verification'">
        <!-- .... -->
    </div>
    <div v-show="form.response.step == 'verified'">
        <!-- fill other information -->
    </div>
    <div v-show="form.response.step == 'finish'">
        <!-- .... -->
    </div>
</x-splade-form>
```

Using a response event emitted from the component:

```blade
<x-splade-form stay default="{step: 'verification'}">
    <x-splade-script>
        function updateValues(form, response) {
            form.$put('step', response.step)
        }
        $splade.on('response', updateValues)
    </x-splade-script>
    <div v-show="form.step == 'verification'">
        <!-- .... -->
    </div>
    <div v-show="form.step == 'verified'">
        <!-- fill other information -->
    </div>
    <div v-show="form.step == 'finish'">
        <!-- .... -->
    </div>
</x-splade-form>
```

I've noticed that the component emits the `success` event when it receives the response, but with that alone you can manipulate it outside of the `<x-splade-form />` component, so you don't have access to the `form` property of the component.

Maybe there's a better way to approach this. I hope you get the idea.

**Comment by pascalbaljet** [comment]
I like the idea! I'll try to include it in the next release :)

**Comment by pascalbaljet** [comment]
As of v1.4.0, the `form` object has a `$response` key:

```blade
<x-splade-form stay>
    <pre v-text="form.$response" />
</x-splade-form>
```
