### ISSUE TITLE
Did I miss anything to set up the pusher?

### ISSUE THREAD

**Issue by takielias** [protonemedia/laravel-splade#325]
- Laravel Version: 10.0.3
- PHP Version: 8.2.1
- Splade JS Version (npm): 1.2.15
- Splade PHP Version (composer): 1.2.15
- Dev environment (OS, Sail/Valet/etc): Windows (Laragon)

```shell
class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Broadcast::routes();

        require base_path('routes/channels.php');
    }
}

```

```shell
Broadcast::channel('App.Models.User.{id}', function (User $user, $id) {
    return (int)$user->id === (int)$id;
});

Broadcast::channel('task.{user_id}', function (User $user, $user_id) {
    return (int)$user->id === (int)$user_id;
});

```

But when a dispatch an event, I usually get 
```shell
ReflectionException

Property Illuminate\Broadcasting\BroadcastEvent::$user does not exist
```

I have followed each & every step [here](https://laravel.com/docs/10.x/broadcasting)

Is there any extra step did I miss to set up the pusher?

**Comment by HUGE-D1CK-10-INCHES** [comment]
Why is this splade question?

**Comment by takielias** [comment]
> Why is this splade question?

I'm only getting this on splade.
