### ISSUE TITLE
Show error in console

### ISSUE THREAD

**Issue by ifathurrohman** [protonemedia/laravel-splade#328]
I am trying Laravel Splade. I have registered and logged in without any issue. However, when I tried to log in with the wrong password, there was an error in the console. Is this a problem?

![Screenshot 2023-02-24 222710](https://user-images.githubusercontent.com/13009992/221219296-aa98379f-710b-47cc-8ff0-d4cfdfe2630e.png)

**Comment by jitterbux** [comment]
I am experiencing the same error as well:

<img width="953" alt="Screenshot 2023-02-25 at 13 23 02" src="https://user-images.githubusercontent.com/102470544/221356619-5c9db474-37af-44c4-9f19-015104971538.png">

**Comment by HUGE-D1CK-10-INCHES** [comment]
Well you are using vue which send axios requests, it does it by default as I know because its error code from server

**Comment by ifathurrohman** [comment]
So, is the error not a problem?

**Comment by pascalbaljet** [comment]
This intentional and a 422 error indicates a validation error. There is probably a way to disable the errors with Axios, but I like that you can see the HTTP errors in the console.
