### ISSUE TITLE
Integration TailwindUI Admin Theme/Sidebar Layout

### ISSUE THREAD

**Issue by ifathurrohman** [protonemedia/laravel-splade#329]
- Laravel Version: 10.0.3
- PHP Version: 8.2.3
- Splade JS Version (npm): 1.2.15
- Splade PHP Version (composer): 1.2.15
- Dev environment (OS, Sail/Valet/etc): Laragon

Hi, has anyone here ever used the TailwindUI sidebar layout admin theme design? I am having trouble integrating this admin template with Splade, especially when it comes to displaying and hiding the mobile navigation.

**Comment by pascalbaljet** [comment]
You may use the [Toggle](https://splade.dev/docs/x-toggle) or [Data](https://splade.dev/docs/x-data) component to toggle elements.

The Breeze starter kit uses [a toggle](https://github.com/protonemedia/laravel-splade-breeze/blob/92a9452db2bb10c102a7af18c30e9e003489f1f9/stubs/splade/resources/views/layouts/navigation.blade.php#L1) and the Jetstream starter kit uses a [global data store](https://github.com/protonemedia/laravel-splade-jetstream/blob/6b6f6ef490286ba6a34c0cdde8dfe197c075f7de/stubs/splade/resources/views/components/navigation.blade.php#L1).
