### ISSUE TITLE
It does not allow to use of table class when custom head and body

### ISSUE THREAD

**Issue by mccarlosen** [protonemedia/laravel-splade#334]
- Laravel Version: 9.52.4
- PHP Version: 8.1.12
- Splade JS Version (npm): 1.3.1
- Splade PHP Version (composer): 1.3.1
- Dev environment (OS, Sail/Valet/etc): Linux mint/Homestead

### Description:

https://user-images.githubusercontent.com/8524361/222322951-efb18c12-cd50-46a5-86b6-9cc054eb95a8.mp4

### Steps To Reproduce Issue:

This works:

```html
<x-splade-table :for="$posts" as="$post">
    <x-splade-cell recibo.orden>
        @if ($post->estado == 'Pendiente')
        -
        @else
        <div class="font-medium text-center text-white py-1 px-2 bg-color1-600 rounded-lg">
            {{ trim($post->recibo->orden) }}
        </div>
        @endif
    </x-splade-cell>
    <x-splade-cell fecha_creacion>
    {{ date('d/m/Y', strtotime($post->fecha_creacion)) }}
    </x-splade-cell>
</x-splade-table>
```
This doesn't work:

```html
<x-splade-table :for="$posts">
    <x-slot name="head">
        <thead class="text-xs">
            <tr class="border-gray-300 bg-gray-200 text-color1-500 border-y hidden lg:table-row">
                @foreach($posts->columns() as $column)
                    <th class="p-3 tracking-wider text-left uppercase lg:table-cell">{{ $column->label }}</th>
                @endforeach
            </tr>
        </thead>
    </x-slot>

    <x-slot name="body">
        <tbody class="text-xs">
            @foreach($posts->resource as $post)
                <!-- ..... -->
            @endforeach
        </tbody>
    </x-slot>
    
    <x-slot:empty-state>
        <p>No hay registros</p>
    </x-slot>
</x-splade-table>
```

**Comment by mccarlosen** [comment]
Something new?

**Comment by pascalbaljet** [comment]
The `$posts` variable is the fully qualified class name of the Table (`Posts::class`), so it's a *string* and you can't call any methods on that. Under the hood, when you pass a classname/string to  the `Table` component, it creates an instance of that class.

In the next release, I'll add a static `build()` method that you can use in the controller (instead of `::class`). I'll let you know once it's released.

**Comment by pascalbaljet** [comment]
Added in v1.4.7, make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).

So in your controller, don't pass `Posts::class` to the view, but `Posts::build()`.
