### ISSUE TITLE
Can't make Vue3 Carousel to work

### ISSUE THREAD

**Issue by hipoagencia** [protonemedia/laravel-splade#335]
- Laravel Version: 10.1
- PHP Version: 8.1
- Splade PHP Version (composer): 1.2.15
- Dev environment: Sail

### Description:

Hello!

I've done the same thing as the docs: https://splade.dev/docs/using-vue-libraries
But the carousel isnt working properly.

My code:

```
                <Carousel>
                    @for($i = 1; $i <= 10; $i++)
                        <CarouselSlide key="{{ $i }}">
                            <img src="{{Vite::asset('resources/img/thumb.jpeg')}}" alt="">
                        </CarouselSlide>
                    @endfor
                </Carousel>
```

### Steps To Reproduce Issue:

https://user-images.githubusercontent.com/79876130/222417244-eadb5c50-457d-4d79-a693-94ac814c160a.mp4

**Comment by pascalbaljet** [comment]
Did you include the Carousel CSS file? 

https://ismail9k.github.io/vue3-carousel/getting-started.html
