### ISSUE TITLE
Can we write vue methods in blade?

### ISSUE THREAD

**Issue by soixt** [protonemedia/laravel-splade#338]
Most of the time while using @click, or something like that in blade I need to write a little bit more code instead of simple on/off, so is there a way to write inline functions?

**Comment by pascalbaljet** [comment]
I recommend using [Custom Vue components](https://splade.dev/docs/custom-vue-components), but if you really want to do it inline, you may use the global `$splade` instance to bind functions with a [Script component](https://splade.dev/docs/x-script):

```blade
<button @click="$splade.doSomething()">Click me</button>

<x-splade-script>
    $splade.doSomething = function () {
        alert('Hey');
    };
</x-splade-script>
```
