### ISSUE TITLE
Select with multiple prop autocloses in modal

### ISSUE THREAD

**Issue by soixt** [protonemedia/laravel-splade#340]
Not sure how to even debug this besides sharing this picture:

![select](https://user-images.githubusercontent.com/100382372/222922464-dc34eab5-f72b-4892-8d05-03be57ca4138.png)

Basically, if this is in modal (not self page), when you click on  left side / over the search input it auto closes the dropdown, its like doing two events. One to open by clicking on label and other to close by clicking on search input side.
![select2](https://user-images.githubusercontent.com/100382372/222923199-4d27d12d-f159-4c85-be92-2518c8d8eb13.png)
When removing these 2 events, everything works fine

**Comment by pascalbaljet** [comment]
Fixed in v1.4.2, make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).
