### ISSUE TITLE
Laravel Splade does not auto-redirect on authentication

### ISSUE THREAD

**Issue by MotionPhix** [protonemedia/laravel-splade#342]
I find it very irritating recently that when I click on a link that requires authentication, instead of Laravel taking me to the login page, I am getting the ``Illuminate \ Auth \ AuthenticationException`` errror ``Unauthenticated``. I have tried to change the settings and even wrote my own middleware, but this problem persists. Is there something I am missing? An extra note is that this only happens when I click on Link. It redirects pretty fine when I use the normal anchor tags

**Comment by HUGE-D1CK-10-INCHES** [comment]
Try modifying this:
https://splade.dev/docs/exception-handling

**Comment by MotionPhix** [comment]
Probably I don't know what I should modify in that file, but so far I am getting the following error:

![image](https://user-images.githubusercontent.com/59722054/222969859-5073b9fd-b8a6-481c-8652-ed9f75fea073.png)

Any ideas?

**Comment by MotionPhix** [comment]
Solved it. Had to write my own render function in the ``Exceptions\Handler.php``

**Comment by pascalbaljet** [comment]
Fixed in v1.4.2.

**Comment by MotionPhix** [comment]
> 

Great! Thanks. Let me try upgrading, because the render function I implemented myself doesn't auto-redirect to the page someone wa viewing. It always redirects to the **dashboard** after getting authenticated. So let's hope this works differently. I'll be back with feedback.
