### ISSUE TITLE
Form components -> FilePond:  How to hide the text "Powered by PQINA"?

### ISSUE THREAD

**Issue by faydanube** [protonemedia/laravel-splade#343]
```php
<x-splade-file name="signature" label="label" max-size="1MB" filepond server preview />
```

<img width="706" alt="image" src="https://user-images.githubusercontent.com/8817046/222976226-b2bf51a5-a4b1-4a1e-b4cd-f169b96e8ea6.png">

How to hide the text marked in the above screenshot? I've tried posting the css and making changes, also tried a global search on ...... Anyone who knows can help me ma

**Comment by HUGE-D1CK-10-INCHES** [comment]
```
.filepond--credits {
    display: none;
}
```

**Comment by Gigoland** [comment]
credits       | `{ label, url }` | Shows [Powered by PQINA](#disabling-credits) in footer

`credits: false`
