### ISSUE TITLE
Get continious error on console when using searchEnabled: true

### ISSUE THREAD

**Issue by takielias** [protonemedia/laravel-splade#344]
- Laravel Version: 10.0.3
- PHP Version: 8.2.0
- Splade JS Version (npm): 1.3.1
- Splade PHP Version (composer): 1.3.1
- Dev environment (OS, Sail/Valet/etc): Laragon on Windows

I developed a complex form with multiple texts, select & radio inputs. Everything is fine except searchEnabled select option. 

```shell
                                            <div>
                                                <label
                                                    class="block text-sm font-medium text-gray-700">Medical
                                                    Center</label>
                                                <x-splade-select name="medical_center"
                                                                 choices="{ searchEnabled: true }"
                                                                 v-model="form.medical_center"
                                                                 class="mt-1"
                                                                 :options="$medical_center"/>
                                            </div>
```

After selecting an option from that select menu I continuously got a console error.

![Screenshot_3](https://user-images.githubusercontent.com/38932580/223008912-bd3dc90f-1448-4af0-9b9e-9d473c89238c.jpg)

If I click the js files for details I get this
![Screenshot_4](https://user-images.githubusercontent.com/38932580/223009001-40d81b89-3c65-4574-a93d-dd04dcbb51b5.jpg)

If I disable the search, It works fine. 

My options array looks like 

```shell
 $medical_center = [
        'Human Diagnostic and Medical',
        'Ferdous Medical Centre',
        'Green Crescent Medical Diagnostic',
        'Medicare Medical Check-up Centre'
    ];
```
Did I miss anything?

**Comment by pascalbaljet** [comment]
`searchEnabled` is set to `true` by default. Any reason you're passing it as a custom config?
