### ISSUE TITLE
Vue-ChartJS usage in splade

### ISSUE THREAD

**Issue by bardolf69** [protonemedia/laravel-splade#345]
- Laravel Version: 10.2.0
- PHP Version: 8.1.16
- Splade JS Version (npm): 1.3.1
- Splade PHP Version (composer): 1.3.1
- Dev environment (OS, Sail/Valet/etc): Alpine Linux built the docker image php:8.1-fpm-alpine

### Description:

I'm trying to get Vue-ChartJS working on my first splade site.  I think I have everything setup right but when I try to pass th chartData to the component I get a javascript error saying the 'labels' is undefined.

### Steps To Reproduce Issue:

I installed the package via NPM and setup the package in app.js as below
```
import "./bootstrap";
import "../css/app.css";
import "@protonemedia/laravel-splade/dist/style.css";

import { createApp } from "vue/dist/vue.esm-bundler.js";
import { renderSpladeApp, SpladePlugin } from "@protonemedia/laravel-splade";
import { Bar, Line, Pie } from 'vue-chartjs';
import { Chart as ChartJS, Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale } from 'chart.js';

ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale);

const el = document.getElementById("app");

createApp({
    render: renderSpladeApp({ el })
})
    .use(SpladePlugin, {
        "max_keep_alive": 10,
        "transform_anchors": false,
        "progress_bar": true,
        "components": {
            BarGraph: Bar,
            LineGraph: Line,
            PieGraph: Pie,
        },
    })
    .mount(el);
```
Then in my blade I used the following
```
<BarGraph :data="$graph" />
```
and graph data is setup like Vue-ChartJS requests it.
```
$graph = {
    "labels":["2023-02-27","2023-02-28","2023-03-01","2023-03-02","2023-03-03","2023-03-04","2023-03-05","2023-03-06"],
    "datasets":{
        "data":[126,126,126,126,126,126,126,126]
    }
}
```

**Comment by HUGE-D1CK-10-INCHES** [comment]
Where do you set this up? can't do that in php, add it as array or json string.

**Comment by HUGE-D1CK-10-INCHES** [comment]
Well share actual code of how you create those strings, and why don't you just pass array?

**Comment by MotionPhix** [comment]
> ```
> @foreach ($users as $graph)
>      <BarGraph :data="$graph" />
> @endforeach
> ```

Probably you should do
```
@foreach ($users as $graph)
    <BarGraph :data="@js($graph)" />
@endforeach
```

I am assuming that the ``<BarGraph />`` is a Vuejs component

**Comment by bardolf69** [comment]
> Well share actual code of how you create those strings, and why don't you just pass array?
```
$period = CarbonPeriod::create($start, $end)->toArray();
        foreach($period as $day){
            $range[] = $day->toDateString(); 
        }
 $tmp['labels'] = $range;
$tmp['datasets']['data'][] = DB::table('users')
                        ->where('created_at', '<=', $date)
                        ->count();
$userData[] = json_encode($tmp);
```
These snippets are taken from several different methods, but it shows how the values are calulated.  I passed the json string because that is what the Vue-ChartJS component is expecting.

**Comment by bardolf69** [comment]
> <BarGraph :data="@js($graph)" />

trying that chamged the error from being unable to read the 'labels' to being unable to read the 'map' properties

**Comment by bardolf69** [comment]
> > ```
> > @foreach ($users as $graph)
> >      <BarGraph :data="$graph" />
> > @endforeach
> > ```
> 
> Probably you should do
> 
> ```
> @foreach ($users as $graph)
>     <BarGraph :data="@js($graph)" />
> @endforeach
> ```
> 
> I am assuming that the `<BarGraph />` is a Vuejs component

trying that changed the error from being unable to read the 'labels' to being unable to read the 'map' properties

**Comment by mobreviews** [comment]
I eventually gave up on this library and opted to use [https://chartkick.com/vue](https://chartkick.com/vue) for my charts instead.

**Comment by pascalbaljet** [comment]
Due to [this ticket](https://github.com/protonemedia/laravel-splade/issues/403), I've added additional documentation on how to pass PHP data to Vue components:

https://splade.dev/docs/using-vue-libraries
