### ISSUE TITLE
Splade Input Errors based on Label attribute

### ISSUE THREAD

**Issue by alexpitacci** [protonemedia/laravel-splade#358]
Is there a way to show validation errors based on Label attribute in x-splade-input?

**Comment by pascalbaljet** [comment]
Can you show an example? You can change the validation key:

```blade
<x-splade-input name="email" validation-key="email_address" />
```

**Comment by SebRothIFB** [comment]
I have the same question. 

Here is an example: 

`                        <x-splade-group inline>
                            <x-splade-input name="Eig_Position" label="eigene Position" />
                            <x-splade-input name="Buchungsnummer" label="Buchungsnummer*" />
                            <x-splade-select name="FCL_LCL" label="FCL oder LCL? *" :options="[1 => 'FCL', 2 => 'LCL']" choices />
                        </x-splade-group>`

![image](https://github.com/protonemedia/laravel-splade/assets/63638852/e601c9d8-f799-4a24-86d4-36cd2a9d3fb4)
