### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by thewebartisan7** [protonemedia/laravel-splade#37]
First of all congrats for this great package!

Seem missing a progress bar when request take too much, something like in InertiaJS.

Thanks!

**Comment by thewebartisan7** [comment]
I see that with SSR it's render css immediately 👍

**Comment by pascalbaljet** [comment]
Thanks! I had a progress bar in a very early version of Splade, but I removed it along the way. It would be a great addition!

**Comment by pascalbaljet** [comment]
Fixed in [v0.4.11](https://github.com/protonemedia/laravel-splade/releases/tag/0.4.11)

Docs: https://splade.dev/docs/progress-bar
