### ISSUE TITLE
JS library load problem

### ISSUE THREAD

**Issue by MdAnowarHosen** [protonemedia/laravel-splade#372]
Flowbite js not working after click a link. But if I refresh the page then it's work. How to fix that?

**Comment by mobreviews** [comment]
have you checked your dev console in your browser to see if any errors are thrown.  Normally that sort of behaviour is caused by an unhandled error in the js which stops all future js from running.

**Comment by MdAnowarHosen** [comment]
it's works when I add that js library to `root.blade.php` file
