### ISSUE TITLE
Dynamic Remote URL Not Working

### ISSUE THREAD

**Issue by MdAnowarHosen** [protonemedia/laravel-splade#376]
- Laravel Version: 10.0
- PHP Version: 8.1
- Splade PHP Version (composer): 1.4.6

```
<x-splade-select name="category_id" label="Select Category" :options="$categories" option-label="name"  option-value="id" required/>

<x-splade-select name="subcategory_id" remote-url="`get/subcategory/${form.category}`" label="Sub Category" option-value="id" select-first-remote-option />
```
After I select a category It should show sub categories on another select input. But it's does not work. Please correct me.

**Comment by omidnadeem** [comment]
> * Laravel Version: 10.0
> 
>     * PHP Version: 8.1
> 
>     * Splade PHP Version (composer): 1.4.6
> 
> 
> ```
> <x-splade-select name="category_id" label="Select Category" :options="$categories" option-label="name"  option-value="id" required/>
> 
> <x-splade-select name="subcategory_id" remote-url="`get/subcategory/${form.category}`" label="Sub Category" option-value="id" select-first-remote-option />
> ```
> 
> After I select a category It should show sub categories on another select input. But it's does not work. Please correct me.

@MdAnowarHosen your first select name should pass to the second select
<x-splade-select name="category_id" label="Select Category" :options="$categories" option-label="name"  option-value="id" required/>

<x-splade-select name="subcategory_id" remote-url="`get/subcategory/${form.category_id}`" label="Sub Category" option-value="id" select-first-remote-option />

**Comment by MdAnowarHosen** [comment]
@omidnadeem brother. It's working.
