### ISSUE TITLE
Feature request TipTap editor

### ISSUE THREAD

**Issue by thewebartisan7** [protonemedia/laravel-splade#38]
Would be good to have a rich textarea with https://tiptap.dev/

**Comment by rodrigopedra** [comment]
Tiptap maybe? https://tiptap.dev/

**Comment by thewebartisan7** [comment]
Ops yes right tiptap.dev ))

**Comment by boranbar** [comment]
It would be great if we had a component for a popular rich text editor like CKEditor, TinyMCE etc...

**Comment by soixt** [comment]
@boranbar why don't you create a component for one and then share it here?

**Comment by pascalbaljet** [comment]
We're using Quill in one of our projects, and I like it. However, it has been over three years since there has been a new release which worries me. They're [working hard](https://github.com/quilljs/quill/issues/3694) on the next version, though! Native support for tables and uploads in the editor are very welcome.

**Comment by uqjohart** [comment]
> Vuequill could be added very quickly
> 
> `npm install @vueup/vue-quill@latest --save`
> 
> Then in `app.js` add Quill.
> 
> ```
> import { QuillEditor } from '@vueup/vue-quill'
> import '@vueup/vue-quill/dist/vue-quill.snow.css';
> createApp({
>     render: renderSpladeApp({ el })
> })
>     .use(SpladePlugin, {
>         "max_keep_alive": 10,
>         "transform_anchors": false,
>         "progress_bar": true,
>         "components": {
>             QuillEditor
>         }
>     })
>     .mount(el);
> ```

How are you adding it to your blade? I've been wracking my brain and just cant get it to render on my splade form for the life of me. I looked at the doco and they just seems to use a <div id="editor"></div> but this wont render in the component.
(apologies, I'm still learning so I'm pretty stupid)

My simple splade comp:
<x-layout>
  <x-panel>
    <x-splade-lazy>
       <x-splade-form :default="$experiment">
         <div id="editor"></div>
         // also tried <x-splade-textarea name="notes" label="Notes" id="editor" />
       </x-splade-form>
        </x-splade-lazy>
    </x-panel>
</x-layout>

It just refuses to render.

**Comment by HUGE-D1CK-10-INCHES** [comment]
@uqjohart 
Add this inside form, or maybe make a form component @pascalbaljet 
```
<div>
  <label class="block">
      <span class="block mb-1 text-gray-700 font-sans">Description</span>
      <div class="rounded-md border border-gray-300 shadow-sm">
          <quill-editor name="descriptipn" id="description" v-model:value="form.description" toolbar="full" />
          <x-splade-input type="hidden" name="description" />
      </div>
  </label>
</div>
```

**Comment by pascalbaljet** [comment]
Anyone familiar with Jodit? https://xdsoft.net/jodit/

**Comment by MichInf** [comment]
following the response from @HUGE-D1CK-10-INCHES , it was important for me to use v-model:content instead of :value to make the data submission work properly in the form and avoid null request. I used a syntax similar to the example.


      <div class="rounded-md border border-gray-300 shadow-sm">
          <quill-editor name="description" v-model:component="form.description" componentType="html" toolbar="full" />
          <x-splade-input type="hidden" name="description" />
      </div>

**Comment by hipoagencia** [comment]
> <div>
>   <label class="block">
>       <span class="block mb-1 text-gray-700 font-sans">Description</span>
>       <div class="rounded-md border border-gray-300 shadow-sm">
>           <quill-editor name="descriptipn" id="description" v-model:value="form.description" toolbar="full" />
>           <x-splade-input type="hidden" name="description" />
>       </div>
>   </label>
> </div>

Doing exactly what you said, my website goes all blank with this message um console:

caught TypeError: Cannot read properties of undefined (reading 'description')
    at Proxy.render (eval at compileToFunction (vue.esm-bundler.js:65:21), <anonymous>:253:33)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5649:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5777:9)
    at mountComponent (runtime-core.esm-bundler.js:5559:9)
    at processComponent (runtime-core.esm-bundler.js:5517:17)
    at patch (runtime-core.esm-bundler.js:5119:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5656:21)


Any suggest?

**Comment by hipoagencia** [comment]
> v-model:component="form.description"

Like this i get no errors:

```
<div class="rounded-md border border-gray-300 shadow-sm">
       <quill-editor name="descrip" v-model="form.descrip"  toolbar="full" />
</div>
```

But i cant get the value on $request.. Thanks for your time!

**Comment by hipoagencia** [comment]
> :content

using v-model:content="form.description"

i could achive this:

![image](https://user-images.githubusercontent.com/79876130/236338262-c89c2eb8-1a3d-492e-9567-423ebf2a5fec.png)

**Comment by hipoagencia** [comment]
> Anyone familiar with Jodit? https://xdsoft.net/jodit/

Do you pretend to make a tutorial with how we can implement this? It will be awesome.

**Comment by pascalbaljet** [comment]
Thanks to great work by @J87NL, Splade now supports the Jodit editor as of v1.4.10:

```blade
<x-splade-form>
    <x-splade-wysiwyg name="body" />
</x-splade-form>
```

Because Jodit's stylesheet is quite large, I decided not to include it in the default `style.css`, so you need to manually add it to the main `app.js` file:

```diff
import "@protonemedia/laravel-splade/dist/style.css";
+ import "@protonemedia/laravel-splade/dist/jodit.css";
import { renderSpladeApp, SpladePlugin } from "@protonemedia/laravel-splade";
```

I'll soon add this to the docs!
