### ISSUE TITLE
How to use v-model.lazy in select component

### ISSUE THREAD

**Issue by MdAnowarHosen** [protonemedia/laravel-splade#383]
- Laravel Version: 10.0
- PHP Version: 8.1
- Splade JS Version (npm): 
- Splade PHP Version (composer): 1.4.6

`<x-splade-select name="category_id[]" label="Select Category" :options="$categories" option-label="name"  option-value="id" required multiple choices/>`

I want to select multiple categories and after select my categories then want to send a request to server. But how? **Those codes sending requests on every category select.** Here how to use `v-model-lazy` in `select` component?

**Comment by pascalbaljet** [comment]
Why does it send a request to the server after selecting a category? Are you using a dependent select?
