### ISSUE TITLE
[QUESTION] HOW TO GET ALL CHECKED DATA IN BULK ACTIOIN

### ISSUE THREAD

**Issue by zulfikar-ditya** [protonemedia/laravel-splade#385]
- Laravel Version: 10.5.1
- PHP Version: 8.1.2
- Splade JS Version (npm): 1.4.7
- Splade PHP Version (composer): 1.4.7

let say we have case like generating item receiving report from many purchasing data, and we need all the checked data in data table, is that any option for this features?

**Comment by pascalbaljet** [comment]
This was undocumented, but the `before` and `after` callbacks receive all ids. When all rows are selected, the callbacks receive an array with a single `*` item:

```php
$table->bulkAction(
    label: 'Notify users',
    before: function (array $selectedIds) {
        $users = User::query()
            ->unless($selectedIds === ['*'], fn ($query) => $query->whereIn('id', $selectedIds))
            ->get();
 
        Mail::to($users)->send(new ImportantNotification);
    }
);
```

**Comment by zulfikar-ditya** [comment]
maybe can help with it [pr for doc get all selected data](https://github.com/protonemedia/laravel-splade-docs/pull/49)
