### ISSUE TITLE
Middleware isn't working!

### ISSUE THREAD

**Issue by MdAnowarHosen** [protonemedia/laravel-splade#391]
- Laravel Version: 10.0
- PHP Version: 8.1
- Splade JS Version (npm): 1.4.7
- Splade PHP Version (composer):  1.4.7

`verified ` middleware not working!
I'm using `Jetstream Starter Kit` for auth system.

My codes:

```
Route::middleware(['splade'])->group(function () {
    Route::middleware([
        'auth:sanctum',
        'auth',
        config('jetstream.auth_session'),
        'verified',
        'admin'
    ])->prefix('admin')->name('admin.')->group(function ()
    {
      // some routes
    });
});
```

What to do?

**Comment by mobreviews** [comment]
Shouldn't there be a 'splade' middleware in there as well? [https://splade.dev/docs/manual-installation](https://splade.dev/docs/manual-installation)

**Comment by MdAnowarHosen** [comment]
I have used 'splade' middleware in parent route of those routes.

**Comment by MdAnowarHosen** [comment]
Custom `middleware` working. But default `verified` middleware not working.

**Comment by MdAnowarHosen** [comment]
My bad! I forgot to implements `MustVerifyEmail` to User model.
