### ISSUE TITLE
Can not use Link component to root layout!

### ISSUE THREAD

**Issue by MdAnowarHosen** [protonemedia/laravel-splade#396]
- Laravel Version: 10.x
- PHP Version:8.1
- Splade JS Version (npm): 1.4.7
- Splade PHP Version (composer): 1.4.7

I can't use Link component to root layout, also I can't use `<x-nav-link>` component. Both are showing as text in root layout. **What or which component should I use to root layout for navigation menu?**

Here is my root layout codes:

```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        @spladeHead
        @vite('resources/js/app.js')
    </head>
    <body class="font-sans antialiased">
        <div class="container mx-auto">
            <div class="text-center text-xl font-bold mt-3">
                <h1>Laravel Splade</h1>
                <Link route('/') >Home</Link>
                <x-nav-link :href="route('users')">Users</x-nav-link>
            </div>
            @splade
        </div>
    </body>
</html>
```

**Comment by J87NL** [comment]
Please try:

<Link href="/">Home</Link>

**Comment by MdAnowarHosen** [comment]
Still it doesn't works! @J87NL

**Comment by rusdyahmad** [comment]
It won't work because everything will be done on `@splade`

You need to put the link in the `/views/layouts/app.blade.php` or include from your custom/existing `components`

**Comment by pascalbaljet** [comment]
@rusdyahmad is correct. The `@splade` directive is an alias for the Vue app, so everything outside of it will be ignored by Vue.

**Comment by MdAnowarHosen** [comment]
So, @pascalbaljet,  What should I do to make it's work!
