### ISSUE TITLE
[FEATURE REQUEST] Support for Backend Controlled Resources/Component Class like in Laravel Nova/Filament

### ISSUE THREAD

**Issue by uwascan** [protonemedia/laravel-splade#400]
Have you considered adding a Backend controlled Resource/Component Class functionality like you will find in Laravel nova or Laravel Filament to splade?. Splade is super RAD (Rapid Application Development) but still having to create a Controller for most functionality rubs on the RADness of Splade. You may take a look at Airwire for a good idea (https://github.com/archtechx/airwire). I intend to use Splade for an upcoming project and this is how I would love to go about it. Configuration for Splade Forms and Tables can be defined in proposed Resource/Component Class . I will take a stab at this latter when I have the time.

**Comment by pascalbaljet** [comment]
Check out the *Bridge Components*: https://splade.dev/docs/bridge-components

**Comment by uwascan** [comment]
@pascalbaljet Thanks for the link. I am checking it out right away
