### ISSUE TITLE
ErrorException: Undefined property: Illuminate\Routing\Redirector::$headers in SpladeMiddleware.php on line 72

### ISSUE THREAD

**Issue by HUGE-DECK-10-INCHES** [protonemedia/laravel-splade#402]
For some reason I am getting this error:
ErrorException: Undefined property: Illuminate\Routing\Redirector::$headers in SpladeMiddleware.php on line 72

Which is `$response->headers->add(['Vary' => 'X-Splade']);`

**Comment by pascalbaljet** [comment]
Can you share the Controller or Middleware that sends the response?
