### ISSUE TITLE
[ADD TO DOCS] Larapex

### ISSUE THREAD

**Issue by soixt** [protonemedia/laravel-splade#403]
If you decide to use apex charts with larapex package you could focus on usage for vue and then inside blade do this:
https://larapex-charts.netlify.app/6-working-with-inertiajs/
```
<x-splade-data :default="$chart">
    <apexchart :width="data.width" :height="data.height" :type="data.type" :options="data.options" :series="data.series"></apexchart>
</x-splade-data>
```

**Comment by pascalbaljet** [comment]
You can do it even shorter 😉

```blade
<apexchart v-bind="@js($chart)" />
```

**Comment by soixt** [comment]
Keep forgetting about @js() stuff all the time :D I'll make PR for custom icon picker component works with font-awesome-5 I needed it so I'll share if you wish to add it as component?
