### ISSUE TITLE
How to listen on route changes in splade front part?

### ISSUE THREAD

**Issue by soixt** [protonemedia/laravel-splade#408]
I am trying to execute some script on route change but can't figure out how to handle that?

**Comment by pascalbaljet** [comment]
As of v1.4.8, you can listen for these three events:

`splade:history:popped-state`
`splade:history:pushed-state`
`splade:history:replaced-state`

The URL is in the `detail` object of the event:

```js
document.addEventListener("splade:history:pushed-state", ($event) => {
    console.log($event.detail.url);
});
```

Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).

**Comment by soixt** [comment]
is there a list of splade events? or just those 3? thanks
