### ISSUE TITLE
The response is not a Splade response.

### ISSUE THREAD

**Issue by mccarlosen** [protonemedia/laravel-splade#411]
- Laravel Version: 9.52.4
- PHP Version: 8.1.18
- Splade JS Version (npm): 1.4.8
- Splade PHP Version (composer): 1.4.8
- Dev environment (OS, Sail/Valet/etc): Homestead

### Description:

https://user-images.githubusercontent.com/8524361/235379116-ff90a786-c662-438e-9847-a90ac3ac81cf.mp4

### Steps To Reproduce Issue:
```php
// PostsController.php

public function download(Request $request)
{
    $data = $request->all();
    $documentId = $data['document_id'];
    $name = $data['name'];
    if (!$documentId) abort(404);
    $document = Documento::find($documentId);
    if (!$document) abort(404);
    $media = $document->getMedia('documents')->where('name', $name)->first();
    
    return response()->download($media->getPath(), $media->file_name);
    // return response()->file($media->getPath());
    // return response()->streamDownload(function () use ($media) {
    // 	echo file_get_contents($media->getPath());
    // }, $media->file_name);
    // return response()->json(['data' => 'Hello']);
}
```

```vue
<!-- The vue component -->
<Link 
    method="POST"
    :data="{document_id: adj.document_id, name: adj.name}"
    href="/panel/publicaciones/descargar/single-attach"
    class="absolute right-0 top-0 btn-icon bg-color2-200 hover:bg-color2-100 p-2 rounded-bl rounded-tr">
    <svg class="w-4 h-4 fill-color1-500" enable-background="new 0 0 24 24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m12 16c-.205 0-.401-.084-.542-.232l-5.25-5.5c-.455-.476-.117-1.268.542-1.268h2.75v-5.75c0-.689.561-1.25 1.25-1.25h2.5c.689 0 1.25.561 1.25 1.25v5.75h2.75c.659 0 .997.792.542 1.268l-5.25 5.5c-.141.148-.337.232-.542.232z"/><path d="m22.25 22h-20.5c-.965 0-1.75-.785-1.75-1.75v-.5c0-.965.785-1.75 1.75-1.75h20.5c.965 0 1.75.785 1.75 1.75v.5c0 .965-.785 1.75-1.75 1.75z"/></svg>
</Link>
```

I'm not sure if I'm doing something wrong. I've even checked a similar problem  #368, but I can't see the issue. My theory is that the middleware is not capturing this type of response. I've seen that the middleware has been updated to handle this type of response [here](https://github.com/protonemedia/laravel-splade/commit/52801c3ec1708b83e49786c5e5cd9dd870f45a8b) but it's not working for me.

I hope you can help me.

**Comment by mccarlosen** [comment]
I have reviewed the `protone-media-laravel-splade.js` file and I see that the response expects the splade object. However, in the download-type response, this property is not included.

**Comment by HUGE-DECK-10-INCHES** [comment]
For me it wasn't working for response as well but it did work by returning:

`return Storage::disk('public')->download($path);`

**Comment by mccarlosen** [comment]
Thank you for your response. I tried it and it didn't work for me.

```php
// ...
return Storage::disk('media')->download($media->getPathRelativeToRoot(), $media->file_name);
```

**Comment by jamesj2** [comment]
I too have this problem.  I documented a workaround in #399 using a form for options.  It would be awesome if Splade would handle attachments.

**Comment by pascalbaljet** [comment]
I'm aware of this issue and working on a fix! (also for #399)

**Comment by pascalbaljet** [comment]
The Form component now accepts a `blob` attribute as of v1.4.10:

```blade
<x-splade-form blob>
    <button type="submit">Download</button>
</x-splade-form>
```

Make sure to [update both packages](https://splade.dev/docs/upgrading) (JS + PHP).

**Comment by mccarlosen** [comment]
Thanks so much!

**Comment by MdAnowarHosen** [comment]
@pascalbaljet, Thanks
