### ISSUE TITLE
[Question] How can I send a request in vue inside Splade? 

### ISSUE THREAD

**Issue by MikePonce-UwU** [protonemedia/laravel-splade#418]
Hi there, well... what i meant up there is how i can send data through vue inside splade. here is my case:
i´m developing a project where i need to send a list of data, be it scores or user information, so what i want to do is send this gathered info to my data base. the question is if i can do this as it were an api and i should be sending the info thru axios  or is there any way to do this?

**Comment by pascalbaljet** [comment]
Where does the data come from? In most cases, you can just use the [Form component](https://splade.dev/docs/x-form) or create a [Custom component](https://splade.dev/docs/custom-vue-components) and handle the request manually.
