### ISSUE TITLE
Table columns reset visibility if hiding/showing and then sorting

### ISSUE THREAD

**Issue by gbrock** [protonemedia/laravel-splade#420]
- Laravel Version: 10.10.1
- PHP Version: 8.2.5
- Splade JS Version (npm): 1.4.8
- Splade PHP Version (composer): 1.4.8
- Dev environment (OS, Sail/Valet/etc): Docker / Sail default install on MacOS

### Description:

**Columns reappear if hidden and then the table is sorted.**

I don't know enough about Vue yet to track this down, but I suspect the URLs for sorting table columns aren't getting updated regarding shown/hidden columns.

### Steps To Reproduce Issue:

- Default Laravel / Splade installation
- Set up a table to display users:
  ```php
  'users' => \ProtoneMedia\Splade\SpladeTable::for(\App\Models\User::class)
    ->column('name', sortable: true)
    ->column('email')
    ->paginate(15)
- Make sure you have a few users, I used the default 10 seeded users:
  ```console
  php artisan db:seed
  ```
- View the table in the browser
- Turn off the email column by clicking the eye icon and switching off "email"
- Sort table by clicking the "Name" column header
- The email column re-appears

Refreshing the page "hacks" it back to working:
- Hide the email column again
- Refresh the page
- Email column is still hidden because it's in the query string
- Sort by name; the email column continues to stay hidden

**Comment by mbeckerle-xqueue** [comment]
This problem can be fixed, if you append all previous parameters to the url.

Please try this:

```
'users' => \ProtoneMedia\Splade\SpladeTable::for(\App\Models\User::class)
  ->column('name', sortable: true)
  ->column('email')
  ->paginate(15)
  ->appends(request()->query());
```
