### ISSUE TITLE
 Issue with New Feature Jodit WYSIWYG Editor

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#425]
I encountered this while using the new feature introduced in pull request #415 .
The problem arises when using the following component     

             <x-splade-wysiwyg name="description" placeholder="Description" />

The expected behavior should be the appropriate display of the Jodit Editor. However, the output does not correctly show the Jodit Editor as intended.

To provide a visual representation of the issue, I have attached a screenshot of the problematic output. You can view it at the following link:

               
![image](https://github.com/protonemedia/laravel-splade/assets/8742640/51e6df30-e43f-48c7-ba5f-273272d739b5)

- Laravel Version: #.#.#
- PHP Version: #.#.#
- Splade JS Version (npm): #.#.#
- Splade PHP Version (composer): #.#.#
- Dev environment (OS, Sail/Valet/etc): ...

You may use the [built-in Artisan Command](https://splade.dev/docs/upgrading) to show the installed versions of the packages:

```bash
php artisan splade:show-versions
```
![image](https://github.com/protonemedia/laravel-splade/assets/8742640/e47019ba-629b-4cd0-bd5a-053d895c4dfe)

Make sure both Splade packages (JS + PHP) are up-to-date and on the same version. For example, when using version 0.5.0 of the PHP package, you should use the same JavaScript package version.

**Comment by pascalbaljet** [comment]
You need to import the stylesheet. Check out the docs: https://splade.dev/docs/form-wysiwyg

**Comment by ebifurei** [comment]
> You need to import the stylesheet. Check out the docs: https://splade.dev/docs/form-wysiwyg
Hi there,

I'm currently experiencing an issue with the laravel-splade WYSIWYG package. I've followed the documentation provided at https://splade.dev/docs/form-wysiwyg and imported the Jodit stylesheet and i already install jodit via npm. 

However,  it seems like the file "@protonemedia/laravel-splade/dist/jodit.css" is missing. Could you please provide some guidance on how to resolve this issue?
