### ISSUE TITLE
Autofocus only working on first submit

### ISSUE THREAD

**Issue by Blixary** [protonemedia/laravel-splade#439]
Composer (PHP) package version: 1.4.11
NPM (JS) package version: 1.4.11

You may use the [built-in Artisan Command](https://splade.dev/docs/upgrading) to show the installed versions of the packages:

```bash
php artisan splade:show-versions
```

Make sure both Splade packages (JS + PHP) are up-to-date and on the same version. For example, when using version 0.5.0 of the PHP package, you should use the same JavaScript package version.

### Description:

The "autofocus" attribute on text inputs is inducing the autofocus of the input field on the first time loading. After submitting the form, the text field isn't focused any more.

### Steps To Reproduce Issue:

Autofocus attribute on text field.

**Comment by pascalbaljet** [comment]
Do you use the `stay` attribute on the Form element? Or does this occur on a subsequent page?

**Comment by Blixary** [comment]
> Do you use the `stay` attribute on the Form element? Or does this occur on a subsequent page?

The form element uses 'stay reset-on-sucess', the input field the 'autofocus' attribute.
The form is "embed" in a slideover.

**Comment by Blixary** [comment]
Hi @pascalbaljet,

I figured out that removing the 'stay' attribute from the splade-form and using a redirect function on submit is preserving the autofocus. Only problem with that method is, that this interferes with the splade rehydrate component. But for now, this is a solid workaround.
