### ISSUE TITLE
'peer' class - highlight the correspondent checked element

### ISSUE THREAD

**Issue by Adel-Kazem** [protonemedia/laravel-splade#445]
@pascalbaljet can you help?
when the checkbox is checked the correspondent element should be highlighted, such as the label that holds the 'for' attribute should be highlighted with border, usually both elements are connected together by 'peer' class value.
See example [here](https://flowbite.com/docs/forms/checkbox/#advanced-layout)

code I'm working on (try uncommenting the regular input to see how it works):
`@foreach($user->photos as $image)

                    <li>
                        <x-splade-checkbox name="selected_images[]" id="{{$image->id}}" value="{{$image->id}}" class=" peer"/>
                        {{-- <input type="checkbox" name="selected_images[]" id="{{$image->id}}" value="{{$image->id}}" class="absolute w-0 h-0 opacity-0 peer" >--}}
                        <label for="{{$image->id}}" class="inline-flex items-center justify-between w-full p-2 text-gray-500 bg-white border-2 border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 peer-checked:border-blue-600 hover:text-gray-600 dark:peer-checked:text-gray-300 peer-checked:text-gray-600 hover:bg-gray-50 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                            <div class="block">
                                <img src="{{$image->path}}" class=" w-full h-full text-sky-500">
                            </div>
                        </label>
                    </li>

                @endforeach`

Is it possible in SPLADE form components?
thanks.

**Comment by pascalbaljet** [comment]
The `peer` class only works in the checkbox input element is a direct sibling of the `label` element. I would suggest using Vue directives:

```blade
<p v-if="form.selected_images.includes('id')">
    ID is checked
</p>

<p v-bind:class="{ 'text-green-500': form.selected_images.includes('id') }">
    Green if ID is checked
</p>
```
