### ISSUE TITLE
Change localization on flatpickr

### ISSUE THREAD

**Issue by ryahpalma** [protonemedia/laravel-splade#449]
- Laravel Version: 9.19
- PHP Version: 8.1.2
- Splade JS Version (npm): 1.1.0
- Splade PHP Version (composer): 1.2
- Dev environment (OS, Sail/Valet/etc): Windows 10, Valet

### Description:

I want to change the language of date like official flatpickr doc says:

```
import flatpickr from "flatpickr"
import { Portuguese } from "flatpickr/dist/l10n/pt.js"

flatpickr(myElem, {
    "locale": Portuguese // locale for this instance only
});
```

How can I set it on x-splade-input? it can be by instance or global...

### Steps To Reproduce Issue:

It's not an issue.

**Comment by pascalbaljet** [comment]
Try this in the main `app.js` file:

```js
import flatpickr from "flatpickr";
import { Portuguese } from "flatpickr/dist/l10n/pt.js"
flatpickr.localize(Portuguese);
```

**Comment by ryahpalma** [comment]
Works like a charm! Thanks a lot @pascalbaljet.
