### ISSUE TITLE
The root view is not rendered in Laravel's custom error pages

### ISSUE THREAD

**Issue by thecyrilcril** [protonemedia/laravel-splade#457]
- Laravel Version: 10.13.5
- PHP Version: 8.1.13
- Splade JS Version (npm): 1.4.14
- Splade PHP Version (composer): 1.4.14
- Dev environment (OS, Sail/Valet/etc): Windows 10 Pro.

### Description:

When creating custom error pages the root view is not rendered into the error page.

### Steps To Reproduce Issue:

1. Create a 404.blade.php file inside the errors directory within the views directory

2. Add the following to the page
```
<x-guest-layout>
    <h3 class="text-7xl font-semibold">404</h3>
</x-guest-layout>
```
3. Visit a page that is not registered on your routes file

### Result
The roots view is missing, so the layout is broken

**Comment by thecyrilcril** [comment]
@pascalbaljet I think some logic within ```\ProtoneMedia\Splade\SpladeCore::exceptionHandler()```  prevents the root view from being rendered within the custom error pages. 
*Note:* I am not sure of what I am saying

**Comment by jamesj2** [comment]
What I did was add the contents of root.blade.php inside a laravel blade layout and call that from the 404.blade.php.

```blade
// errors/404.blade.php
<x-layout.httperror>
  <h3 class="text-7xl font-semibold">404</h3>
</x-layout.httperror>
```

```blade
// components/layout/httperror.blade.php
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta property="csp-nonce" content="{{ csp_nonce() }}">
   ...
   @vite(['resources/css/app.scss', 'resources/js/app.js'])
</head>
<body>
    {{ $slot }}
</body>
</html>
```

**Comment by thecyrilcril** [comment]
> What I did was add the contents of root.blade.php inside a laravel blade layout and call that from the 404.blade.php.
> 
> ```
> // errors/404.blade.php
> <x-layout.httperror>
>   <h3 class="text-7xl font-semibold">404</h3>
> </x-layout.httperror>
> ```
> 
> ```
> // components/layout/httperror.blade.php
> <!DOCTYPE html>
> <head>
>     <meta charset="utf-8">
>     <meta name="csrf-token" content="{{ csrf_token() }}">
>     <meta property="csp-nonce" content="{{ csp_nonce() }}">
>    ...
>    @vite(['resources/css/app.scss', 'resources/js/app.js'])
> </head>
> <body>
>     {{ $slot }}
> </body>
> </html>
> ```

@jamesj2 Thanks but this approach strips all the error pages of all laravel-splade behavior and leaves just a layout shell.
What I am going for is to display the error page like it's part of the web app, while still having the full power of splade.

**Comment by jamesj2** [comment]
@thecyrilcril You're right.  I did forget the @splade directive in the body but it still doesn't work.  I used my solution mainly for the automatic page refresh via Vite.  Even if you add the @splade directive it won't put your slot inside the Splade initialization.  Might I suggest redirecting to another page with a proper controller from the error view?

**Comment by thecyrilcril** [comment]
> Might I suggest redirecting to another page with a proper controller from the error view?

how would I do that?

**Comment by thecyrilcril** [comment]
Custom Exceptions pages can be rendered as described in the **Exception handling** section of the [Splade Documentation](https://splade.dev/docs/exception-handling).

Mine looks like this:
```
    public function register(): void
    {
        $this->renderable(\ProtoneMedia\Splade\SpladeCore::exceptionHandler($this, function(Throwable $exception, Request $request) : RedirectResponse {

            if ($exception instanceof HttpException && $exception->getStatusCode() === 403) {
                return to_route('errors:403');
            }

            if ($exception instanceof HttpException && $exception->getStatusCode() === 404) {
                return to_route('errors:404');
            }
        }));

        $this->reportable(function (Throwable $e): void {

        });
    }
```
