### ISSUE TITLE
Views not render locales and translations

### ISSUE THREAD

**Issue by Noraitec** [protonemedia/laravel-splade#459]
- Laravel Version: v10.13.5
- PHP Version: 8.1.10
- Splade JS Version (npm): 8.19.2
- Splade PHP Version (composer): 1.4
- Dev environment (OS, Sail/Valet/etc): Ubuntu 22.04.2 LTS x86_64
- Composer (PHP) package version: 1.4.14
NPM (JS) package version: 1.4.14

I have used the command "php artisan lang:publish" and in /config/app.php, I have configured 'locale' => 'es'.

Then, I created a file in the lang directory called frontend.php.

I navigate to the welcome.blade.php view and enter a text {{__(frontend.example)}}. However, the languages are not rendered in the view, and it shows "frontend.example" as rendered.

Is there any configuration setting to render the languages in Blade before creating the component?

**Comment by pascalbaljet** [comment]
This seems like a generic Laravel issue, not Splade related. Could you try executing `__('frontend.example')` in [Tinker](https://laravel.com/docs/10.x/artisan)?
