### ISSUE TITLE
Attribute choices not working on form component

### ISSUE THREAD

**Issue by thecyrilcril** [protonemedia/laravel-splade#474]
- Laravel Version: 10.14.1
- PHP Version: 8.1.13
- Splade JS Version (npm): 1.4.15
- Splade PHP Version (composer): 1.4.15.1
- Dev environment (OS, Sail/Valet/etc): ...

Make sure both Splade packages (JS + PHP) are up-to-date and on the same version. For example, when using version 0.5.0 of the PHP package, you should use the same JavaScript package version.

### Description:
```
<x-splade-form action="{{ route('admin:create-shipment') }}">

                @php
                $countries= [
                    'NG' => 'Nigeria',
                    'CN' => 'China'
                ];
                @endphp
                <x-splade-select name="country_code"
                    label="Select your country"
                    :options="$countries"
                    choices
                />
</x-splade-form>
```
The above does not work and renders

```
<select name="country_code" data-validation-key="country_code" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 disabled:opacity-50 choices__input" hidden="" tabindex="-1" data-choice="active"><option value="" data-custom-properties="[object Object]"></option></select>
```

**Comment by jamesj2** [comment]
Your code worked for me using the [example app](https://splade.dev/docs/automatic-installation).

**Comment by thecyrilcril** [comment]
@jamesj2 Starting a new project using https://splade.dev/docs/breeze works for me too but on the existing project

**Comment by thecyrilcril** [comment]
@jamesj2 ```@click.stop="closeMobileMenu"``` on the whole layout from [Issue #474](https://github.com/protonemedia/laravel-splade/issues/448) was the culprit, it stops the propagation of click events on the whole layout thereby stopping that of choices too
