### ISSUE TITLE
Fail to catch error from eloquent

### ISSUE THREAD

**Issue by davitlee88** [protonemedia/laravel-splade#48]
### found error when no data in database
tried using eloquent and DB Query
with findOrFail and where('id', $id)
error when using postgress with schema

![image](https://user-images.githubusercontent.com/11909608/191340607-c4253c53-1d2a-4f22-bc5b-c33c63e964ca.png)

**Comment by pascalbaljet** [comment]
This seems more like a generic Laravel error than a specific Splade error. But to be sure, can you share some more code so I can reproduce the error?

**Comment by davitlee88** [comment]
After re-checking for the function confirmed that this is error from laravel
and just happen in postgress database with scheme.
I handle this issue using try and catch exception.

**Comment by pascalbaljet** [comment]
Glad you solved it! And thank you for your sponsorship! ❤️
