### ISSUE TITLE
Question: how to prevent the dynamic Remote URL from making ajax calls on page load

### ISSUE THREAD

**Issue by thecyrilcril** [protonemedia/laravel-splade#482]
- Laravel Version: 10.15.0
- PHP Version: 8.1.13
- Splade JS Version (npm): 1.4.15
- Splade PHP Version (composer): 1.4.15.1
- Dev environment (OS, Sail/Valet/etc): Window 10 Pro. / WAMP

### Description:

I have this setup
```
                <x-splade-select name="country_code"
                    label="Select your country"
                    :options="$countries"
                    placeholder="Select your country..."
                    choices
                />
                
               <x-splade-select name="city_name"
                    label="Select your city"
                    remote-url="`/country/cities/${form.country_code}`"
                    placeholder="Select your city..."
                    choices
                    reset-on-new-remote-url
                />
```
I will like to prevent the select component with the ```remote-url``` attribute from making an ajax call before the country_code is changed. for now it makes a call as soon as the page is loaded.

**Comment by J87NL** [comment]
I noticed the same, an option to not call the remote-url as long as the `${form.country_code}` is empty could be nice.

**Comment by jamesj2** [comment]
@thecyrilcril I'm wondering if you've looked into the [Lazy](https://splade.dev/docs/lazy-loading#app) component in Splade?  I don't have any experience with it.  But it does have a conditional load option.

**Comment by thecyrilcril** [comment]
@pascalbaljet @J87NL a simpler approach - the ```city_name``` is updated with the search term which is in turn appended to the ```remote-url``` attribute as a query string
```
               <x-splade-select name="city_name"
                    @search="form.city_name=$event.detail.value
                    label="Select your city"
                    remote-url="`/country/cities/${form.country_code}?search=${form.city_name}`"
                    placeholder="Select your city..."
                    choices
                    select-first-remote-option
                />
```
Unfortunately, the experience is terrible as ```xhr``` request are fired off on every keystroke. @pascalbaljet  is there a way to debounce this?

**Comment by thecyrilcril** [comment]
> @thecyrilcril I'm wondering if you've looked into the [Lazy](https://splade.dev/docs/lazy-loading#app) component in Splade? I don't have any experience with it. But it does have a conditional load option.

I have checked it a bit, can't see how it applies to my situation. thanks

**Comment by jamesj2** [comment]
@thecyrilcril I played around with the Lazy component and got it to mostly work but I wasn't able to access the form object.  Then I tried using the Data component and I got it working.  Choices will not load on page load because the url is initially empty.

```blade
<x-splade-data default="{remote_url: ''}">
    <x-splade-form>
        <x-splade-select name="country_code"
                         label="Select your country"
                         :options="$countries"
                         placeholder="Select your country..."
                         choices
                         @change="data.remote_url = '/country/cities/' + $event.target.value"
        />
        <x-splade-select name="city_name"
                         label="Select your city"
                         remote-url="`${data.remote_url}`"
                         placeholder="Select your city..."
                         choices
                         reset-on-new-remote-url
        />
    </x-splade-form>
</x-splade-data>
```

**Comment by thecyrilcril** [comment]
> @thecyrilcril I played around with the Lazy component and got it to mostly work but I wasn't able to access the form object.  Then I tried using the Data component and I got it working.  Choices will not load on page load because the url is initially empty.
> 
> ```blade
> <x-splade-data default="{remote_url: ''}">
>     <x-splade-form>
>         <x-splade-select name="country_code"
>                          label="Select your country"
>                          :options="$countries"
>                          placeholder="Select your country..."
>                          choices
>                          @change="data.remote_url = '/country/cities/' + $event.target.value"
>         />
>         <x-splade-select name="city_name"
>                          label="Select your city"
>                          remote-url="`${data.remote_url}`"
>                          placeholder="Select your city..."
>                          choices
>                          reset-on-new-remote-url
>         />
>     </x-splade-form>
> </x-splade-data>
> ```

My use case has changed from when I askee the question.

I now only want to load cities that match the search term instead of loading all the cities as choices and the browser have trouble loading that much options without freezing(Ex. 19000+ cities in the US)

I will look take a look, thanks

**Comment by thecyrilcril** [comment]
> @J87NL

I think this approach will really work for you. like I mentioned earlier my situation needs a debounce function 
so it's not firing off Ajax request on every input.

Has anyone figured out how to debounce an event within the ```x-splade-form``` component?

**Comment by jamesj2** [comment]
@thecyrilcril I was looking at the docs today and see there is already an option for your initial issue.  Please try the [select-first-remote-option](https://splade.dev/docs/form-select).  Also you can control how many results you get back with the choices attribute, check the [choices](https://github.com/Choices-js/Choices) documentation.

```blade
<x-splade-select name="region" remote-url="`/api/regions/${form.country}`" reset-on-new-remote-url select-first-remote-option choices={ searchResultLimit: 5}/>
```
