### ISSUE TITLE
How to listen to SPLADE input change and then manipulate the DOM inside the page? Is it possible and how?

### ISSUE THREAD

**Issue by Adel-Kazem** [protonemedia/laravel-splade#483]
Hello @pascalbaljet  I want to use the following input as an example:
```
<x-splade-group name="theme_head" label="Theme Head" inline>
     <x-splade-radio name="theme_head" value="0" label="Theme Head 0"/>
      <x-splade-radio name="theme_head" value="1" label="Theme Head 1"/>
  </x-splade-group>
```

and if the value is = 1 then I want to change the font-family for a certain element on the page. Is this possible?

I have already built an app that uses the jQuery that does the exact functionality, I have also successfully added the jQuery into SPLADE project and I am able to use it but I couldn't use it inside the SPLADE form inputs because either it's not possible or I don't know how to.

thank you.

**Comment by bahramzade** [comment]
fix?
