### ISSUE TITLE
Splade Input Errors based on Label attribute

### ISSUE THREAD

**Issue by SebRothIFB** [protonemedia/laravel-splade#491]
- Laravel Version: 10.15.0
- PHP Version: 8.1.10
- Splade JS Version (npm): 1.4.15
- Splade PHP Version (composer): 1.4.15.1

### Description:

Is there a way to show validation errors based on Label attribute in x-splade-input?

`<x-splade-group inline>
                            <x-splade-input name="individualPosition" label="individual position" />
                            <x-splade-input name="BookingNumber" label="Booking number*" />
                            <x-splade-select name="FCL_LCL" label="FCL or LCL? *" :options="[1 => 'FCL', 2 => 'LCL']" choices />
</x-splade-group>`

![image](https://github.com/protonemedia/laravel-splade/assets/63638852/606508c3-6068-4a2f-a432-34d119d02c05)

**Comment by thecyrilcril** [comment]
@SebRothIFB do you mean use the label value ```FCL or LCL``` in the returned error message?

If that's what you want you would do that on the backend. you could create a form request with an attributes method like below:

```
    public function attributes()
    {
        return [
            ...
            'FCL_LCL' => 'FCL or LCL',

        ];
    }
```
You error message will return "The FLC or LCL field is required"
Hopefully that what you wanted.
