### ISSUE TITLE
value assigned to x-splade-input from x-splade-script gets ignored as form saved.

### ISSUE THREAD

**Issue by samk1r0** [protonemedia/laravel-splade#499]
- Laravel Version: 10.18.0
- PHP Version: 8.1.11
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.16
- Dev environment (OS, Sail/Valet/etc): Windows

I'm assigning a value to x-splade-input element in x-splade-script. The problem appears as I save the form, at this moment data get's updated with the initial value. However If i change the input manually(by clicking on the input field and modifying value) it doesn't set the value to the inital value.

**Comment by pascalbaljet** [comment]
Please share your script.

**Comment by samk1r0** [comment]
<section>
    <x-splade-form method="patch" :action="route('widget.update')" :default="$user" class="mt-6 space-y-6" preserve-scroll>
        <h3 class="text-white">Jingle</h3>
        <div class="flex sm:items-center flex-col sm:flex-row" style="margin-top: 0;">
            <x-splade-file id="jingle_file" name="jingle" accept="audio/mp3"></x-splade-file>
        </div>   
        <x-splade-input id="duration" name="duration"></x-splade-input>
        <div class="flex items-center gap-4">
            <x-splade-submit :label="__('Save')" />

            @if (session('status') === 'gif-updated')
                <p class="text-sm text-white">
                    {{ __('Saved.') }}
                </p>
            @endif
        </div>
    </x-splade-form>
</section>
<x-splade-script>   
    let audio = document.createElement('audio');
    let alertDuration = document.getElementById('duration');
    const inputElement = document.getElementById("jingle_file");
    inputElement.addEventListener("change", (event) => {
        var target = event.currentTarget;
        var file = target.files[0];
        var reader = new FileReader();
        if (target.files && file) {
            var reader = new FileReader();

            reader.onload = function (e) {
                audio.src = e.target.result;
                audio.addEventListener('loadedmetadata', function(){
                    alertDuration.value = audio.duration;
                });
            };
        }
        reader.readAsDataURL(file);
    });

</x-splade-script>

**Comment by samk1r0** [comment]
```
<section>
    <div class="flex">
    </div>
    <x-splade-form method="patch" :action="route('widget.update')" :default="$user" class="mt-6 space-y-6" preserve-scroll>
        <h3 class="text-white">Jingle</h3>
        <div class="flex sm:items-center flex-col sm:flex-row" style="margin-top: 0;">
            <x-splade-file id="jingle_file" name="jingle" accept="audio/mp3"></x-splade-file>
        </div>   
        <x-splade-input id="duration" name="duration"></x-splade-input>
        <div class="flex items-center gap-4">
            <x-splade-submit :label="__('Save')" />

            @if (session('status') === 'gif-updated')
                <p class="text-sm text-white">
                    {{ __('Saved.') }}
                </p>
            @endif
        </div>
    </x-splade-form>
</section>
<x-splade-script>   
    let audio = document.createElement('audio');
    let alertDuration = document.getElementById('duration');
    const inputElement = document.getElementById("jingle_file");
    inputElement.addEventListener("change", (event) => {
        var target = event.currentTarget;
        var file = target.files[0];
        var reader = new FileReader();
        if (target.files && file) {
            var reader = new FileReader();

            reader.onload = function (e) {
                audio.src = e.target.result;
                audio.addEventListener('loadedmetadata', function(){
                    alertDuration.value = audio.duration;
                });
            };
        }
        reader.readAsDataURL(file);
    });

</x-splade-script>
```

**Comment by samk1r0** [comment]
@pascalbaljet So do you know what's the reason for this problem?

**Comment by romain-lgr** [comment]
@samk1r0  `duration` should be a field of your User model and then predefined. Your code is quite strange, not sure what you want to achieve.

**Comment by samk1r0** [comment]
@romain-lgr but what if I don't have duration column in my users table and I only want to use this field for calculation purposes?

**Comment by jadetulda1996** [comment]
> @romain-lgr but what if I don't have duration column in my users table and I only want to use this field for calculation purposes? Also, what you find strange in my code?

After the `alertDuration.value = 123;` line, write the ff.
`alertDuration.dispatchEvent(new Event('input'))`

PS: I can't reference the link, I forgot where did I got the idea xx)

**Comment by samk1r0** [comment]
> > @romain-lgr but what if I don't have duration column in my users table and I only want to use this field for calculation purposes? Also, what you find strange in my code?
> 
> After the `alertDuration.value = 123;` line, write the ff. `alertDuration.dispatchEvent(new Event('input'))`
> 
> PS: I can't reference the link, I forgot where did I got the idea xx)

what's ff?

**Comment by jadetulda1996** [comment]
> > > @romain-lgr but what if I don't have duration column in my users table and I only want to use this field for calculation purposes? Also, what you find strange in my code?
> > 
> > 
> > After the `alertDuration.value = 123;` line, write the ff. `alertDuration.dispatchEvent(new Event('input'))`
> > PS: I can't reference the link, I forgot where did I got the idea xx)
> 
> what's ff?

only means "following"..

"write the following"
