### ISSUE TITLE
Vue Warning from tables since upgrading to 1.4.16

### ISSUE THREAD

**Issue by mobreviews** [protonemedia/laravel-splade#502]
- Laravel Version: 10.19.0
- PHP Version: 8.1.17
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.16
- Dev environment (OS, Sail/Valet/etc): Docker container using Alpine Linux

### Description:

Since upgrading to version 1.4.16 all of my splade tables are throwing 2 Vue Warning messages in the console.

1.  [Vue warn]: Extraneous non-props attributes (style) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 

2. [Vue warn]: Missing required prop: "spladeId"

**Comment by EmilMoe** [comment]
I don't think these are from your tables, I think this is from banner.blade.php. I removed `<x-banner />` for that reason.

**Comment by ifathurrohman** [comment]
> * Laravel Version: 10.19.0
> * PHP Version: 8.1.17
> * Splade JS Version (npm): 1.4.16
> * Splade PHP Version (composer): 1.4.16
> * Dev environment (OS, Sail/Valet/etc): Docker container using Alpine Linux
> 
> ### Description:
> Since upgrading to version 1.4.16 all of my splade tables are throwing 2 Vue Warning messages in the console.
> 
> 1. [Vue warn]: Extraneous non-props attributes (style) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
> 2. [Vue warn]: Missing required prop: "spladeId"

Same with me, where <x-banner /> location ?

**Comment by pascalbaljet** [comment]
Unable to reproduce without a code example. I couldn't find any warning in the example app.
