### ISSUE TITLE
<Link method="POST" modal> performs a GET request

### ISSUE THREAD

**Issue by dusp2k** [protonemedia/laravel-splade#504]
- Laravel Version: 10
- PHP Version: 8.2
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.15.1
- Dev environment (OS, Sail/Valet/etc): Windows

Any reason why this doesn't work? If I use the 'modal' attribute on &lt;Link&gt; it reverts back to being a GET request. It doesn't matter which method is used (POST, DELETE, PUT etc.)

```
<Link method="DELETE" href="{{ route('some_controller_name.destroy', $modelToDestroy) }}" modal confirm preserve-scroll>
	{{ __('Delete') }}
</Link>
```

**Comment by thecyrilcril** [comment]
@dusp2k I guess modal should open something or resource, that how I use it.
What are you trying to do?
From your code, it seems you are trying to delete a model. Why do you need a modal for that?

I assume you meant to use ```confirm``` instead of a modal.
If you are trying to warn the user or confirm the action before deletion, then confirm is what you should use, and not modal

**Comment by dusp2k** [comment]
I'm showing a SpladeTable in a modal with an option to delete rows. After deletion I want to stay in the modal, so I need to set the modal attrtibute. Else I'm redirected back to a full-page version of the list.

Shouldn't the functionalitity of the Link method attribute be te same regardless if I use modal or not?

**Comment by thecyrilcril** [comment]
hmm...I see maybe @pascalbaljet could help.

**Comment by dusp2k** [comment]
Update: There is this ```keep-modal``` attribute which does what I want. It keeps open the modal after the request.

```
<Link method="DELETE" href="{{ route('some_controller_name.destroy', $modelToDestroy) }}" keep-modal confirm preserve-scroll>
	{{ __('Delete') }}
</Link>
```

**Comment by pascalbaljet** [comment]
Modals are always a `GET` request.
