### ISSUE TITLE
Question: How do I speed up a huge component?

### ISSUE THREAD

**Issue by thecyrilcril** [protonemedia/laravel-splade#511]
- Laravel Version: 10.20.0
- PHP Version: 8.1.13
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.16
- Dev environment (OS, Sail/Valet/etc): Windows 10 Pro.

### Description:

I have a spade form component that can grow from at leat 32 fields to 100 or more fields.
loading the page extremely slow, it freezes for about 5 seconds glitches.

How can I speed up this page up, prevent the freezing and glitches.

[https://youtu.be/uaPSBOPuOoE](https://youtu.be/uaPSBOPuOoE)

**Comment by pascalbaljet** [comment]
Impossible to answer without a code example.
