### ISSUE TITLE
Question: Is there a way to have toasts render HTML

### ISSUE THREAD

**Issue by thecyrilcril** [protonemedia/laravel-splade#515]
- Laravel Version: 10.20.0
- PHP Version: 8.1.13
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.16
- Dev environment (OS, Sail/Valet/etc): Windows/WAMP 

### Description:

I would like to put some html into some toasts.

### Steps To Reproduce Issue:

For example, passing a link tag as part of the contents of  ```Splade::toastOnEvent()``` to allow users navigate to an appropriate url

**Comment by pascalbaljet** [comment]
Fixed in v1.4.19
