### ISSUE TITLE
Question: How to use the ClickOutside component

### ISSUE THREAD

**Issue by thecyrilcril** [protonemedia/laravel-splade#519]
- Laravel Version: 10.20.0
- PHP Version: 8.1.13
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.16
- Dev environment (OS, Sail/Valet/etc): Windows 10 Pro./WAMP

You may use the [built-in Artisan Command](https://splade.dev/docs/upgrading) to show the installed versions of the packages:

```bash
php artisan splade:show-versions
```

### Description:

It tried to use the clickoutside component  like so
```
<x-splade-outside do="() => data.open = false" opened="true">
...
</x-splade-outside>
```
but could not get it to work

**Comment by pascalbaljet** [comment]
The `outside` component is undocumented, only meant for internal use, and unsupported.

Maybe try `onClickOutside` from VueUse (https://vueuse.org/core/onClickOutside/)
