### ISSUE TITLE
Unable to integrate Daisy UI into a new Laravel/Splade project - important

### ISSUE THREAD

**Issue by Adel-Kazem** [protonemedia/laravel-splade#526]
I am trying to use Daisy UI components inside SPLADE but the ones that has movement functionality such as 'accordion' or ' countdown'..etc. Doesn't work. I have tried to use it on a fresh laravel Project and it worked fine but when I use it within SPLADE it doesn't work.

[daisyUI install](https://daisyui.com/docs/install/)

@pascalbaljet Please help me resolving this issue because I decided to build my app upon SPLADE + [daisyUI](https://daisyui.com/) 

thank you.

**Comment by ahmadzissa** [comment]
+ same issue here

**Comment by fabiorcamargo** [comment]
Hello Everyone, maybe this is not the case for you but I had recent problems using Livewire in NGINX, as the library is incorporated into several packages it may be related.

I solved it by adapting the model available in the Laravel documentation.
https://laravel.com/docs/10.x/deployment#nginx

**Comment by pascalbaljet** [comment]
Please reopen the issue with steps to reproduce.
