### ISSUE TITLE
Error when input name starts with digit

### ISSUE THREAD

**Issue by evici** [protonemedia/laravel-splade#529]
- Laravel Version: 10.28.0
- PHP Version: 8.2.11
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.16
- Dev environment (OS, Sail/Valet/etc): nginx (Herd/Valet)

### Description:

Page rendering breaks when splade-input name starts with a digit. It only breaks if name starts with a digit. No problem if contains or ends with a digit.

```console
app.js:26 [Vue warn]: Template compilation error: Error parsing JavaScript expression: Invalid or unexpected token
2074|      :flatpickr="false"
2075|      :js-flatpickr-options="{}"
2076|      v-model="form.3d_url2"
   |               ^^^^^^^^^^^^
2077|      #default="inputScope"
2078|  > 
```

### Steps To Reproduce Issue:

```blade
<x-splade-input name="3d_url" label="3D url" />
```

**Comment by dusp2k** [comment]
This is javascript related. Object properties using dot notation can not start with a number. 

Use bracket syntax: ```v-model="form['3d_url2']"```
