### ISSUE TITLE
Missing og:description

### ISSUE THREAD

**Issue by meetwithchuks** [protonemedia/laravel-splade#535]
- Laravel Version: 10.20.0
- PHP Version: 8.2.12
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.16

### Description:

og:description is not available. 
Can have something like: SEO::openGraphDescription('This is the home page of my application'); ?

**Comment by pascalbaljet** [comment]
`ProtoneMedia\Splade\Head` is macroable, so you could add your custom method:

```php
Head::macro('openGraphDescription', function($value) {
    $this->metaByProperty('og:description', $value);
});
```
