### ISSUE TITLE
Laravel Splade jquery code not work untill reload whole page

### ISSUE THREAD

**Issue by Gash2017** [protonemedia/laravel-splade#541]
hi
i have a laravel splade project
i use laravel 10
php 8.1

i add custom jquery code to my laravel blade

when i open this blade view from dashboard
the js code dont work
but when i reload the whole page
the js code works
what can i do?

**Comment by Gash2017** [comment]
any help pkz ?

**Comment by zyyko** [comment]
I am experiencing the same issue,  my script doesn't work until I reload the page. Have you found any solutions?

**Comment by MdAnowarHosen** [comment]
@pascalbaljet
