### ISSUE TITLE
Component Specific Javascript Dependencies

### ISSUE THREAD

**Issue by KimGrimm** [protonemedia/laravel-splade#545]
- Laravel Version: 10.39.0
- PHP Version: 8.2.13
- Splade JS Version (npm): 1.4.8
- Splade Breeze PHP Version (composer): 2.5.1
- Dev environment (OS, Sail/Valet/etc): Linux & Windows
Make sure both Splade packages (JS + PHP) are up-to-date and on the same version. For example, when using version 0.5.0 of the PHP package, you should use the same JavaScript package version.

### Description:

It seem's to me that we don't have a good and easy way to load custom javascript Dependencies for every page specific. What i've found in the internet is always a sneak-around solution and doesn't feel great, if it's even working..

What I mean get's clear when you think of a theme with multiple pages. Every Page has some charts and statistics on it. The theme provides 3rd-Party-Libraries for that and uses it in the demo files of the theme. So far so good. But when i swap it from basic HTML to Splade it contains page-specific javascript dependencies which don't get "re-loaded" or "re-initialized" during the seamlease pageload of splade.

The script component doesn't provide any feature for external scripts i just want to embed into the specific page. Sadly there is no "default scripts" or something where we could simply pass an array of script-href's to the view method in the controller which are provided with the template of the splade component and them being rendered after the template is mounted.

Do i make sens in someway?
Please be kind. I am a newbie to splade but i love it so far. This is my only error it seems i cant solve.

**Comment by dwicahyo1512** [comment]
same problem @pascalbaljet

**Comment by bardolf69** [comment]
try including the javascript in a <x-splade-script></x-splade-script> block. https://splade.dev/docs/x-script

**Comment by pascalbaljet** [comment]
Please reopen the issue with steps to reproduce.
