### ISSUE TITLE
<x-splade-input> value tag will be ignored and is empty

### ISSUE THREAD

**Issue by Lioxen** [protonemedia/laravel-splade#547]
- Laravel Version: 10.41.0
- PHP Version: PHP v8.1.2-1ubuntu2.14
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.16
- Dev environment (OS, Sail/Valet/etc): Linux Mint 21.3 Cinnamon

### Steps To Reproduce Issue:

Just build a form and try to get an value of a hidden field back... e.g.
`<x-splade-input type="hidden" name="testhidden" value="testit" />`

If you hit submit, the value is empty for this field.... I expect to get testit back

**Comment by pascalbaljet** [comment]
You need add it to the default form data.
