### ISSUE TITLE
The script is not working until I reload the page

### ISSUE THREAD

**Issue by zyyko** [protonemedia/laravel-splade#552]
- Laravel Version: 10
- PHP Version: 8.2.0
- Splade JS Version (npm): 1.4.16
- Splade PHP Version (composer): 1.4.16

I am experiencing an issue where my script does not function until the page is manually reloaded. This issue arises when utilizing certain CDNs for chart functionality.

Additionally, a warning appears in the console: 'chunk-YGMWQZVL.js?v=5c022d98:1577 [Vue warn]: Template compilation error: Tags with side effect (<script> and <style>) are ignored in client component templates.' This occurs at line 110 in the code: '</div>.

Thanks in advance

**Comment by pascalbaljet** [comment]
Unable to debug without a code example.
