### ISSUE TITLE
Debounce on search input field

### ISSUE THREAD

**Issue by davitlee88** [protonemedia/laravel-splade#57]
## Search input debounce time
can we set debounce time for search input?

**Comment by pascalbaljet** [comment]
It's currently [fixed to 350ms](https://github.com/protonemedia/laravel-splade/blob/d96328ca942ed10019ed8939fabb8244a7a4777f/lib/Components/Table.vue#L179-L184), but I'll check out if there's a way to make it configurable. Just out of curiosity, what's the desired value?

**Comment by davitlee88** [comment]
Maybe 500ms to 800ms, and maybe we can make it disabled when data is loading to prevent users input new value

**Comment by pascalbaljet** [comment]
As of v0.5.9, you may now set the debounce time:

```blade
<x-splade-table search-debounce="800" />
```

Or you may set it globally:

```php
SpladeTable::defaultSearchDebounce(800);
```

I've tried to freeze the input elements while the data was loading, but it results in a weird user experience.

**Comment by AliasSuperman** [comment]
My users complain about the user experience. And I've tried setting debounce to both 350 and 800 for them.

Is there any way to rather have the user press ENTER when finished searching?
 
 `<x-splade-table :for="$articles" search-debounce="750" striped>`
