### ISSUE TITLE
How to call JS functions?

### ISSUE THREAD

**Issue by deligoez** [protonemedia/laravel-splade#64]
Is it possible to call a JS (windows) function from a blade component.

It seems like anything in a `script` tag causing an `template compilation error: Tags with side effect (<script> and <style>) are ignored in client component templates` errors

**Comment by pascalbaljet** [comment]
I think you need to add/import the function to the main `app.js` file, or use a [custom Vue component](https://splade.dev/docs/custom-vue-components). Can you share some example code, and the function you want to call?

**Comment by deligoez** [comment]
all clear, there was no `Vue components and libraries` section before in the documentation. thanks Pascal.

**Comment by pascalbaljet** [comment]
You're welcome! I added the docs that morning :)
