### ISSUE TITLE
Fill checkboxes from default-values

### ISSUE THREAD

**Issue by JapSeyz** [protonemedia/laravel-splade#68]
Hi,

I'm testing out Splade, and it seems the checkboxes doesn't auto-check based on the `:default` provided to the form.

Nor can I programatically select it with a `checked` prop.

What am I doing wrong?

```php
<x-splade-form :action="route('house.update', $house)" :default="$house" class="space-y-4">
    <x-splade-group>
        <x-splade-checkbox name="pool" label="Pool" />
        <x-splade-checkbox name="fenced_in" label="Fenced in" />
        <x-splade-checkbox name="pets_allowed" label="Pets allowed" />
    </x-splade-group>
</x-splade-form>
```

I've `dd'ed` out `$house` to ensure that `pool`, `fenced_in` and `pets_allowed` are in the model, and equal to `1`, however the checkboxes still seem to be unchecked.

**Comment by pascalbaljet** [comment]
Thanks for reporting. I'll take a look at it!

**Comment by pascalbaljet** [comment]
Can confirm, working on a fix!

**Comment by JapSeyz** [comment]
Sweet, it works!

**Comment by HUGE-D1CK-10-INCHES** [comment]
Maybe add this to the docs as well 🗡️
