### ISSUE TITLE
Modal or SlideOver on RowLink, how do I work to fun with this?

### ISSUE THREAD

**Issue by dfikeda** [protonemedia/laravel-splade#71]
Hello! Hey, sorry about my english. 
I am extremely confident in this new tool, which is much more flexible than other more popular ones out there. Thanks for your contribution! Despite not being so good, I will try to bring my difficulties and particularities about using the tool here for you.
I believe that the title itself already brings what I need, I know I can implement it in `@cell`, but... I wish there was this option for the whole line.

**Comment by pascalbaljet** [comment]
Hey, don't worry about your English :)

It's a good point. I'll add it soon as a feature!

**Comment by pascalbaljet** [comment]
Fixed in v0.6.0. You may now use `rowModal()` and `rowSlideover()`.

https://splade.dev/docs/table-query-builder

**Comment by dfikeda** [comment]
Thanks Pascal! You're awesome!
