### ISSUE TITLE
Component select with choice.js enabled not work in modal

### ISSUE THREAD

**Issue by davitlee88** [protonemedia/laravel-splade#74]
Choice.js do not when the view call in modal.

**Comment by pascalbaljet** [comment]
Can confirm, the Headless UI Modal blocks the event handler on the Choices.js instance:
https://github.com/tailwindlabs/headlessui/issues/1480

I've got a workaround, which will be included in the next release :)

**Comment by pascalbaljet** [comment]
Fixed in v0.6.0.
