### ISSUE TITLE
Update x-splade-input when other form is changed

### ISSUE THREAD

**Issue by davitlee88** [protonemedia/laravel-splade#75]
![Screenshot splade onchange input update](https://user-images.githubusercontent.com/11909608/195769963-0b621db0-6455-490b-97d9-3357abe228c2.png)
can we do onchange event in input? to update others input value?

**Comment by pascalbaljet** [comment]
Not tested, but I think this should work:

```blade
<x-splade-form>
    <x-splade-input name="quantity" v-on:change="form.total = form.quantity * form.price" />
    <x-splade-input name="price" v-on:change="form.total = form.quantity * form.price" />
    <x-splade-input name="total" />
</x-splade-form>
```

Or:

```blade
<x-splade-form>
    <x-splade-input name="quantity" v-on:change="form.$put('total', form.quantity * form.price)" />
    <x-splade-input name="price" v-on:change="form.$put('total', form.quantity * form.price)" />
    <x-splade-input name="total" />
</x-splade-form>
```

**Comment by davitlee88** [comment]
Cool, 2 options is work.
thanks a lot.

how about number format?

**Comment by pascalbaljet** [comment]
I've added a section to the documentation about watching form values:
https://splade.dev/docs/custom-form-components
