### ISSUE TITLE
how can i pass default option selected in x-splade-select Component

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#76]
![image](https://user-images.githubusercontent.com/8742640/195832983-8045d3e4-7510-42ab-b29d-1a9f62c1e9e3.png)

![image](https://user-images.githubusercontent.com/8742640/195833181-de60b636-0586-4d31-8fef-4339447b811a.png)

**Comment by bdsumon4u** [comment]
Pass **default** parameter to **splade-form** component.

![Screenshot from 2022-10-14 18-49-15](https://user-images.githubusercontent.com/75123992/195850992-2fc10170-6886-41cf-9f44-cbff05671222.png)

See **Default data** section from the doc of [Form](https://splade.dev/docs/x-form) component.

**Comment by sahnb** [comment]
Finally, I pass directly data to option but , still facing issue selected option doesn't print.
![image](https://user-images.githubusercontent.com/8742640/195852966-265e3dc9-4ad5-4c2c-b5ec-09c6b9af2872.png)

**Comment by pascalbaljet** [comment]
```blade
<x-splade-form :default="['currency_pair_type_id' => $currencyPairType->id]">
    ...
</x-splade-form>
```

**Comment by sahnb** [comment]
Thank you, solved now .
