### ISSUE TITLE
How to get relation data in form 

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#78]
![image](https://user-images.githubusercontent.com/8742640/196004899-c3d679de-5033-4dee-997e-7e44b5e22959.png)
![image](https://user-images.githubusercontent.com/8742640/196004942-15e4b884-8933-425a-aa4b-e77f9ac3a149.png)
How i can get attributes from relation into Spade Form?

**Comment by sahnb** [comment]
![image](https://user-images.githubusercontent.com/8742640/196040667-63d03f23-10e1-4462-85f0-e3b859efa652.png)
 
Docs Link: https://splade.dev/docs/introducing-splade
resolved.

**Comment by sahnb** [comment]
![image](https://user-images.githubusercontent.com/8742640/198264330-0fcc0241-1cb3-4c23-bef2-c409c2898b17.png)

**Comment by MotionPhix** [comment]
> ![image](https://user-images.githubusercontent.com/8742640/198264330-0fcc0241-1cb3-4c23-bef2-c409c2898b17.png)

This still didn't work for me. It would be great if @pascalbaljet gave an insight on this, otherwise I am stuck.

**Comment by sahnb** [comment]
make sure by dd relation data link with your Model ?

**Comment by MotionPhix** [comment]
> make sure by dd relation data link with your Model ?

Yes, the relation is there. Even in the view, I am able to render the relation nicely but the values don't show in the inputs

**Comment by sahnb** [comment]
Please if possible to share your code snippet of  method and view?

**Comment by MotionPhix** [comment]
Alright, here we go.

![Screenshot_20221028_061417](https://user-images.githubusercontent.com/59722054/198685697-72910e88-ca04-47da-a6fd-618e0a30041d.png)

The above picture shows a function for editing a customer. It calls a modal from the view

![Screenshot_20221028_061520](https://user-images.githubusercontent.com/59722054/198685958-06e9f8c2-b54b-4795-8c6d-d7e2a5bb2bd2.png)

The above picture is a view in a modal that gets opened by the function in the very first picture. It is in this modal view where the values don't show up

![Screenshot_20221028_061614](https://user-images.githubusercontent.com/59722054/198686267-966d1ac2-09b6-4cd8-b9cb-bc80f8b41c2d.png)

The above picture is a a customer model

**Comment by sahnb** [comment]
i guess you need a foreach loop to fetch data from get

**Comment by MotionPhix** [comment]
That's actually not the reason because I just changed that to see what data I would get in a collection. Look at the working code from the pictures below.

![Screenshot 2022-10-28 184629](https://user-images.githubusercontent.com/59722054/198690641-5fe56c86-150e-4dbc-bec5-202476900895.png)

The above picture is the working code. Let me show you what happens

![Screenshot 2022-10-28 184726](https://user-images.githubusercontent.com/59722054/198690919-f6ba0785-bb04-441b-b009-107fc90f7e43.png)

The above is a data table displaying all contacts (currently there is only one contact). If click on the edit icon from the **ACTIONS** column, i get the following modal

![Screenshot 2022-10-28 184814](https://user-images.githubusercontent.com/59722054/198691297-a524a86d-fc4f-4999-9f27-39875cf98812.png)

You see how the phone number is missing but the rest of the data is showing?

**Comment by sahnb** [comment]
Which version are you using? even i check by implementing modal, perfectly work. and one more thing make sure mobile field exist typically must be in fillable of  Phone Model

**Comment by MotionPhix** [comment]
Laravel version 9.19
Laravel-Splade version 0.6.11

And here is the phone model

![Screenshot 2022-10-28 181700](https://user-images.githubusercontent.com/59722054/198694522-ef443074-ab08-4b9a-a9c0-6db37a157b99.png)

**Comment by sahnb** [comment]
In edit form that you are using in modal place this code   {{$customer->phone->mobile}} or {{$customer->phone}} after the    <x-splade-form> opening tag and what is the output?

**Comment by MotionPhix** [comment]
That one shows the phone like it is supposed to.

![Screenshot 2022-10-28 194027](https://user-images.githubusercontent.com/59722054/198699080-ad63e424-9a8d-4cdd-a950-b55c9c95915c.png)

**Comment by MotionPhix** [comment]
I have solved it by casting values in the :default property like in the picture below

![Screenshot 2022-10-28 203438](https://user-images.githubusercontent.com/59722054/198708242-bbe25552-aad5-4efc-997a-6dbdb06c6677.png)

It's working, but I feel like it's a hack. For now I get what I wanted.

![Screenshot_20221028_083720](https://user-images.githubusercontent.com/59722054/198708553-304e7903-a38c-4097-9ca1-2b0a59015fe5.png)

**Comment by pascalbaljet** [comment]
It has been fixed in v0.6.12. Nested relationships, like the example below, now work:

```blade
<x-splade-form :default="$project">
    <x-splade-input name="name" label="Name" />
    <x-splade-input name="organization.address.city" label="City" />
</x-splade-form>
```

**Comment by brunoalfred** [comment]
How to set default values on <x-splade-select > using the relationship

**Comment by brunoalfred** [comment]
How to set default values on `<x-splade-select` using the relationship
