### ISSUE TITLE
Modal is broken

### ISSUE THREAD

**Issue by MotionPhix** [protonemedia/laravel-splade#81]
With the latest release (0.6.2), the modal seems to be broken. Putting the modal to a different size doesn't work at all. Just the default size is working. It only works if I manually change the size with raw CSS by putting a *Style* tag on the modal element which, however, breaks the modal as it can't inherit the *style* attribute.

**Comment by pascalbaljet** [comment]
Whoops! It's fixed in v0.6.3 😉

**Comment by MotionPhix** [comment]
Patiently waiting for the update!
