### ISSUE TITLE
Select option multiple values selected with choices js on based relations attached or assigned value 

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#82]
I try to select the permission that was already to attach the role but, from the model, I get the data [1,2,3] but the select option was not selected or was the attached value pre-selected, what I did a mistake?
**![image](https://user-images.githubusercontent.com/8742640/196505616-e2254395-8524-43d0-b9f2-0389c43a75c9.png)**
as a option showing in both select option
![image](https://user-images.githubusercontent.com/8742640/196507573-b6c45a7c-4779-460f-85f8-d2eaba7f2d18.png)

![image](https://user-images.githubusercontent.com/8742640/196505844-c754ba7b-2817-473c-a50f-da75bcaed237.png)

![image](https://user-images.githubusercontent.com/8742640/196505367-554b819c-f484-42dc-8c98-45d4eccfd32f.png)

**Comment by pascalbaljet** [comment]
I've just release v0.6.4. It has a fix for this! Could you please [upgrade](https://splade.dev/docs/upgrading) and try Method 1 again?

**Comment by sahnb** [comment]
I updated as described in [Docs](https://splade.dev/docs/upgrading)
![image](https://user-images.githubusercontent.com/8742640/197012678-d386d142-6829-4e53-9c75-63820fc6493d.png)

![image](https://user-images.githubusercontent.com/8742640/197013157-d40f1227-c2cb-451e-a0f4-1e080a48983b.png)
![image](https://user-images.githubusercontent.com/8742640/197013624-91e06212-d25c-4c24-9236-404e09d580eb.png)

**Comment by sahnb** [comment]
still not matching and filtering the records from the selection options.

**Comment by pascalbaljet** [comment]
I can't reproduce the problem. All related tests also pass. Could you provide a code example or repo so I can quickly reproduce the problem?

**Comment by sahnb** [comment]
https://github.com/sahnb/laravel-splade-role-permission

**Comment by pascalbaljet** [comment]
Related to #96

**Comment by pascalbaljet** [comment]
Fixed in v0.7.3.
