### ISSUE TITLE
Form submit-on-change doesn't work with input dates

### ISSUE THREAD

**Issue by JapSeyz** [protonemedia/laravel-splade#84]
Hey,

```php
<x-splade-form submit-on-change action="xxxx">
<x-splade-input name="dates" date range/>
</x-splade-form>
```

Doesn't seem to auto-submit when a date-range has been selected.

**Tested in 0.6.2, not sure if it has been fixed in 0.6.5**

**Comment by pascalbaljet** [comment]
I've tried your code example and it seems to work fine, I can't reproduce it. I'm not sure if it helps, but could you upgrade to the latest version ([both PHP and JS](https://splade.dev/docs/upgrading))?

**Comment by pascalbaljet** [comment]
Thank you so much for your sponsorship, it really helps! 🙌🤗

**Comment by JapSeyz** [comment]
> I've tried your code example and it seems to work fine, I can't reproduce it.

Perfect. I'll assume it's fixed. (I don't have the original setup anymore as I just went with a different approach)

**Comment by JapSeyz** [comment]
> Thank you so much for your sponsorship, it really helps! 🙌🤗

Ofc, it's a wonderful lib!
