### ISSUE TITLE
[Feature Request] External Redirect

### ISSUE THREAD

**Issue by bdsumon4u** [protonemedia/laravel-splade#85]
What if I want to redirect to an external URL from a controller?
![External Redirect](https://user-images.githubusercontent.com/75123992/197345900-03511630-43a4-448c-b540-3aa96d34ab63.png)
Inertia has the feature.

**Comment by pascalbaljet** [comment]
Good point, I'll work on that!

**Comment by pascalbaljet** [comment]
Fixed in v0.6.6 🎉

It automatically detects redirects to external hosts, but if you want, there's a helper method that you may call on the Splade Facade in the controller:

```php
return Splade::redirectAway('https://splade.dev');
```

**Comment by pascalbaljet** [comment]
Docs: https://splade.dev/docs/navigation-routing
