### ISSUE TITLE
Open modals from vue components

### ISSUE THREAD

**Issue by MotionPhix** [protonemedia/laravel-splade#86]
I want to be able to open modals (which are basically views pointing to certain routes - like *posts/create.blade.php*. From the documenation there are just a few limited example usage to follow along. There's the this.$splade.visit, can this also open a modal? If yes, how?

**Comment by bdsumon4u** [comment]
I was also trying to open splade modal just like a normal modal, without route. But I couldn't.

**Comment by pascalbaljet** [comment]
You can use `this.$splade.modal(url)` instead of the `visit()` method.

**Comment by MotionPhix** [comment]
Oh, great. Does the this.splade object have type hints in Vue components?
We could probably use those to quickly know what's possible. What do you
think?

**Comment by pascalbaljet** [comment]
In that case, I think we should migrate to TypeScript. I'll open a new issue :)

**Comment by MotionPhix** [comment]
> You can use `this.$splade.modal(url)` instead of the `visit()` method.

Is it possible to open modals without binding them to a route?
