### ISSUE TITLE
Impossible to install with Laravel/framework v9.36.2

### ISSUE THREAD

**Issue by Kanww** [protonemedia/laravel-splade#88]
### **Hello,**

I was trying to install splade to test it to my laravel/vuejs project but I encounter a problem with the composer require command.
I got this message :

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework is locked to version v9.36.2 and an update of this package was not requested.
    - protonemedia/laravel-splade 0.6.5 conflicts with laravel/framework 9.36.0|9.36.1|9.36.2.
    - Root composer.json requires protonemedia/laravel-splade ^0.6.5 -> satisfiable by protonemedia/laravel-splade[0.6.5].
```

It appears that splade is in conflict with my version of laravel (and version 9.36.1 + 9.63.0). 
Can it be fix from my side ?

_Thanks you for you work 👍_

**Comment by pascalbaljet** [comment]
It's correct Splade is not compatible with those versions. There was an attempt by the Laravel core team to optimize Blade, but it was reverted in 9.36.3. So you need to upgrade the framework to *at least* that version and then install Splade.

In short, first run `composer update` and then install the Splade package.
