### ISSUE TITLE
Using Filepond Library for handling file uploading

### ISSUE THREAD

**Issue by LogicSatinn** [protonemedia/laravel-splade#90]
Hey there!

I really think it would be cool if we could use Filepond for file uploading. It makes things so clean and expressive.

What do you think?

**Comment by pascalbaljet** [comment]
Yeah that would be great! Would you like to upload the file when you hit the *submit* button of the form, or do you want the file to be uploaded beforehand, right after you pick it?

**Comment by MotionPhix** [comment]
> Yeah that would be great! Would you like to upload the file when you hit the _submit_ button of the form, or do you want the file to be uploaded beforehand, right after you pick it?

I think a bit of both. Like when there are other elements in the form then after hitting the submit button is the best option. And if I am updating a profile picture, then it should upload instantly

**Comment by LogicSatinn** [comment]
> Yeah that would be great! Would you like to upload the file when you hit the _submit_ button of the form, or do you want the file to be uploaded beforehand, right after you pick it?

@pascalbaljet I think ... uploading the file beforehand is better, especially with Filepond. It provides a better user experience. Developers can go as far as clearing the files stored in temporary storage if it may be an issue.

**Comment by pascalbaljet** [comment]
Added in v0.7.6 🚀

Docs: https://splade.dev/docs/form-file

It supports drag-and-drop, file size and type validation, image preview, image validation and async uploads. It also comes with an Artisan command to cleanup the temporary uploads.

**Comment by LogicSatinn** [comment]
> Added in v0.7.6 🚀
> 
> Docs: https://splade.dev/docs/form-file
> 
> It supports drag-and-drop, file size and type validation, image preview, image validation and async uploads. It also comes with an Artisan command to cleanup the temporary uploads.

This is massive. Thank you @pascalbaljet
