### ISSUE TITLE
can i use @stack('scripts') in root.blade.php ?

### ISSUE THREAD

**Issue by sahnb** [protonemedia/laravel-splade#95]
can i use @stack('scripts') in root.blade.php if yes then how ? i tried but not worked.
![image](https://user-images.githubusercontent.com/8742640/198850696-86197406-cba2-43e8-9988-177103ec3bc3.png)
![image](https://user-images.githubusercontent.com/8742640/198850713-73dcb812-f5e2-4892-a4d2-68e289989da5.png)

**Comment by pascalbaljet** [comment]
I don't think scripts outside the Vue app work, and I recommend using [Vue Components](https://splade.dev/docs/custom-vue-components). What are you trying to get to work?

**Comment by sahnb** [comment]
I want to use filepond or dropzone with input file, like show progress or preview before upload. Something like this currently it's displaying image name only.

**Comment by pascalbaljet** [comment]
In that case, you should use the [Vue adapter for Filepond](https://github.com/pqina/vue-filepond). I'm looking into [integrating](#90) Filepond.

**Comment by sahnb** [comment]
Thank you 👍

**Comment by pascalbaljet** [comment]
@sahnb FilePond integration is available in [v0.7.6](https://github.com/protonemedia/laravel-splade/issues/90#issuecomment-1317631453).

**Comment by sahnb** [comment]
> @sahnb FilePond integration is available in [v0.7.6](https://github.com/protonemedia/laravel-splade/issues/90#issuecomment-1317631453).

Thank you so much,
Laravel Documentation and Splade are now my highly active tabs. Just love it.
