### ISSUE TITLE
Does it work with Alpine JS?

### ISSUE THREAD

**Issue by MdAnowarHosen** [protonemedia/laravel-splade#97]
I have added Splade to my new project. In my project, I am using Tailwindcss, AlpineJS, and recently installed Splade. After installing Splade, Alpine JS not working!

**Comment by pascalbaljet** [comment]
Splade uses Vue.js, and Alpine.js is [not compatible](https://github.com/alpinejs/alpine/issues/101#issuecomment-575813315) with it. I recommed looking at the [Vue components](https://splade.dev/docs/custom-vue-components) docs.

**Comment by MdAnowarHosen** [comment]
Can you please add support for AlpineJS?

**Comment by MdAnowarHosen** [comment]
Does it work with jQuery?
