### ISSUE TITLE
[Question] Custom Form Inputs

### ISSUE THREAD

**Issue by JapSeyz** [protonemedia/laravel-splade#99]
Hi!

I've created a simple Blade Component  that acts as a radio input.
Selectable cards ala:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/2234034/199385308-98c4785a-7394-4f4d-ac48-a329d817c40e.png">

This is pure blade, no Vue in use.
It's a generic html `input type="radio"`  element. However the element doesn't seem to be submitted to the server, along with the additional form values.

(It works if I exchange it for `x-splade-input`, however this breaks the CSS, as it is nested and the selector `input:checked + label` will no longer work.

Is there a way to make form submission work with regular input fields, or get a splade input field without any nested markup?

**Comment by bdsumon4u** [comment]
Have you used v-model attribute?
For x-splade-* components, name attribute is enough. But in custom component, you've to use v-model attribute.

**Comment by JapSeyz** [comment]
I haven't tried that. I'll do that in the morning. Thanks for a swift response

**Comment by JapSeyz** [comment]
Ahh, it works wonderfully.

I was looking under `custom components` and `model binding`, but the docs were under the general `form` tab.

https://splade.dev/docs/x-form

Thanks

**Comment by JapSeyz** [comment]
Hmm, unfortunately this seems to not bind the initial value from the `default` attribute on the form.

Eg. the initial value is blank, instead of the value provided from the `default` attribute.

It works fine on `<x-splade-input`, which displays the correct value

**Comment by JapSeyz** [comment]
Ohh,

Somehow `<x-splade-input` is exempt from the `unguarded` prop in a form.

This works:
```blade
<x-splade-form :action="route('profile.update', $user)" :default="$user">
    <x-splade-input name="zip" label="{{ __('Zip code') }} *" required />
</x-splade-form>
```

This does *not* work:
```blade
<x-splade-form :action="route('profile.update', $user)" :default="$user">
    <input v-model="form.zip" required />
</x-splade-form>
```

This *works*
```blade
<x-splade-form :action="route('profile.update', $user)" :default="$user" unguarded>
    <input v-model="form.zip" required />
</x-splade-form>
```

Don't worry, this is just examples, for the sake of understanding. I am not unguarded the User model.

It feels strange that `<x-splade-input` as special privileges that reads the model even if the form is not unguarded.

What's worse. Even if i do `unguarded="name"`, and expect my form to be fully guarded; `<x-splade-input` will still read any attribute, even those that's aren't unguarded. 

Bug or intentional? @pascalbaljet

**Comment by JapSeyz** [comment]
Another question that belongs under custom form inputs:

I tried making the same Counter component in Vue, but I am having trouble figuring out how to bind my v-model to `form.{name}`. How do I access the `form` object, to bind to it?

I can't seem to find anything in the docs, nor by looking through the code.

**Comment by sahnb** [comment]
I try a lot to investigate how to post v-model sync with form object but didn't understand. if i prefixed the custom input , then renderless vue functionalities not worked.
`     <x-splade-form
            default="{redirectSlug}"
            :action="route('admin.keywords.store')"
            unguarded
        >

            <div class="shadow sm:rounded-md">
                <div class="bg-white py-6 px-4 sm:p-6">

                    <div class="mt-6 grid grid-cols-4 gap-6">
                        <InputSlug />
                        <Slug v-slot="{redirectSlug,setRedirectSlug,slugify}">
                            <div class="col-span-4 sm:col-span-2">
                                <x-splade-input
                                    v-on:input="form.$put('slug', slugify($event.target.value))"
                                    name="title"
                                    label="Title"
                                />
                            </div>
                            <div class="col-span-4 sm:col-span-2">
                                <x-splade-input
                                    name="slug"
                                    label="Slug"
                                />
                            </div>
                            <div class="col-span-4 sm:col-span-4">
                                <textarea
                                    name="redirectSlug"
                                    v-model="redirectSlug"
                                    @input="setRedirectSlug($event.target.value)"
                                    label="Redirect Slug"/>
                            </div>
                        </Slug>
                        <div class="col-span-4 sm:col-span-4">
                            <x-splade-textarea name="description" label="Description"/>
                        </div>
                        <x-splade-submit class="bg-gold-700 hover:bg-gold-900"/>
                    </div>
                </div>
            </div>
        </x-splade-form>`

**Comment by JapSeyz** [comment]
If I make a custom Vue Form component, how do I get acces to the `form` object within the component? In `<script setup>` and `<template>`

**Comment by sahnb** [comment]
Something like this, I am doing but when i submit the form with v-model="form. Slug" then input type value post. but slugify function isn;t in action. if i post with v-model="slug" , slugify function in action but form value isn't posted.
```
<script>
export default {
    props: {
        title: {
            type: String,
        },
        slug: {
            type: String,
        },
    },
    data() {
        return {
            title: '',
            redirectSlug: '',
            slug: '',
        }
    },
    methods: {
        setRedirectSlug: function (value) {
            this.redirectSlug = value.toString().toLowerCase()
                .replace(/--+/g, '-')
                .replace(' ', '-');
        },
        slugify(text, ampersand = 'and') {
            const a = 'àáäâèéëêìíïîòóöôùúüûñçßÿỳýœæŕśńṕẃǵǹḿǘẍźḧ'
            const b = 'aaaaeeeeiiiioooouuuuncsyyyoarsnpwgnmuxzh'
            const p = new RegExp(a.split('').join('|'), 'g')
            return text.toString().toLowerCase()
                .replace(/[\s_]+/g, '-')
                .replace(p, c =>
                    b.charAt(a.indexOf(c)))
                .replace(/&/g, `-${ampersand}-`)
                .replace(/[^\w-]+/g, '')
                .replace(/--+/g, '-')
                .replace(/^-+|-+$/g, '')
        }
    },
    render() {
        return this.$slots.default(
            {
                slug: this. Slug,
                setSlug: this.setSlug,
                redirectSlug:this.redirectSlug,
                setRedirectSlug: this.setRedirectSlug,
                slugify: this.slugify,
            });
    },
};

</script>

```

**Comment by sahnb** [comment]
have you handle the custom field , i am still not figure how to set input data from vue compmonent to Splade form input. if i set as 
`     <input
                                      v-model="form.title"
                                        label="Title"
                                    />`
when submit form didn't show in post data.

**Comment by sahnb** [comment]
If i do pass data as to input from vue :
` <x-splade-input
                                        name="title"
                                        v-bind:value="form.title=article.title"
                                        label="Title"
                                    />`
data perfectly populate into Splade input and post perfectly but its single way binding. i want with two way binding at somes time might be needed to re write article.
@pascalbaljet can you guide use. how can we set input data from fetching in api vue component and set into splade input.

**Comment by pascalbaljet** [comment]
@JapSeyz Regarding the *mailing list* example, if you have a User Model with a `project_type` attribute, you can pass the User to the `x-splade-form` component and fully unguard it or just unguard the `project_type` attribute. Now you can use the `form.project_type` as `v-model` for the radio inputs and for the `v-show` and `:class` directives. I've simplified the template as I don't want to paste a complete Tailwind UI component over here 😅

```blade
<x-splade-form :default="$user" unguarded="project_type">
    <h1>Select a mailing list</h1>

    <div class="grid">
        <label>
            <input type="radio" v-model="form.project_type" value="Newsletter" class="sr-only">
      
            <span class="...">Newsletter</span>
            <span class="...">Last message sent an hour ago</span>
            <span class="...">621 users</span>
    
            <svg v-show="form.project_type === 'Newsletter'" class="h-5 w-5 text-indigo-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
            </svg>
            
            <span :class="{
                'border-indigo-500': form.project_type === 'Newsletter',
                'border-transparent': form.project_type !== 'Newsletter'
            }" class="pointer-events-none absolute -inset-px rounded-lg border-2"></span>
        </label>

        {{-- Other labels... --}}
    </div>
</x-splade-form>
```

If you want to use a custom Vue component, there are a few options, but the most simple one (definitely not the purest one), is to pass the `form` object as a property:

```vue
<template>
    <h1>Select a mailing list</h1>

    <div class="grid">
       <label>
            <input type="radio" v-model="form.project_type" value="Newsletter" class="sr-only">
       </label>      
    </div>
</template>

<script setup>
defineProps({
    form: {
        type: Object,
        required: true,
    },
});
</script>
```

And then in the Blade template:

```blade
<x-splade-form :default="$user" unguarded="project_type">
    <Card :form="form" />
</x-splade-form>
```

I'll also post an example without passing the full `form` object.

**Comment by pascalbaljet** [comment]
If you don't want to pass the `form` object to the Vue component, you could also use a `v-model`  implementation:

```vue
<template>
    <h1>Select a mailing list</h1>

    <div class="grid">
        <label>
            <input
                type="radio"
                :checked="modelValue === 'Newsletter'"
                @change="$emit('update:modelValue', 'Newsletter')"
                value="Newsletter"
                class="sr-only"
            />

            <span class="...">Newsletter</span>
            <span class="...">Last message sent an hour ago</span>
            <span class="...">621 users</span>

            <svg
                v-show="modelValue === 'Newsletter'"
                class="h-5 w-5 text-indigo-600"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                aria-hidden="true"
            >
                <path />
            </svg>

            <span
                :class="{
                    'border-indigo-500': modelValue === 'Newsletter',
                    'border-transparent': modelValue !== 'Newsletter',
                }"
            ></span>
        </label>

        <!-- Other labels... -->
    </div>
</template>

<script>
export default {
    props: {
        modelValue: String,
    },

    emits: ["update:modelValue"],
};
</script>
```

And then in Blade:

```blade
<Card v-model="form.project_type" />
```

Next, I'll refactor this into a `CardLabel` component.

**Comment by pascalbaljet** [comment]
Here's the `CardLabel.vue` example:

```vue
<template>
    <label>
        <input
            type="radio"
            :checked="modelValue === value"
            @change="$emit('update:modelValue', value)"
            :value="value"
            class="sr-only"
        />

        <span class="..." v-text="title" />

        <svg
            v-show="modelValue === value"
            class="h-5 w-5 text-indigo-600"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
        >
            <path
                fill-rule="evenodd"
                d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z"
                clip-rule="evenodd"
            />
        </svg>

        <span
            :class="{
                'border-indigo-500': modelValue === value,
                'border-transparent': modelValue !== value,
            }"
        />
    </label>
</template>

<script>
export default {
    props: {
        modelValue: String,
        title: String,
        value: String,
    },

    emits: ["update:modelValue"],
};
</script>
```

And then in Blade:

```blade
<h1>Select a mailing list</h1>

<div class="grid">
    <CardLabel value="newsletter" title="Newsletter" v-model="form.project_type" />
    <CardLabel value="existing_customers" title="Existing Customers" v-model="form.project_type" />
</div>
```

**Comment by pascalbaljet** [comment]
I've added all of this to the documentation:
https://splade.dev/docs/custom-form-components
